### ISSUE TITLE
Subscrptions should be handled by clients only

### ISSUE THREAD

**Issue by rockstorm101** [nostr-protocol/nips#104]
> Upon receiving a REQ message, the relay SHOULD [...] then store that filter and send again all future events it receives to that same websocket until the websocket is closed. 

Silly question on NIP-01 [[1]]. Why make relays keep the websocket alive? Wouldn't it be simpler and less resource consuming to make relays just send the required posts when a REQ message is received and be done with it? A client that is "subscribed" simply queries the relays every given time interval with the same REQ. I fail to see the need to keep the connection to the relay alive and I'm assuming the less resources consumed by the relay the better.

[1]: https://github.com/nostr-protocol/nips/blob/master/01.md#from-client-to-relay-sending-events-and-creating-subscriptions

**Comment by fiatjaf** [comment]
Doing a database query every 5 seconds (which is probably the interval clients would use to poll relays for new stuff) is much more costly than keeping a websocket open and pushing new events to it.

Not to mention the extra complexity for the client (which is significant if we assume that there will always be more client implementations than relay implementations) and the network costs.

**Comment by rockstorm101** [comment]
Thanks for taking the time to answer and please forgive my ignorance here.

I would think of social media as something with a pace similar to email, i.e. polling interval of about 30min(?). 5 seconds sounds like an interval suited for instant massaging, which users have other apps for.

IMHO making relays as dumb as possible makes it easier to switch from one to another since implementations will be more similar. Keep relay implementations very basic and very strict so people don't innovate and truly all relays work alike. Otherwise some users might find some relays have features that others don't and then switching relays is not that easy. Which defeats the whole purpose of avoiding censorship and/or server abandonment.

Again, thank you for your patience. I know I'm late to this debate anyway.

**Comment by cjackie** [comment]
> Why make relays keep the websocket alive?

In practice, relays will probably need to close the connection once "REQ" is EOSE, for better scaling, and client implementation should prepare for this kind of disconnection. And, I just learned that Damus client closes the subscription once it is done.
