### ISSUE TITLE
NIP proposal structure

### ISSUE THREAD

**Issue by phyro** [nostr-protocol/nips#106]
I believe NIPs could benefit from a certain structure. Structure requires more time from the writer, but may save time for the reader and the implementer.

I suggest we use a template for NIPs to save the reader time and to make it obvious what it is about. The reader should get an idea of what we're trying to solve before reading the implementation and this is why `Motivation` section is added. Given that the nostr system has a very simple design, I think we could require a test vector example to help people implementing it to check a few basic cases and potentially enumerate some edge-cases. Below is an example NIP template:

NIP-XX
======

Summary
------------------------

We describe in one or two sentences _WHAT_ this is.

Motivation
------------------------

We describe _WHY_ we'd want this feature. What properties does the system have today and what properties do we get by implementing and using this NIP?

Design & Implementation
------------------------

We describe _HOW_ this feature works. This includes clearly stating which kinds, tags are used and how. If it's a multistep scheme, we describe the steps etc.

Test vectors
------------------------

We make some basic test cases for the NIP. Below we make a test case which makes 4 sequential actions. First it makes two EVENT requests followed by two REQ requests. Here's a basic form for test vectors:
```json
[
  {
    "req": ["EVENT", ...],
    "expected_response": {...},
  },
  {
    "req": ["EVENT", ...],
    "expected_response": {...},
  },
  {
    "req": ["REQ", <subscription_id>, <filters JSON>...],
    "expect_response": {...},
  },
  {
    "req": ["REQ", <subscription_id>, <filters JSON>...],
    "expect_response": {...},
  },
]
```

We get a list of actions to execute on our relay and their expected results. This should be simple enough to test. If we need more expressivity, we can extend the structure, but let's start with a simple structure.

**Comment by fiatjaf** [comment]
Thank you for the suggestion. My first opinion after reading this is that we can manually encourage people to put test vectors and written explanations in NIPs, but I don't like the strictness of having a fixed template.
