### ISSUE TITLE
NIP-90 job result confusion

### ISSUE THREAD

**Issue by alexgleason** [nostr-protocol/nips#1075]
Kind `6xxx` job results can include an `amount` tag, but how can there be a result already if an invoice still needs to be paid?

As a DVM, I'm confused about when to send job feedback and when to send a job result.

"It's up to the DVM" doesn't make sense. There needs to be an unambiguous way to determine if the job is finished.

Here's how I think the flow *should* be:

1. User creates Job Request
2. DVM sends Job Feedback with status = "payment-required"
3. User zaps the _Job Feedback_ event (or pays the bolt11 invoice)
4. DVM sends a Job Result

How it currently works(?):

1. User creates a Job Request
2. DVM might send a Job Feedback or a Job Result
3. If the Job Result has an `amount`, the job isn't really finished, and you need to zap it
4. Or, if you got a Job Feedback instead, you need to pay its invoice
5. Depending on what happened before, you might get a Job Result if you didn't already, or you might get a Job Feedback with status = "success"

Why are there two ways to indicate that a job is finished? Why should I _ever_ use Job Result to indicate that a payment still needs to be made, and why am I only allowed to zap Job Result events instead of Job Feedback events to make the payment?

**Comment by alexgleason** [comment]
@pablof7z @staab Can you guys tell me if I'm being dumb here? The spec is confusing and the stuff I found in the wild doesn't actually match the spec. Does the spec need to be updated?

**Comment by pablof7z** [comment]
No, if you get a job result with an amount the job is finished but unpaid.

Imagine a Coffeeshop where you order a coffee and get the coffee and the bill at the same time as opposed to paying and then getting the coffee.

The idea is that this is flexible enough to make different business models possible (ie full pay up front, partial upfront, or fully pay after the fact and if you don't pay your bills I'll stop serving your pubkey)

**Comment by alexgleason** [comment]
I think what's missing from the spec is that Job Feedback events can have an `amount` tag. The example flow I shared above has it, and it makes sense, but it's not present in the spec.

**Comment by alexgleason** [comment]
Never mind, I must have hallucinated that. What the heck.
