### ISSUE TITLE
Feature Request: Markdown Support

### ISSUE THREAD

**Issue by joe-rodgers** [nostr-protocol/nips#110]
Would it be possible to build markdown into the protocol or should that be handled on the client side?

**Comment by eskema** [comment]
how about we keep kind-1 as plain text and you guys can play with markdown on another kind? seems better than have clients force dumb formats on everyone.

**Comment by fiatjaf** [comment]
Why no one has ever asked for Markdown on Twitter?

**Comment by gkbrk** [comment]
Markdown prides itself on being equally functional as unrendered plain text and rendered HTML. To imply that glorious Markdown text content needs to be annotated and additional functionality needs to be written to handle it is an insult to Markdown.

**Comment by fiatjaf** [comment]
Markdown is a scam, it is in fact very bad at being readable without special formatting. If it was indeed readable as plaintext this issue would have never been opened and people would be writing Markdown on Twitter.
