### ISSUE TITLE
REMOVE command

### ISSUE THREAD

**Issue by mikedilger** [nostr-protocol/nips#1118]
I wish to delete events on my relay. Maybe because they are spam. After the relay AUTHs me, it will accept DELETE commands which simply pass event IDs.

These are not delete events!  They do not propagate to other relays. Clients never see these.  It is just a command to delete the local event from the specific relay.

But we do not have a DELETE command in nostr.

Do people think this command is a good idea, or is it too much out of scope for nostr? Most clients probably would never issue DELETE commands. It could well be done in some out-of-band way too.

**Comment by alexgleason** [comment]
The way I'm doing it is the relay can have admin pubkeys configured, and then admins can do normal kind 5 deletions of events they don't own.

**Comment by vitorpamplona** [comment]
I like the idea that Clients should be able to manage personal relays via Nostr-native interfaces (via events, either in a RPCs protocol like NIP-46 or by modifying a replaceable event the relay is watching, etc). That could be a DVM-like system running in or outside the relay that accepts requests to adjust the relay's properties from a given set of admin pubkeys. A Delete method could just be one of the available commands to Clients.

 It would be awesome if all relay devs could agree on a set of methods for personal relays.

**Comment by mikedilger** [comment]
Having thought a bit more, I think it should be called REMOVE to avoid confusion.

I would *love* if someone built a web-based relay moderation system, that popped up alerts for 1984 events, showed a moderation queue, did REMOVE commands, etc... and such a tool being 100% independent of the relay implementation.

**Comment by alexgleason** [comment]
Check out how I'm doing relay moderation here: https://docs.soapbox.pub/ditto/nsec/#event-deletions

The relay has its own nsec and publishes events from it. Kind 5, 3, 10000, 10002, 10006, etc all have a semantic meaning when published from the relay nsec.

**Comment by vitorpamplona** [comment]
> I would love if someone built a web-based relay moderation system, that popped up alerts for 1984 events, showed a moderation queue, did REMOVE commands, etc... and such a tool being 100% independent of the relay implementation.

If you make Chorus notify and reply, I will code the client on Amethyst.

**Comment by mikedilger** [comment]
> Check out how I'm doing relay moderation here: https://docs.soapbox.pub/ditto/nsec/#event-deletions
> 
> The relay has its own nsec and publishes events from it. Kind 5, 3, 10000, 10002, 10006, etc all have a semantic meaning when published from the relay nsec.

That is one way to do it, but not my preference.

> If you make Chorus notify and reply, I will code the client on Amethyst.

Ok I'll start a NIP.

**Comment by mikedilger** [comment]
https://github.com/nostr-protocol/nips/pull/1169
