### ISSUE TITLE
URIs attached to NIP-05 identifiers

### ISSUE THREAD

**Issue by Synesso** [nostr-protocol/nips#115]
Would it be reasonable to extend NIP-05 (or maybe it's just separate metadata standard) to allow optional URLs that clients could use to hyperlink domain identifiers.

e.g. given `jem@satsophone.tk` is a nip-05 verified id, and `https://bitcoin.org/bitcoin.pdf` is configured as the id uri, then clients may choose to render the id as a hyperlink to that url: [jem@satsophone.tk](https://bitcoin.org/bitcoin.pdf)

**Comment by fiatjaf** [comment]
I may be missing your point, but I don't think it makes sense. The NIP05 names are meant to identify Nostr profiles/pubkeys, not to make general unrelated links. It is better to use kind0 events for that.
