### ISSUE TITLE
Type of NIP-46 message has changed

### ISSUE THREAD

**Issue by alexgleason** [nostr-protocol/nips#1154]
- Original document: https://github.com/nostr-protocol/nips/blob/4bb393735ea501f0bac3e2cb255ae9a3caab6a68/46.md
- New version: https://github.com/nostr-protocol/nips/blob/master/46.md

New version says `[<json_stringified_event_to_sign>]`

Old version just says `[event]`

Did we change this on purpose? Or it slipped through the cracks, or what?

**Comment by alexgleason** [comment]
I'm implementing a new Nostr Connect thing and it's incompatible with my old thing.

**Comment by alexgleason** [comment]
It was changed in https://github.com/nostr-protocol/nips/pull/1047 @erskingardner 

I think this was just overlooked, right? We should change it back.

**Comment by fiatjaf** [comment]
It was always implemented as the stringified garbage.

**Comment by erskingardner** [comment]
Yeah, I just tried to make the original doc more clear. Anything you put in an even must be stringified to be valid JSON.
