### ISSUE TITLE
Mute by kind

### ISSUE THREAD

**Issue by SnowCait** [nostr-protocol/nips#1156]
It would be nice to be able to mute particular pubkey's kind like "mute retweets" in X (Twitter).

- Reposts (kind 6, 16)
- Reactions (kind 7)
- Zaps (kind 9735)
- etc

### JSON

Based on [NIP-51](51.md) sets.

```json
{
  "kind": 30007,
  "content": "<encrypted tags>",
  "tags": [
    ["d", "<kind>"],
    ["p", "<pubkey 1>"],
    ["p", "<pubkey 2>"]
  ]
}
```

### Tags

- `d` (MUST): kind string
- `p`s (MAY): pubkeys
  - Same as kind 10000

**Comment by alexgleason** [comment]
I like your solution.

It seems the `k` tag is only included for aesthetic purposes. I would remove it and filter by `d` tag.

**Comment by SnowCait** [comment]
Indeed.
