### ISSUE TITLE
Empty tag

### ISSUE THREAD

**Issue by yukibtc** [nostr-protocol/nips#1193]
Should empty tag be allowed in events? Like:

```json
{
      "id": "11f22b4683f0aaf7060778cfafd2d62ae34648e43029bc75ee9e1bcd19366849",
      "pubkey": "97c70a44366a6535c145b333f973ea86dfdc2d7a99da618c40c64705ad98e322",
      "created_at": 1712189994,
      "kind": 10002,
      "tags": [
        [], // <==
        [
          "client",
          "Coracle",
          "31990:97c70a44366a6535c145b333f973ea86dfdc2d7a99da618c40c64705ad98e322:1685968093690"
        ]
      ],
      "content": "",
      "sig": "a4b3a034963702e7b8bb514dec692741fdd00ba41d4d4cb73decb753b2c226097ce8d0d66a25dea2896d06a5b981c4eeec498a29fe70ff21193ad1d995b1ccd8"
}
```

In `rust-nostr` libs empty tags aren't allowed, the same in `strfry` and `chorus` relays. But relays like `nostr-rs-relay` allow them.

Currently NIP01 specify this for tags: "Each tag is an array of strings of arbitrary size". So apparently empty tag should be allowed (?)

Ref https://github.com/rust-nostr/nostr/issues/411

**Comment by fiatjaf** [comment]
Would be nice if we could prevent them but I think it's impossible at this point.

Still I think it's nice if libraries and relays disallow them as much as possible.

**Comment by Giszmo** [comment]
nip01 should be explicit there and I agree to disallow empty arrays.

**Comment by mikedilger** [comment]
It was not intentional that chorus would throw an error on an empty tag. I'm working to fix that now. I think they should be discouraged but not be seen as errors.

**Comment by mikedilger** [comment]
fixed in chorus

**Comment by Giszmo** [comment]
So we don't prescribe? Not allowing empty arrays warrants filing issues with those relays then? I'm indifferent to the resolution but would prefer to be explicit.
