### ISSUE TITLE
last word (advisory)

### ISSUE THREAD

**Issue by mikedilger** [nostr-protocol/nips#1204]
A tag `["lastword"]` meaning that a note is the last word, and any replies will not be shown by clients that support the last word NIP.  Of course other clients can reply to it and see replies to it, but clients supporting the NIP will voluntarily suppress replies to notes marked with this.

Sometimes you get into a back and forth and just want to say something and end it, but the other party just keeps replying and you feel like you have to reply again to that.  If the other party could see that you don't want yet another reply, and if you knew that most other clients won't be seeing additional replies, you can more easily exit a bad conversation.

My client will allow people to reply to 'lastword' events with the warning that the reply may not be seen by other clients, just because I want to enable my users.  But default setting will be supression of replies to lastword notes.

I don't plan to implement this soon, I have too much else to do. But I wanted it out of my head so I could sleep.

**Comment by staab** [comment]
This seems like a bad idea to me. Dunking/blocking is a pretty dark pattern of legacy social media. If you're in one of these terrible conversations and you want to exit, it requires the humility of leaving the last word to the other person, and ignoring the thread. Post + mute thread seems more healthy to me.

**Comment by fiatjaf** [comment]
This is decided.

**Comment by fiatjaf** [comment]
Unfortunately GitHub doesn't follow this NIP and doesn't suppress replies, so my joke didn't work.

**Comment by vitorpamplona** [comment]
I am not sure if the NIP review process should consider "what's good for the user" in the discussion. That kind of nanny state thinking is what went wrong with regular social media in the first place. 

Clients can do whatever they want, of course.

**Comment by staab** [comment]
Every decision any of us makes is based on an ethical framework. That's why we're here making censorship-resistant social media in the first place. It can only speak for myself that I probably won't adopt a certain feature, and the NIPs repo is not for gatekeeping the protocol, but that doesn't imply ethical discussions are out of scope.

**Comment by pablof7z** [comment]
Concept NACK.

We don't need a NIP to guardrail what is a personal responsibility. I also sometimes find myself in stupid arguments that are clearly not going to lead anywhere, at that point my `lastword` NIP is just closing the computer and going outside.

https://njump.me/nevent1qqsdlnrxr8sl3hup2xnj84yaqpa49awkgd54f4dzzfpyvllfxekl9pqpzpmhxue69uhnzdps9enrw73wd9hszrthwden5te0dehhxtnvdakqz8thwden5te0dehhxarj94c82c3wwajkcmr0wfjx2u3wdejhgqg0waehxw309ahx7um5wghx6mmdqy08wumn8ghj7mn0wd68ytnnv46xsen0wfc8y6tkv93hjtnrdaksz9rhwden5te0wfjkccte9ejxzmt4wvhxjmcpz3mhxue69uhhyetvv9ujumn0wd68ytnzvuq3vamnwvaz7tmjv4kxz7fwwpexjmtpdshxuet5qgs04xzt6ldm9qhs0ctw0t58kf4z57umjzmjg6jywu0seadwtqqc75srl5q3l

**Comment by vitorpamplona** [comment]
This is not an ethical question. The question is: do we want a common standard for clients to create a way for users to opt-out of a thread or do we want each of them to create their own ways, which might not converge? 

It doesn't matter if the thread itself is worth having or not. The ethics of it are irrelevant. 

I say, if there are users and clients in need of this, it should be a NIP.

**Comment by staab** [comment]
> The question is: do we want a common standard for clients to create a way for users to opt-out of a thread

That is the ethical/values-based question. The rest of the question about interoperability is dependent on whether this feature will exist at all, which I'm just expressing my preference about.

lastword 😂

**Comment by vitorpamplona** [comment]
> whether this feature will exist at all

That's my point. We are not here to debate if features will exist or not. If people want, they will exist. If ONE client codes it, they will exist. It doesn't matter if we all code it or not.

The only thing this repo can do is, given that it will exist, what's the best way to make it happen?  

Concept NACKing is irrelevant to the proponent.

**Comment by fiatjaf** [comment]
What if we just assume it will not exist? Then we don't have to do anything.

**Comment by vitorpamplona** [comment]
> What if we just assume it will not exist? Then we don't have to do anything.

I assume @mikedilger wouldn't create a PR if this is not an actual need.

**Comment by vitorpamplona** [comment]
Either way, I am fine with this PR. 

#lastword

**Comment by mikedilger** [comment]
I proposed this in order to help the women on nostr who are complaining that women are leaving nostr.  I read through the "harassment" threads that cause some of them to leave.  And it was clear in one of them that the women did not want further replies, but also couldn't help but to read further replies and reply yet again to them.  Is it her fault for not having the humility to allow the asshole the last word?  Is it her failing for not just walking away?  Yeah, sure, you can see it that way if that is your ethos.

The idea wasn't to give someone the power to silence someone else. It was to signal "I'm leaving now, I won't read your reply". But I suppose someone could just type that into their note.

I'm really not even sure how my proposal is unethical. But I won't start a flame war about it.  If you think I'm unethical, fine. I play the black sheep fairly well.

In any case, if it won't be supported elsewhere I won't do it.

**Comment by staab** [comment]
I think trying to address this use case is a good thing. Maybe another approach would be Rabble's best-effort block functionality. Like delete, not everyone has to respect it, but it would be a good signal for well-behaved clients to support.
