### ISSUE TITLE
Can ownership of a replaceable event be reassigned?

### ISSUE THREAD

**Issue by xeruf** [nostr-protocol/nips#1217]
What if I have an event like a blog post or a task, and want to reassign it to another person to have full authority to manage (edit) the event. Is that possible?

**Comment by fiatjaf** [comment]
No.

**Comment by vitorpamplona** [comment]
You can create a new key that will be controlled by all users with editing permissions. 

On #1189, we encrypt the key in the `p` tag of each user. That allows them to fully (and unilaterally) control the replaceable event. 

You can even create two keys, one for the signers and another for viewers only.

**Comment by Giszmo** [comment]
That would be a different pubkey then. An existing pubkey/d-tag replaceable event cannot be transferred to somebody else.

**Comment by vitorpamplona** [comment]
Correct. I just provided one of the ways to solve this very common use case.
