### ISSUE TITLE
NIP-05 reflectivity

### ISSUE THREAD

**Issue by majestrate** [nostr-protocol/nips#127]
a common issue with activity pub i have seen in the wild is in practice it turns into a giant XSRF sending network that you can get thousands of servers to do a GET request to a single url. activity pub has no way to authenticate if this is something that the server wants.

in NIP-05, this problem exists too. a malicious actor would be able to very trivially use a server that serves the `/.well-known/nostr.js` endpoint to redirect to an arbitrary other location and CORS lets it go cross origin again. one could flood with new bogus users to redirect the thousands of GET requests to whatever url they want, as many times as they want.

NIP-05 should explicitly disallow any kind of redirects to prevent this.

**Comment by fiatjaf** [comment]
Can you edit NIP-05 to add a line disallowing redirects? Redirects are a cancer of the internet.

**Comment by majestrate** [comment]
yup. there should also be clear requirements backoff with refetches here too to prevent servers that arent serving this endpoint from being spammed hard.

**Comment by majestrate** [comment]
or... perhaps use a DNS record to opt out of this that admins can set to prevent their server being hit. without notice.

**Comment by fiatjaf** [comment]
No, I don't think we should do the DNS stuff.

**Comment by majestrate** [comment]
fair.
