### ISSUE TITLE
nip-01 limit length of tags to 255 and length of tag to 255

### ISSUE THREAD

**Issue by mleku** [nostr-protocol/nips#1278]
this is a purely practical consideration, for the reason of encoding the size of lengths of the arrays compactly in binary forms

there doesn't seem to be a good reason to allow the tags field to have more than 255 elements, nor the tag elements to have more than 255 sub-elements

if this were stipulated as a limitation it would greatly assist in making for more space-efficient binary encoding of events

it might also make sense to limit the size of individual tag elements to 64kb so they can have size prefixes of 2 bytes

**Comment by sant0s12** [comment]
What about the length of the tag string?

**Comment by mleku** [comment]
well, i'd want it to be max 32 bits, ie 4Gb, at minimum, yes, making it 16 bits would be nicer, and limit tag strings to 64kb

i'll include that in the idea

**Comment by alexgleason** [comment]
Sounds like an extension to NIP-11, not NIP-01: https://github.com/nostr-protocol/nips/blob/master/11.md#server-limitations

We already have a `max_event_tags`. Could add a `max_tag_length`

**Comment by fiatjaf** [comment]
I agree except for the fact that contact lists have more than 255 elements almost always because people follow a lot of others and shove everybody in the contact list event as tags.

**Comment by vitorpamplona** [comment]
On the next protocol we need to bake these limits in the verification procedure. If it's over 255 tags or if one tag has more than 10 elements it simply doesn't verify the event. 

It would have forced everyone to break their lists down into manageable groups from the start.

**Comment by fiatjaf** [comment]
I agree. What else? We must make a list so others won't commit the same mistakes.

**Comment by vitorpamplona** [comment]
Actually, It would be fun to have a live document just collecting all of our learnings into a hypothetical next protocol. I think we could all learn a lot from it. I know @melvincarvalho would love to see it.

For instance, I would add these ones: 
- The incoming byte array (on the websocket's channel) must be the same byte array to create the id hash. That avoids verifiers having to reallocate lots of memory just to re-encode things before hash-checking the event just to immediately throw that memory out. 
- Native support for byte arrays in the format would be awesome. No more wasted space with hexes, bech, base64s, and other encoders to force things into JSON strings, especially with encrypted events. 

I just recently found this [EVE](https://github.com/beve-org/beve) format and I am in love with it :)

**Comment by staab** [comment]
I think @mikedilger has something like this

**Comment by mikedilger** [comment]
I've been trying to remember these things here:  https://github.com/mikedilger/nostr-next  (previously on text files on my computer which may have even more).  Many of the suggestions/solutions in that repo are probably wrong, but I wanted to note down the issue at least.

My thoughts are:
* It would be bad for somebody to split off to make another nostr-like protocol that forks the community,
* If we decide it is worth the high cost, we should all do it together
* I don't think we are ready to make that decision

**Comment by mleku** [comment]
i'm closing this because follow lists

i didn't think it through
