### ISSUE TITLE
Best way to implement encrypted and secure instant messaging?

### ISSUE THREAD

**Issue by juanguillermo040488** [nostr-protocol/nips#1280]
Hello! I'm looking for a way to use Nostr to design an instant messaging client, similar to WhatsApp or Telegram.

I understand that NIP04 is already obsolete and replaced by NIP-17, but I still can't understand it.

I am assuming that:
a) There are 2 users: Alice and Bob.
b) The conversation between them takes place in a Room Chat.

So:
1. How should Bob send a message to Alice? Does Alice need to share her public key with Bob? Something like "Hey! Write to me here." That would be an implementation similar to other clients I've seen that still use NIP04.

2. How should Alice retrieve all the conversations she has had? Similar to the main screen of WhatsApp or Telegram, which shows all the chats. Is there a way for the client to retrieve/filter all of Alice's Room Chats?

3. Assuming there is a way to solve point 2, does this retrieval get all the messages from all the Room Chats? Is there a way to retrieve only the last n messages and asynchronously retrieve the rest as Alice scrolls up in the conversation?

4. Is there any specification or metadata that marks a message as read or unread?

I appreciate any guidance, tutorials, comments, or help you can provide.

**Comment by vitorpamplona** [comment]
Welcome! 

1. How should Bob send a message to Alice?

Bob creates a kind 14, seals it in a kind 13, and creates a gift wrap (kind 1059) with Alice's public key as a p-tag. 
Bob then creates another wrap to save the message for himself. 

Bob and Alice download all GiftWraps that tag each of their keys.  

2. How should Alice retrieve all the conversations she has had? 

Download all gift wraps, decrypt them, and select the kind 14s. 

3. does this retrieval get all the messages from all the Room Chats? 

Yes, The public cannot know which wraps are messages and which wraps are noise or other kinds. The only person that can see that is Alice's with her private key. 

> Is there a way to retrieve only the last n messages and asynchronously retrieve the rest as Alice scrolls up in the conversation?

No, you have to store them all locally. Ideally, GiftWraps don't survive for a long time on relays. If Alice doesn't download a copy of messages locally it will likely disappear in time. 

> Is there any specification or metadata that marks a message as read or unread?

No. This would be a huge privacy issue.
