### ISSUE TITLE
3-digit NIPs now exist

### ISSUE THREAD

**Issue by alexgleason** [nostr-protocol/nips#1287]
Now NIP-01 should become NIP-001:

![image](https://github.com/nostr-protocol/nips/assets/3639540/679b4b27-855a-4000-9ff4-f9398ab8be88)

**Comment by fiatjaf** [comment]
This is wrong, who merged this broken number?

**Comment by fiatjaf** [comment]
Fixed.

**Comment by alexgleason** [comment]
Good, but we won't be able to delay the inevitable much longer. There are truly almost 100 NIPs.

**Comment by fiatjaf** [comment]
We can always recycle older NIPs.
