### ISSUE TITLE
NIP-26 may be entirely dead

### ISSUE THREAD

**Issue by mikedilger** [nostr-protocol/nips#1299]
I don't have a single event in my database of 1.35 million events that has a "delegation" tag.  So I'm presuming people don't use NIP-26.  

There are problems
1. It doesn't become useful until the vast majority of clients support it.
2. It doesn't become useful until the vast majority of relays support it too.
3. Relay support wouldn't have been necessary if the delegation tag was a single letter and could be searched by a filter.

I can't even check on popular relays right now to see if anybody uses delegation.  How do I find all the events with a "delegation" tag when filters can only specify single-letter tags?  I can't.

I think we should remove this defunct NIP.

**Comment by vitorpamplona** [comment]
Yes. 

Good to go! https://github.com/nostr-protocol/nips/pull/1051

**Comment by fiatjaf** [comment]
It was never alive in the first place.

**Comment by mikedilger** [comment]
Ok I see the other issue #1051 I'll close this.
