### ISSUE TITLE
NIP-01 & NIP-16: why integer instead of descriptive string event kind?

### ISSUE THREAD

**Issue by nullpraxia** [nostr-protocol/nips#130]
i want to understand the event kind type design decisions in NIP-01 and NIP-16:

using strings for kind seems preferable to me:

- no indirection or ranges to manage
- human readable 
- facilitate namespacing of different event types

**Comment by eskema** [comment]
> * no indirection or ranges to manage
ranges are good to have
> * human readable
numbers are perfectly readable by humans if they are the meaning (i.e. not an indice of something else)
> * facilitate namespacing of different event types
what do you mean by this? what would that achieve in nostr?

**Comment by nullpraxia** [comment]
> numbers are perfectly readable by humans if they are the meaning (i.e. not an indice of something else)

that's what i mean by indirection, the kind numbers are being index into meanings specified in NIPs.

using meaningful strings could relieve us of the burden of memorising and/or looking up what numbers and ranges map to.

> ranges are good to have

they seem necessary for integer kinds, yes, but regarding namespacing ...:

> what do you mean by this? what would that achieve in nostr?

... instead of declaring ranges like (10000 <= n <= 20000) and mapping those to "replacible events" as in NIP-16, nostr could have kind prefixes which namespace the purpose:

"base/set_metadata", "base/text_note", "base/recommend_server"
"regular/*"
"replacable/*"
"ephemeral/*"

**Comment by fiatjaf** [comment]
I used to see only cons to this idea, thanks to this issue I see pros too, so thank you for that. But anyway it is a waste of time to argue now because we can't change it anymore.

**Comment by nullpraxia** [comment]
it would certainly take a lot of effort to coordinate the change across implementations, yes!

**Comment by eskema** [comment]
> that's what i mean by indirection, the kind numbers are being indexed into meanings specified in NIPs.

it this case, the numbers do not change, so the number = the meaning is what I was alluding to, in contrast, mentions numbers are an indice and do not carry any meaning by themselves, you need to look them up every time. when I see kind-1, I already know it's meaning, I don't need to check a list for it (only if I never heard of it, but i'd need to check a new name too..)

**Comment by nullpraxia** [comment]
@eskema i would agree that new kind names may sometimes require initial human investigation, but they would still convey more than raw numbers, and would serve as mnemonic facilitators for human retrieval/retention of meaning

i do have similar concerns about abbreviated tag names like "e"/"p"/"r"

these are at least specified as type string (although they seem very similar to kind), but i don't see an advantage to using abbreviations over descriptive labels

in any case, as @fiatjaf points out the protocol may be too widely implemented now to conveniently modify to this extent at this level

**Comment by eskema** [comment]
yes, I agree it would be more descriptive but that's what we have now, and it's totally workable, doesn't merit the effort to change IMO. 
the abbreviations on tags are for relay indexing. they only index known 1 letter tags, so it acts as a reserved space for that.
