### ISSUE TITLE
NIP-05 redirect security doesn't work for nginx reverse proxy

### ISSUE THREAD

**Issue by trbouma** [nostr-protocol/nips#1328]
Recently, Amethyst implemented the NIP-05 security constraint not to allow returning redirects.  This is causing my verification to fail. It seems like ngnix does an internal redirect for https and this is causing the fail. 

Any help/insight would be appreciated. My nginx file is below

```
server {
    
    server_name openbalance.app;

    root /var/www/openbalance.app;
    index index.html;

    location /test {
        try_files $uri $uri/ =404;
    }

    

     location / {
           include /etc/nginx/proxy_params;
           proxy_pass http://127.0.0.1:8081;
	   proxy_set_header content-type "application/json";
       }



    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/openbalance.app/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/openbalance.app/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}


server {
	if ($host = openbalance.app) {
        return 308 https://$host$request_uri;
    	} # managed by Certbot

    server_name openbalance.app;
    listen 80;
    return 404; # managed by Certbot


}
```

**Comment by trbouma** [comment]
@vitorpamplona do you have any detail on what you had implemented for the nip-05 redirect security constraint?

**Comment by vitorpamplona** [comment]
I am not sure if the issue is on nignx. It could be in the openbalance app 

This is the path it's taking now: 

https://openbalance.app/.well-known/nostr.json?name=trbouma 

307	Temporary Redirect	

http://openbalance.app/.well-known/nostr.json/?name=trbouma	

308	Permanent Redirect	

https://openbalance.app/.well-known/nostr.json/?name=trbouma

**Comment by trbouma** [comment]
I believe these are due to an nginx directive inserted by certbot. 
```
if ($host = openbalance.app) {
        return 308 https://$host$request_uri;
    	} # managed by Certbot

```


I am investigating if I can modify these certbot directives. If anyone else is using nginx, i'd appreciate to see what they have done.

I am also seeing if I can get caddy to work as my reverse proxy and see if I get the same problem. Stay tuned!

**Comment by trbouma** [comment]
I fixed it. In my app, I had a trailing slash in my nostr.json path 
```

./well-known/nostr.json/

```

Otherwise, it worked perfectly fine as nginx handled it in the reverse proxy, making it a redirect (307 or 308). Once I removed the trailing slash, it become a 200 OK response.

Thanks for your help, @vitorpamplona !
