### ISSUE TITLE
[NIP-01] What should setting a "limit" in multiple REQ filters do?

### ISSUE THREAD

**Issue by bezysoftware** [nostr-protocol/nips#1368]
REQ message can contain multiple filters and each can have a `limit` specified. What should happen if they differ across filters? Does it even make sense to have a limit per filter, shouldn't there be just one per REQ message?

**Comment by bezysoftware** [comment]
Duplicate of #725

**Comment by fiatjaf** [comment]
One count for each filter makes the most sense to me, as in my relay implementation each filter in the array is treated independently.

**Comment by bezysoftware** [comment]
Agreed, at first I didn't see the usecase for doing a limit per filter. Might be worth elaborating on it in the nip, since I'm not the first one to not get it right. I'll try to do a PR
