### ISSUE TITLE
Reactions to a website

### ISSUE THREAD

**Issue by nikolat** [nostr-protocol/nips#1380]
I would like to react to a website.  
There are some services that can do it, but they are centralized.  
https://s.hatena.ne.jp/  
I would like to achieve it with Nostr.  

Am I allowed to use a `kind 7` event that contains the `r` tag?  
Or should I use an event other than `kind 7`, such as `kind 17`?  

```json
{
  "kind": 7,
  "content": "⭐",
  "tags": [
    ["r", "https://example.com/"]
  ],
  ...other fields
}
```

[NIP-25](https://github.com/nostr-protocol/nips/blob/master/25.md) states "The reaction event SHOULD include `e` and `p` tags."

**Comment by alexgleason** [comment]
You are allowed to do anything you set your heart to.

**Comment by vitorpamplona** [comment]
I prefer to just reuse kind 7 with the `r` tag.

**Comment by staab** [comment]
I think repurposing kind 7 with an r tag makes perfect sense. A new kind might be better though, since you mightvwant to query these reactions without getting all the normal ones.

**Comment by nikolat** [comment]
Thanks.
I think a new kind is better.
I will create a pull request with `kind 17`.

**Comment by nikolat** [comment]
I could make what I wanted.
https://nikolat.github.io/makibishi/
And many people used it.
https://zenn.dev/nikolat/articles/800b19c6b6cc2e#%E8%AC%9D%E8%BE%9E
Thank you!
