### ISSUE TITLE
What's the correct way to specify `client` tag?

### ISSUE THREAD

**Issue by alopatindev** [nostr-protocol/nips#1389]
I'd like to label all my events with a client I used.

[Gossip](https://github.com/mikedilger/gossip) seems to do [this](https://njump.me/nevent1qqsx3pzlxfd46sk8k2sh8ps3cyynqy76wm4jpza5wqf9ekya2zyle8qzyqalp33lewf5vdq847t6te0wvnags0gs0mu72kz8938tn24wlfze6yct6gm):

```
"kind": 1,
"tags": [
  [
    "client",
    "gossip"
  ],
```

Is it actually a correct `client` tag?

Is there a NIP that agrees on that?

To me it looks conflicting to NIP-89 Recommended Application Handlers, which [states](https://github.com/nostr-protocol/nips/blob/master/89.md#client-tag):

> This tag is a tuple of `name`, `address` identifying a handler event and, a relay `hint` for finding the handler event.

**Comment by pablof7z** [comment]
It's not a conflict; you can use name, or name + nip-89 identifier
