### ISSUE TITLE
X-only keys and ECDH have a problem

### ISSUE THREAD

**Issue by mleku** [nostr-protocol/nips#1398]
ECDH computations generate two different shared secrets based on whether the pubkey has a 02 or 03 prefix in their normal 33 byte compact encoding

i propose that a field in universally broadcast events, probably kind 0, advertise the sign of the pubkey in order to facilitate easier implementation of p2p encryption using ECDH shared secrets

the only other alternative is to add more complexity to conversation key negotiation and raises issues of privacy and forward secrecy

**Comment by staab** [comment]
The `02` prefix is hardcoded everywhere, doesn't that solve this?

**Comment by mleku** [comment]
not if key generators don't check for this, it's a definite party pooper for a new user just joining they use some random thing to make their key and then can't DM people because their client/keygen made a 3 key

nostr's use case for DMs is sabotaged by this problem and i only just became aware of it 8 months after diving into the protocol

i'm not the only one who has encountered this problem

not only is this issue affecting users adoption of nostr because of DMs, it's also impacting devs who are now avoiding trying to build on nostr DMs, as if the rest of the issues weren't enough on top

it's a showstopper for a serious social network, it needs to be fixed and i say both standardise key generators to only make 2 keys and that there should be some kind of flag embedded in kind 0s to help those who have 3 pubkeys not be excluded from the private conversations

**Comment by jeremyd** [comment]
woah, ok.  i need to research how to check for this.  i used to generate keys with openssl rand -hex 32 as suggested somewhere in some nostr docs.. uh oh lol.

**Comment by mikedilger** [comment]
NIP-01 refers to BIP340 which specifies implicitly choosing the Y coordinate that is even, and "thus our X-only public keys become equivalent to a compressed public key that is the X-only key prefixed by the byte 0x02."

So '3' keys are invalid nostr identities.

**Comment by mikedilger** [comment]
I'm not being dismissive in my prior comment, I'm just stating a fact.  I'm doing some research and testing because some things aren't adding up for me just yet.  For example BITKARROT says she has a 03 key, but we have sent DMs to each other.  I'm writing code to test 03 keys.  Apparently Schnorr signatures will work and verify with an odd key or we would have noticed this sooner.

Finally, mea culpa, gossip has been generating randomly either 02 and 03 keys since Aug 2023 when I switched to libsecp256k1 which doesn't force keys to be even.

**Comment by mikedilger** [comment]
My tests indicate that even and odd keys interoperate just fine. Whether or not your key is even or odd, you can create the same shared point as your even-or-odd conversation partner.  I just did it with 1 even and 1 odd key, and they got the same shared point.

**Comment by vitorpamplona** [comment]
This is not an issue. The shared key used in Nostr is also just the X component. The Y component of the input public key is being ignored and thus it is irrelevant. Both 02 and 03 keys are valid Nostr keys.

Proof: 

All implementations of NIP04 and NIP44 append `02` to the pubkey before getting the shared key. Changing the code to append `03` to the pubkey before getting the shared key also works. 

Appending `02` works even if it's an `03` key.  
Appending `03` works even if it's an `02` key.

**Comment by mleku** [comment]
ok, maybe i did something wrong with the way i was using the bitcoin-core/secp256k1 library:

first, adding that 2 prefix:

```go
// ECPubFromSchnorrBytes converts a BIP-340 public key to its even standard 33 byte encoding.
//
// This function is for the purpose of getting a key to do ECDH.
func ECPubFromSchnorrBytes(pk B) (pub *ECPub, err E) {
	if err = AssertLen(pk, schnorr.PubKeyBytesLen, "pubkey"); chk.E(err) {
		return
	}
	pub = &ECPub{}
	p := append(B{0x02}, pk...)
	if C.secp256k1_ec_pubkey_parse(ctx, &pub.Key, ToUchar(p),
		secp256k1.PubKeyBytesLenCompressed) != 1 {
		err = errorf.E("failed to parse pubkey from %0x", p)
		log.I.S(pub)
		return
	}
	return
}
```

next the actual ecdh calculation:

```go

func ECDH(sec *Uchar, pk *ECPub) (secret B) {
	secret = make(B, sha256.Size)
	uSecret := ToUchar(secret)
	C.secp256k1_ecdh(ctx, uSecret, &pk.Key, sec, nil, nil)
	return
}
```

when i used this with a key generation function that didn't do this:

```go

func GenSecBytes() (sk32, pkb B, err error) {
	// because we must not create pubkeys with odd/0x03 prefix we have to derive the pubkey in this process anyway, and
	// so we must use the bitcoin-core/secp256k1 library or pay a performance penalty if we want to generate a lot of
	// new keys (for network transport MAC use case)
	sk32 = make(B, secp256k1.SecKeyBytesLen)
	for {
		var kp Sec
		kpk := newPublicKey()
		kpx := newXPublicKey()
		if _, err = rand.Read(sk32); chk.E(err) {
			return
		}
		usk32 := ToUchar(sk32)
		res := C.secp256k1_keypair_create(ctx, &kp.Key, usk32)
		if res != 1 {
			err = errorf.E("failed to create secp256k1 keypair")
			return
		}
		ecpkb := make(B, secp256k1.PubKeyBytesLenCompressed)
		clen := C.size_t(secp256k1.PubKeyBytesLenCompressed)
		pkb = make(B, schnorr.PubKeyBytesLen)
		var parity Cint
		C.secp256k1_keypair_xonly_pub(ctx, kpx.pk, &parity, &kp.Key)
		C.secp256k1_keypair_pub(ctx, kpk.pk, &kp.Key)
		C.secp256k1_ec_pubkey_serialize(ctx, ToUchar(ecpkb), &clen, kpk.pk, C.SECP256K1_EC_COMPRESSED)
		C.secp256k1_xonly_pubkey_serialize(ctx, ToUchar(pkb), kpx.pk)
		if ecpkb[0] == 2 {
			break
		}
	}
	return
}
```

a test checking that two keys were generating the same secret from sec1/pub2 sec2/pub1 found that when it was a 2 and a 3 on each side it didn't work

i see some stuff about how supposedly only the X coordinate is necessary but the function does not work without a 33 byte pubkey

this is the ecdh function i'm using: https://github.com/bitcoin-core/secp256k1/blob/fded437c4cec1a29921c90be325d62ba866f44ce/include/secp256k1_ecdh.h#L50

i'm confused because it definitely is not producing the same shared secret from both sides

my code is here:

https://github.com/mleku/nodl/blob/master/pkg/crypto/p256k/libsecp256k1.go

i'm searching for other info and not finding especially convincing information either way

it seems to me like the ecdh function can't be giving the same result from different pubkey bytes, and practically speaking, it's not the same key

as far as i can tell it's the most impossible thing to do, to find a secret key that has a pubkey that is exactly the inverse of another pubkey, there is literally only one

**Comment by mleku** [comment]
> I'm not being dismissive in my prior comment, I'm just stating a fact. I'm doing some research and testing because some things aren't adding up for me just yet. For example BITKARROT says she has a 03 key, but we have sent DMs to each other. I'm writing code to test 03 keys. Apparently Schnorr signatures will work and verify with an odd key or we would have noticed this sooner.
> 
> Finally, mea culpa, gossip has been generating randomly either 02 and 03 keys since Aug 2023 when I switched to libsecp256k1 which doesn't force keys to be even.

none of the libraries force the pubkey to be even, and the signatures verify either way

the thing is that this isn't really a big problem, it's just that you get two different secrets between a two keys that have different sign, but push one to be a 2 that is actually a three

that extra bit, bit 257 being different, means that it has to have come from a different secret key, so it's impossible to get the same ECDH shared secret if you use a 2 and the pubkey you are adding that to was a 3, on the other side, their secret does not derive a 2 key, and certainly not the one that is the same as the 2 key

i'm interested to know if there is some workaround or other facts that can be used to remedy this but it just doesn't make sense that ecdh only uses the X coordinate

**Comment by mleku** [comment]
oh and one other thing, i think it's likely to be a cheaper computation to not invert the secret using G but just roll the dice again and check... the frequency of pure random numbers falling out of the curve order is very low, like, idk how low but almost never at all more than two times the generation loops happen and gathering entropy is cheap compared to a modular division (which is also why schnorr is better than ecdsa)

**Comment by vitorpamplona** [comment]
> none of the libraries force the pubkey to be even

They should not force it to be even. 

Which secret are you calculating? NIP04 or NIP44?

Using `bitcoin-core/secp256k1` for NIP-44 it should be as simple as the `sharedX` here.

```
sharedX = secp256k1_ec_pubkey_tweak_mul(0x02 + pubkey, privateKey).copyOfRange(1, 33)
// hkdf.extract(sharedX, "nip44-v2".toByteArray(Charsets.UTF_8))
```

**Comment by mleku** [comment]
ECDH is ECDH

find a citation that specifies that there is a 1:1 relationship between a secret and both the 3 and 2 prefix on the same X-only pubkey please

there is not, the secret is entirely different between those two pubkeys and their secret

your test needs to actually see what happens when you put a proper 3 key with a 2 key and generate both sides of the ECDH

it is only because the type of elliptic curve used in most ECs are symmetrical that you can leave out all but the sign of the Y but that parameter is 1:1 related to the secret

different sign, different secret

**Comment by bitkarrot** [comment]
The only time I've encountered issues with DMs is on Primal, where my DMs seem to disappear after being sent to only 1 particular damus user, all other DMs are ok. DMs are recovered on other clients, so this might not be a protocol issue but rather a primal issue that rarely happens.

> I'm not being dismissive in my prior comment, I'm just stating a fact. I'm doing some research and testing because some things aren't adding up for me just yet. For example BITKARROT says she has a 03 key, but we have sent DMs to each other. I'm writing code to test 03 keys. Apparently Schnorr signatures will work and verify with an odd key or we would have noticed this sooner.
>

**Comment by mikedilger** [comment]
Logically I understand why you shouldn't expect a secret key paired to an odd pubkey to work the same as the secret key paired to that odd pubkey's even reflection, because it seems like that second secret key would be entirely different.

Yet my code (link above) shows it doesn't matter, I've held successful DMs with people that have 03 keys (I have an 02 key) and so that's enough for me.  I don't understand the crypto well enough to go any deeper or to debug the code above, but I linked my rust code (which just wraps the libsecp256k1 so should be comprehensible to non-rust people).

**Comment by bitkarrot** [comment]
fwiw, this example I look at for deriving shared secret using ECDH

https://github.com/bitcoin-core/secp256k1/blob/master/examples/ecdh.c

**Comment by mleku** [comment]
this is all easily fixable

1. all key derivation functions for nostr need to either 
  a. reroll and check the oddness by doing a standard compressed key derivation, or
  b. subtract the curve order G `fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141` to get the inverse secret

2. signer apps can check thet key sign and alert the user that the key is wrong and derive the inversion as per 1.b. and problem solved.

**Comment by fiatjaf** [comment]
Can you share a code snippet that shows how this is a problem?

**Comment by mleku** [comment]
this is how the change looks:

```
1722496996.366960459 INF (*secp256k1.SecretKey)(0xc0001462e0)({
 Key: (secp256k1.ModNScalar) dc9b902d43617009a428a36b09ec74b174551a23e9508b27c8f769106ecb01ba
})
([]uint8) (len=33 cap=33) {
 00000000  03 2c e7 fe 05 a3 31 ce  69 a6 c4 e2 be bf 05 fd  |.,....1.i.......|
 00000010  9f 76 fa 72 5f 39 01 ba  b7 55 0d 62 69 fb 6c 04  |.v.r_9...U.bi.l.|
 00000020  c1                                                |.|
}
 /home/me/src/git.replicatr.dev/pkg/crypto/p256k/btcec/btcec.go:29
1722496996.367139610 INF (*secp256k1.SecretKey)(0xc0001462e0)({
 Key: (secp256k1.ModNScalar) 23646fd2bc9e8ff65bd75c94f6138b4d4659c2c2c5f81513f6daf57c616b3f87
})
([]uint8) (len=33 cap=33) {
 00000000  02 2c e7 fe 05 a3 31 ce  69 a6 c4 e2 be bf 05 fd  |.,....1.i.......|
 00000010  9f 76 fa 72 5f 39 01 ba  b7 55 0d 62 69 fb 6c 04  |.v.r_9...U.bi.l.|
 00000020  c1                                                |.|
}
 /home/me/src/git.replicatr.dev/pkg/crypto/p256k/btcec/btcec.go:33
```

this is the btcec based code that does it, the main thing is the `Negate()` function:

```go
func (s *Signer) Generate() (err E) {
	for {
		if s.SecretKey, err = ec.NewSecretKey(); chk.E(err) {
			return
		}
		s.PublicKey = s.SecretKey.PubKey()
		s.pkb = s.PublicKey.SerializeCompressed()
		if s.pkb[0] == 2 {
			s.skb = s.SecretKey.Serialize()
			break
		} else {
			log.I.S(s.SecretKey, s.pkb)
			s.SecretKey.Key = *s.SecretKey.Key.Negate()
			s.PublicKey = s.SecretKey.PubKey()
			s.pkb = s.PublicKey.SerializeCompressed()
			log.I.S(s.SecretKey, s.pkb)
		}
	}
	return
}
```

i will have the `libsecp256k1` version done soon

**Comment by mleku** [comment]
```go
func ToUchar(b B) (u *Uchar) { return (*Uchar)(unsafe.Pointer(&b[0])) }

// Generate gathers entropy to generate a full set of bytes and CGO values of it and derived from it to perform
// signature and ECDH operations.
//
// Note that the pubkey bytes are the 33 byte form with the sign prefix, slice it off for X-only use.
func Generate() (skb, pkb B, sec *Sec, pub *XPublicKey, ecpub *PublicKey, err error) {
	skb = make(B, secp256k1.SecKeyBytesLen)
	ecpkb := make(B, secp256k1.PubKeyBytesLenCompressed)
	clen := C.size_t(secp256k1.PubKeyBytesLenCompressed)
	pkb = make(B, secp256k1.PubKeyBytesLenCompressed)
	var parity Cint
	ecpub = newPublicKey()
	pub = newXPublicKey()
	sec = &Sec{}
	for {
		if _, err = rand.Read(skb); chk.E(err) {
			return
		}
		usk32 := ToUchar(skb)
		if res := C.secp256k1_keypair_create(ctx, &sec.Key, usk32); res != 1 {
			err = errorf.E("failed to create secp256k1 keypair")
			return
		}
		C.secp256k1_keypair_pub(ctx, ecpub.Key, &sec.Key)
		C.secp256k1_ec_pubkey_serialize(ctx, ToUchar(ecpkb), &clen, ecpub.Key, C.SECP256K1_EC_COMPRESSED)
		if ecpkb[0] == 2 {
			C.secp256k1_keypair_xonly_pub(ctx, pub.Key, &parity, &sec.Key)
			pkb = ecpkb
			break
		} else {
			C.secp256k1_ec_seckey_negate(ctx, usk32)
			C.secp256k1_keypair_pub(ctx, ecpub.Key, &sec.Key)
			C.secp256k1_ec_pubkey_serialize(ctx, ToUchar(ecpkb), &clen, ecpub.Key, C.SECP256K1_EC_COMPRESSED)
			C.secp256k1_keypair_xonly_pub(ctx, pub.Key, &parity, &sec.Key)
			pkb = ecpkb
			break
		}
	}
	return
}
```

**Comment by mleku** [comment]
https://github.com/mleku/nodl/tree/master/cmd/keyfix

this is a little CLI tool that you give it nsec in either bech32 format or hex and it will print out in both formats and alert you if the pubkey was odd and negates it to get the correct one without changing the nostr BIP-340 pubkey

**Comment by vitorpamplona** [comment]
If the tool is not changing the "Nostr BIP-340 pubkey", how is it fixing anything? 

I still don't think there is anything wrong with keys. From NIP-44: "Execute ECDH (scalar multiplication) of public key B by private key A Output shared_x must be unhashed, 32-byte encoded x coordinate of the shared point"

Pubkey B on Nostr is just the x component. A scalar multiplication of an x component should return the shared x. The Y component is not part of the equations.

**Comment by fiatjaf** [comment]
Can you share a code snippet that shows how this is a problem by demonstrating how two keypairs cannot establish a shared secret if one of them is a "3"?

**Comment by mleku** [comment]
> If the tool is not changing the "Nostr BIP-340 pubkey", how is it fixing anything?
> 
> I still don't think there is anything wrong with keys. From NIP-44: "Execute ECDH (scalar multiplication) of public key B by private key A Output shared_x must be unhashed, 32-byte encoded x coordinate of the shared point"
> 
> Pubkey B on Nostr is just the x component. A scalar multiplication of an x component should return the shared x. The Y component is not part of the equations.

https://i.nostr.build/Z9EUa1zN0MldDCCJ.png it clearly states it in BIP-340

> Can you share a code snippet that shows how this is a problem by demonstrating how two keypairs cannot establish a shared secret if one of them is a "3"?

just generate a key that has a 3 in its 33 byte form, and another with a 2, then run them through an ECDH generation in both directions and see for yourself

**Comment by vitorpamplona** [comment]
> https://i.nostr.build/Z9EUa1zN0MldDCCJ.png it clearly states it in BIP-340

Correct. That is for Bitcoin, not for Nostr. In Nostr we just ignore the compression header. And it's ok to ignore. 

> it is the secret that is different, not the X coordinate, to be precise

The secret on NIP-44 uses only the X coordinate as an input. It CANNOT be different if you follow the spec. 

Here's a quick test I just generated. You can see how the SharedX is the same between them.

### 03-03 DM Key Test

PrivateKeyA = f410f88bcec6cbfda04d6a273c7b1dd8bba144cd45b71e87109cfa11dd7ed561
PrivateKeyB = 65f039136f8da8d3e87b4818746b53318d5481e24b2673f162815144223a0b5a

PubKey A 03 7d4b8806f1fd713c287235411bf95aa81b7242ead892733ec84b3f2719845be6
PubKey B 03 3dcef7585efbdb68747d919152bd481e21f5e952aaaef5a19604fbd096a93dd5

Public Key B: 3dcef7585efbdb68747d919152bd481e21f5e952aaaef5a19604fbd096a93dd5
Private Key A: f410f88bcec6cbfda04d6a273c7b1dd8bba144cd45b71e87109cfa11dd7ed561 
SharedX: 4439214fb975a1f45e532434ca6ab7042a3df64b7563c42fe91d28daa7518e71

Public Key A: 7d4b8806f1fd713c287235411bf95aa81b7242ead892733ec84b3f2719845be6
Private Key B: 65f039136f8da8d3e87b4818746b53318d5481e24b2673f162815144223a0b5a
SharedX: 4439214fb975a1f45e532434ca6ab7042a3df64b7563c42fe91d28daa7518e71

### 03-02 DM Key Test

PrivateKeyA = f410f88bcec6cbfda04d6a273c7b1dd8bba144cd45b71e87109cfa11dd7ed561
PrivateKeyB = e6159851715b4aa6190c22b899b0c792847de0a4435ac5b678f35738351c43b0

PubKey A 03 7d4b8806f1fd713c287235411bf95aa81b7242ead892733ec84b3f2719845be6
PubKey B 02 9fa4ce8c87ca546b196e6518db80a6780e1bd5552b61f9f17bafee5d4e34e09b

Public key B: 9fa4ce8c87ca546b196e6518db80a6780e1bd5552b61f9f17bafee5d4e34e09b 
Private key A: f410f88bcec6cbfda04d6a273c7b1dd8bba144cd45b71e87109cfa11dd7ed561
SharedX: 206c07b2ea34a92b88c4c44367b04b4ca31f1452069fdcad978e58d07b2f6c3a

Public key A: 7d4b8806f1fd713c287235411bf95aa81b7242ead892733ec84b3f2719845be6 
Private key B: e6159851715b4aa6190c22b899b0c792847de0a4435ac5b678f35738351c43b0
SharedX: 206c07b2ea34a92b88c4c44367b04b4ca31f1452069fdcad978e58d07b2f6c3a

**Comment by mleku** [comment]
```
# $ go run ./cmd/keyfix/. d5633530f5bcfebceb5584cfbbf718a30df0751b729dd9a789b9f30c0587d74e
# fixed key!
HEXSEC = 2a9ccacf0a43014314aa7b304408e75bacbe67cb3caac69436186b80caae69f3
HEXPUB = ff17bf710b09d1d36093c7af1a3ea9a8f43df3443bc51b84d5ea8a50db61807d
NSEC = nsec192wv4nc2gvq5x9920vcygz88twktue7t8j4vd9pkrp4cpj4wd8ess7hpc7
NPUB = npub1lutm7ugtp8gaxcync7h3504f4r6rmu6y80z3hpx4a299pkmpsp7spjf96c
```
d5633530f5bcfebceb5584cfbbf718a30df0751b729dd9a789b9f30c0587d74e

and 

2a9ccacf0a43014314aa7b304408e75bacbe67cb3caac69436186b80caae69f3

are two different secrets

they share the same public key X

ff17bf710b09d1d36093c7af1a3ea9a8f43df3443bc51b84d5ea8a50db61807d

what is ECDH?

**Comment by mleku** [comment]
@vitorpamplona it USES ECDH

which requires a 33 byte compressed key as the public key parameter

you didn't just invent some new scheme, at least according to the implementation in go-nostr it uses ECDH

**Comment by mleku** [comment]
https://github.com/mleku/ecdhtest

ok, that is my version that uses random keys and prints the ones with 3s in them, and indeed it seems that ecdh only cares about the X also

the only downside to not negating thet private key is you can't imply which of the old style bitcoin addresses (segwit and p2kh) would match a given npub

i think there could be a small performance hit on 3 keys though, because the signature matching tries the 2 variant first

but i'm definitely wrong about this, ecdh does only work with the X

it's not completely transparent to me exactly why, but good, closing, and apologies for being so salty
