### ISSUE TITLE
NIP 45 wording for kind 3 is confusing

### ISSUE THREAD

**Issue by bezysoftware** [nostr-protocol/nips#1435]
Looking at https://github.com/nostr-protocol/nips/blob/master/45.md the wording around event kind 3 is confusing, because kind 3 is replaceable, meaning the relays cannot really count the number of this event, but rather the number of pubkey inside content. Is this the expectation for kind 3? And are there any other such events (maybe they should be listed there)?

**Comment by mattn** [comment]
Yes, if count the events that the tags contains your pubkey, the number of events should be the count of your followers in the relay.

**Comment by bezysoftware** [comment]
I re-read NIP-45 & NIP-02 and actually they make perfect sense, my bad
