### ISSUE TITLE
Is NIP-07 decryptEvent(event) a good idea?

### ISSUE THREAD

**Issue by arthurfranca** [nostr-protocol/nips#1439]
Currently, asking an extension to decrypt something may end up granting a too broad of a permission to an app.

With a `decryptEvent` method, the extension is able,  e.g., to grant just private bookmarks decryption permisson to an app, which wouldn't allow the app to decrypt DMs.

It would be something like `async window.nostr.nip44.decryptEvent(event)`?

That are some complications:
- I'm not sure what such a method should return, because while most event kinds encrypt just the `event.content` field, some may encrypt one or more tags.
- The extension should be smart enough to know which pubkey to use, depending on what is the `event.kind`.

**Comment by vitorpamplona** [comment]
You will need to define a separate return for each event type. Lists would be the tag list inside of the `.content`. GiftWraps will return Events. Drafts return unsigned event templates. ZapEvents with private zaps should return the Private Zap event or null. Etc.

**Comment by fiatjaf** [comment]
I agree. Granting full decryption rights is bad.

**Comment by vitorpamplona** [comment]
Maybe the return should be the same event, but replacing the encrypted part by the decrypted string in place. So, it might replace the .content, or tags, or both. 

For spreadsheets and forms, for instance, the signer must try to decrypt every `p` or `key` it finds. The receiver must compare the object with the original to find out which tag positions were changed.

**Comment by staab** [comment]
> replacing the encrypted part by the decrypted string in place

This would break signatures, so decrypted events should be validated too.

> The receiver must compare the object with the original to find out which tag positions were changed.

Or, the caller could specify a list of paths to attempt decryption on. For example `[["content"], ["tags", 3, 1]]`

**Comment by paulmillr** [comment]
we can make a generic encryption scheme with nip44. I just need how an API would look like

**Comment by paulmillr** [comment]
What's pubkey? Who's pubkey is it? nip44 was made for conversations e.g. between Alice and Bob, so it's Alice's privkey and Bob's pubkey.

**Comment by paulmillr** [comment]
Understood. In this case, that seems like something which should be handled on a higher level than nip44.

I don’t see how nip44 is relevant here. Key storage should implement permission system, clients should implement it, then they do checks here and there and everything is working. Am I wrong?

**Comment by greenart7c3** [comment]
I think you want something like I did in this pull request

https://github.com/nostr-protocol/nips/pull/1354

I still haven't implemented in any apps but I will eventually

**Comment by paulmillr** [comment]
> Is it a direct message, is it a private mute list, or a private bookmark list?

Okay, so:

1. Decrypt it, `eventType = decrypted.type`
2. Utilize server-side storage to get permission list for the client X. `allowedTypes = getTypesForClient(key, 'x')`
3. Check if eventType is in allowedTypes

Am I missing something here?

No, we don't support AEAD, because there was no need for it.

**Comment by paulmillr** [comment]
I still don't understand what are the exact inputs and outputs. Can someone write code? e.g. something like

```
// client
data = ...
sendToServer(data)

// server
data = receiveFromClient()
...
```

> how easy would it be for a nip44 v3 to include AEAD

Anybody could create any "new version". But v2 was audited. So unless there is some really good update, I would not want to update it. Any new detail is potential data leak etc.

**Comment by paulmillr** [comment]
1. Why don't you put additional info like kind=98 into tags[3]?
2. Why don't you make 'hello mom' something like {"kind": 98, "text": "hello mom"}?

**Comment by vitorpamplona** [comment]
If all we want to do is to allow signers to manage decrypt permissions per kind, how about adding context to the current decrypt call? 

```
window.nostr.nip44.decrypt(pubkey, ciphertext, context: Event)
```

`ciphertext` must be included in the `context` and the signer must be able to verify the event.

If context is absent, the app is asking for broad permissions. If the context is present, the app is asking for individual permissions. The user can accept or reject broad and specific permissions separately.

**Comment by vitorpamplona** [comment]
> @vitorpamplona doesn't work, cause the pubkey argument isn't always the same as event.pubkey (e.g: your spreadsheets PR).

The pubkey should not be part of the verification anyway. The pubkey for the encryption should not be required to be in the event. It can come from another event or another decryption on the same event.

> In these cases the app could generate a fake event to use as context argument.

`ciphertext` still must be part of the event. The app cannot pass a fake event if the signer checks it.

**Comment by paulmillr** [comment]
> I return the question to you

It took a great deal of time to make everything polished. Then an auditor was hired for a bunch of money. Do you want to change something and stay secure? It's better to do the process again. Cryptography is not your average iterative code. Maybe ask BIP: 340 authors if they are iterating on a new iteration of it.

**Comment by paulmillr** [comment]
> why does AEAD even exists

There is no AEAD in NIP44. AEAD is supported in polynomial MACs such as AES-GCM and chacha20poly1305. We don't use polynomial macs.

**Comment by paulmillr** [comment]
So if you're not cryptographer, find a way to solve this without adjusting cryptography.

**Comment by vitorpamplona** [comment]
We can do a simple version of this were the singer checks if the decrypted payload is an event and uses that information to manage permissions. 

For DMs, for instance, the app will send the `.content` in the wrap, which will decrypt to show a kind 13 seal and decrypting the seal reveals a kind 14 DMs. The signer can decrypt first and they ask the user to authorize by kind. 

In that way, if a NIP knows this is available, it can format the encrypted payload as an event (even without signatures).

The Kind 51 encrypted tag list, for instance, could be turned into an event with kind and tag array instead of just the tag array. It's a simple change that can be done when we migrate from NIP-04 to NIP-44.

**Comment by paulmillr** [comment]
@arthurfranca can you stop mentioning me? I've unsubscribed myself from this issue.

@Semisol you're free to develop custom encryption schemes for anything.

**Comment by vitorpamplona** [comment]
> This does not provide much benefit compared to an AEAD scheme, and actually requires another layer of wrapping (event -> encryption -> another event -> actual data)

I'd say a custom AEAD scheme does not provide much benefit on top of a simple change like that. 

The wrapping will have to exist no matter what. It's either wrapped before the encryption or during the encryption by the AEAD itself.
