### ISSUE TITLE
Adding parse mode tag

### ISSUE THREAD

**Issue by kehiy** [nostr-protocol/nips#1442]
I think events can have a parsing mode like: `html5`, `markdown`, `pure/plain`, and more.

So we can use different parsing modes and embed different stuff on an event or even make webpages with an event and more.

This is the basic idea, If it's acceptable, I can work on NIP related to it.

**Comment by fiatjaf** [comment]
This is against criteria 4 for acceptance of NIPs and a big mistake, I think.

https://fiatjaf.com/27598e6f.html

**Comment by kehiy** [comment]
@fiatjaf where can I find list of criterias for acceptance of NIPs?

I read this article and it was logical for most cases. But in the case of parse mode, I think it don't need to be arbitrary parse modes from any client. Parse modes will be defined in the NIP and the is a low chance to add a new parse mode. But on the other hand we can support webpages and MD stuff in notes integrated on every client that implements this NIP.

What do you think? 

Over all that's not something for arbitrary value. That's a field which helps client to understand how to parse the note and at most it's some specific values such as HTML and MD.

**Comment by fiatjaf** [comment]
It's on the README. It's not a super hard criteria, but still.

I think I see what is your idea here and I can imagine scenarios in which we could have such tag, but they would be worst-case scenarios in which the protocol has already been bloated by added flexibility (i.e. some big corporate entity is capturing the network and has started producing HTML content and others are rushing to follow). Just adding this tag here is inviting extra work it for no reason and a move that can't be justified for me.

Another interesting read: https://this.how/standards/

**Comment by kehiy** [comment]
This post about standards was intresting and makes sense. But I still think we can have more disscustions on this. The current reason are logical but I think I can put more time on this and work on this idea details. I prefer to keep this open for a while and work on that more.

**Comment by vitorpamplona** [comment]
Different event kinds can have different formats. For instance, https://github.com/nostr-protocol/nips/pull/811 hosts HTML, CSS and JS files in the `.content` of each kind. 

Mixing formats in a single kind is not a good idea.

**Comment by kehiy** [comment]
@vitorpamplona So, do you think specific kinds with specific parse modes are good enough to use all the potential behind this idea?

Otherwise, that's logical to close this for me.

**Comment by vitorpamplona** [comment]
Yes, We have not seen the need for multiple formats in the same NIP/event kind.

**Comment by kehiy** [comment]
@vitorpamplona Got it. Thanks a lot.
