### ISSUE TITLE
NIP-17 How are relays supposed to "not serve kind:14 to clients other than the ones tagged in them"?

### ISSUE THREAD

**Issue by bezysoftware** [nostr-protocol/nips#1444]
The doc https://github.com/nostr-protocol/nips/blob/master/17.md#relays says 

`It's advisable that relays do not serve kind:14 to clients other than the ones tagged in them.`

How exactly are relays supposed to do that when the `kind:14` message is sealed & gift-wrapped? The relay will not know that the wrapped event contains a sealed kind:14

**Comment by vitorpamplona** [comment]
Wrong wording. It should be kind 1059 (the wrap).

**Comment by bezysoftware** [comment]
Makes sense, no one else will be able to decrypt them anyway
