### ISSUE TITLE
NIP-21 extension. Adding Nostr Data URI

### ISSUE THREAD

**Issue by vir2alexport** [nostr-protocol/nips#1447]
<s>### NIP-21 extension</s>
### NIP-22 extension
<s>**Nostr Data URI**</s>
**Nostr Smart Widgets**

<s>The idea is to store small files inline in nostr events.</s>
The idea is to introduce smart widgets.

<s>The rationale is when you store data as proposed with bossom or according to [NIP-92](../blob/master/92.md) and [NIP-94](../blob/master/94.md) guidance you can spot if the original file was edited and prevent the loading, but then you can't serve complete message to the end user. This is where nostr Data URI come into play to provide user with immutable data.</s>

For more info see [Data URLs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs),  [MIME type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types)

instead of creating new tlv, use naddr
`nostr:naddr1....`

More details below 👇

**Comment by staab** [comment]
NACK, this has been done before in the early days, and it has lots of problems associated with it. Relay operators do not want to store images, because they are often treated differently from text in terms of legal liability. Files of a size large enough to be useful are also a completely different problem in terms of implementation (postgres for example does weird things  like TOAST to deal with inline files). The only thing this could really be useful for are emoji and profile images, and even those aren't trivially small.

**Comment by vir2alexport** [comment]
> Files of a size large enough to be useful are also a completely different problem in terms of implementation

This proposal for small files. A tiny feature for exceptional cases. I have hundreds of scripts that are <10 KB, for example.

**Comment by vir2alexport** [comment]
Ok, let's try to come in from the other side, since I was intially thinking how to make widgets.

> Relay operators do not want to store images, because they are often treated differently from text in terms of legal liability.

can be limited based on mime-type, so let's say we have something like this
```
event.content = {
   mimeType: "<mime-type>",
   data: "<data>" //  <data> part of data-uri
}
```
and so as relay operator you can check the mime-type and then if you want dynamic content w/o legal liabilities / scripts / clicks etc, you use DOMParser to sanitize <data> and then if you're a client simply render like this
```
<img src="data:<mime-type>,<data>"
```
and if you want clickable objects you take the <data> part, parse it with DOMParser to sanitize scripts etc and get something like this
```
event.content = {
   mimeType: "image/svg+xml",
   data:'<svg viewBox="0 0 10 5" xmlns="http://www.w3.org/2000/svg"><a href="https://relays.xport.top" target="_blank"><rect width="10" height="5"><animate attributeName="rx" values="0;5;0" dur="2s" repeatCount="indefinite" /></rect></a></svg>'
};
```
and then you render it like so
```
element.innerHTML = event.content.data;
```

[EXAMPLE](https://plnkr.co/edit/9vUXQJntq5jtc6pm)

And so to make it into `nostr:ndata1....` we will need to extend tlv for that to be able to store let's say 128kB as this is in range with limits of most relays and so we end up with something like this
```
{
	hrp: "ndata",
	data: [
		{
			type: 0,
			length: 128000,
			value: {
                           mimeType: 'image/svg+xml',
                           data: '<svg viewBox="0 0 10 5" xmlns="http://www.w3.org/2000/svg"><a href="https://relays.xport.top" target="_blank"><rect width="10" height="5"><animate attributeName="rx" values="0;5;0" dur="2s" repeatCount="indefinite" /></rect></a></svg>'
                        }
		}
	]
}
```
is this makes sense?

> postgres for example does weird things like TOAST to deal with inline files

I don't really understand what the problem is. It seems to me that it has more to do with the knowledge to be able to work with data and depends on the relay operator.

**Comment by staab** [comment]
My point is, you can do what you want to put large payloads in events, but relays are generally going to block your events. Creating a NIP that recommends doing something that won't generally work on the network is an exercise in futility.

**Comment by vir2alexport** [comment]
> My point is, you can do what you want to put large payloads in events, but relays are generally going to block your events. Creating a NIP that recommends doing something that won't generally work on the network is an exercise in futility.

I can show you my event of kind 3 that is around 512kB and is on the network for at least a year and is still there. Anyway, thanks for your comment and for taking care of the network, I respect that. Widgets will appear one way or another and it will probably be better if we think about the standards before everyone will do what they decide for them.

**Comment by vir2alexport** [comment]
Another point I have completely forgot to mention is widgets are kind=30031 as proposed by NIP-22 which is **parameterized replaceable**, so it may solve the issue you were talking about.

**Comment by vir2alexport** [comment]
I just looked through all the widgets available on the network based on proposed in NIP-22 and the largest takes up about 6kB, so I think there is really nothing to worry about.

**Comment by staab** [comment]
Maybe I'm misunderstanding what you're trying to accomplish here, because I'm not sure how widgets relate. Are you talking about embedding widgets in kind 1 notes? Or using SVGs instead of widgets? I'm not quite following.

**Comment by vir2alexport** [comment]
I was thinking how to make widgets using what is already there, so that you don't have to reinvent the wheel for interpretation on the client's side

> Are you talking about embedding widgets in kind 1 notes? Or using SVGs instead of widgets?

Just like now I can write a long-form content and then link it with naddr/nevent [NIP-19](../blob/master/19.md) and reference according to [NIP-27](../blob/master/27.md) and [NIP-21](../blob/master/21.md), It seems to me widgets need the same mecahnics.

The most flexible imo is to use svg as you can describe any animation you want this way w/o scripts, but you can probably do similar things using html/css or whatever

I need some time to implement this and then we’ll continue if you don't mind.

**Comment by vir2alexport** [comment]
[NIP-22.md](https://github.com/user-attachments/files/16828699/NIP-22.md)

**Comment by melvincarvalho** [comment]
did you think about putting the mime type in a tag?

**Comment by vir2alexport** [comment]
#1468

**Comment by vir2alexport** [comment]
> did you think about putting the mime type in a tag?

can be done no problems
