### ISSUE TITLE
NIP-10: Eliminate marker "root" from "e" tag and prevent "p" tag explosion

### ISSUE THREAD

**Issue by 1l0** [nostr-protocol/nips#1451]
Let me explain by an image below because it's faster than squeezing out a sentence in English for me.
Every event should be considered relative; in other words, every event should be a root from a certain perspective. 
You should care this before it's too late.
![362098212-64d286bf-3628-422a-82d7-a32e9f93bbe8](https://github.com/user-attachments/assets/8bf982f0-5e3a-464e-ab89-84f83cfc7bfc)
Additionally, if you'd like to retrieve only immediate replies, there is currently no way to do that specifically. You would get recent events by time across the entire thread (somewhat randomly), rather than from shallow to deep by reply depth.

**Comment by AsaiToshiya** [comment]
Maybe it's already been discussed in #877 and #1233 will resolve it.

**Comment by 1l0** [comment]
@arthurfranca  Yeah, that’s what I thought. I fixed the image a bit.

**Comment by 1l0** [comment]
With https://github.com/nostr-protocol/nips/pull/1233 merged into the master branch, this will be closed as well. But NIP-10 should be deprecated.
