### ISSUE TITLE
NIP-05 which is the correct pub key format to return? 

### ISSUE THREAD

**Issue by brianoflondon** [nostr-protocol/nips#147]
Which is correct? Or do I have to make my server do the conversion when my users struggle to work out which one to use?

`npub1shlw9de7z7mjyaqsg59wyrcy8xcm52lfsp7j38yvvnmxg8vq97esmnlpzw`

`3dc473414bea4de1df1f172c3196a820719dbb58baaf8764b9edaa07c6d5e9dc`

**Comment by fiatjaf** [comment]
You must return hex.

But you should probably accept pasted npubs from your users and convert them. What language is your server written in? If it's JavaScript just do this to convert: https://github.com/nbd-wtf/nostr-tools#encoding-and-decoding-nip-19-codes

**Comment by brianoflondon** [comment]
Python. I'll have to update the server.

**Comment by brianoflondon** [comment]
Can anyone make this easy in python? I can't figure it out from that JS

**Comment by fiatjaf** [comment]
Here: https://github.com/jeffthibault/python-nostr/blob/181c1efa23f4335af9910764e176aab5852123f6/nostr/key.py#L25

**Comment by brianoflondon** [comment]
Thanks my gateway is working now and users can put either a Hex or npub string in their Hive profile. Closing this issue.
