### ISSUE TITLE
Can we have an "official" gitstuff event of this repo?

### ISSUE THREAD

**Issue by SilberWitch** [nostr-protocol/nips#1472]
Like the one we can see on [GitWorkshop](https://gitworkshop.dev/r/naddr1qqzxu6tswvqs6amnwvaz7tmwdaejumr0dspzqwt5zluywdxsrshfh67lk686m2sqnxuju6p3lul5u8k4fmyf8m00qvzqqqrhny64slsj), according to [NIP-34](https://github.com/nostr-protocol/nips/blob/master/34.md), but with the repo collaborators as maintainers?

**Comment by fiatjaf** [comment]
It's too soon, I think. It's better to experiment at the margins with smaller/newer projects first before we all get used with the NIP-34 stuff and the tooling is solid enough. It's horrible to have to fix things while depending on the same things we are trying to fix in order to fix them.

**Comment by mikedilger** [comment]
> It's horrible to have to fix things while depending on the same things we are trying to fix in order to fix them.

Your hammer head is coming loose. You need to hammer a few more nails into the top of the handle to wedge it tighter.

**Comment by SilberWitch** [comment]
Okay, but then can we all really have a Nostr git project, that we're actively testing NIP-34 with, that doesn't accept issues and proposals on GitHub? That they actually regularly look at and respond to?

I sometimes feel like I'm single-handedly testing NIP-34, and that's not going to cut it. It needs more traffic.

**Comment by melvincarvalho** [comment]
> Like the one we can see on [GitWorkshop](https://gitworkshop.dev/r/naddr1qqzxu6tswvqs6amnwvaz7tmwdaejumr0dspzqwt5zluywdxsrshfh67lk686m2sqnxuju6p3lul5u8k4fmyf8m00qvzqqqrhny64slsj), according to [NIP-34](https://github.com/nostr-protocol/nips/blob/master/34.md), but with the repo collaborators as maintainers?

Great idea!

GitHub is still a major point of centralization in the project. Ngit’s solid—I've been using it daily and think it’s ready for more. As probably the biggest ngit user (most repos!), I can say it works really well and will only improve.

Why not just start asking for collaborators and maintainers now? Those who prefer GitHub can use it, while others can work more decentrally on Nostr. No need to wait for some 'official' approval—who’s the Nostr CEO, anyway?

Let’s just do it. Happy to help!

**Comment by SilberWitch** [comment]
That's true. 🤔
