### ISSUE TITLE
NIP type field

### ISSUE THREAD

**Issue by kehiy** [nostr-protocol/nips#1476]
Beside `optional` and `draft` tags which determine the status and priority of a NIP, I think we need to add another field that determines whether this NIP must be implemented by relays/clients or both.

**Comment by bezysoftware** [comment]
I agree. Frankly I think we should also somehow categorize the NIPs / have a separate UI which will categorize NIPs based on this new tag.

 I want to track changes in the NIPs relevant to me (relay-based ones), but now my only option is to opt in for notifications on ALL changes in this repo and then mute those which are not relay related.

**Comment by kehiy** [comment]
@bezysoftware yes. adding tags on the top of `nips` + having github labels, will help developers to manage it better.

**Comment by kehiy** [comment]
for `nips` we can do that. but for github tags, members must do that, we can't.

**Comment by kehiy** [comment]
i can see most nips may not be for the relay, but they can affect the relay internals. or vice versa. so, i think that's hard to determine which nip affects which concept and probably most nips will be for both relay and client at the end of the day. so i think we need to close this.
