### ISSUE TITLE
NIP-65 how to handle inconsistent data from different relays

### ISSUE THREAD

**Issue by raymonostr** [nostr-protocol/nips#1489]
What if we receive different sets of NIP-65 lists for one hexpub from different relays?

Suggested solution: Use the most recent event over all responses.

**Comment by cesardeazevedo** [comment]
> Suggested solution: Use the most recent event over all responses.

That's correct as suggested on the NIP-01, any kind `10000 <= n < 20000 || n == 0 || n == 3` is a replaceable event and you should use the newest one.
> for kind n such that 10000 <= n < 20000 || n == 0 || n == 3, events are replaceable, which means that, for each combination of pubkey and kind, only the latest event MUST be stored by relays, older versions MAY be discarded.
