### ISSUE TITLE
Why doesn't NIP-22 use NIP-20 to notify that an event wasn't stored?

### ISSUE THREAD

**Issue by Satswalker** [nostr-protocol/nips#149]
NIP-22 (Event created_at limits) says relays should respond with a `NOTICE` message to notify that an event wasn't stored if the event's `created_at` field is outside of the relay's limits. Why is a `NOTICE` message used and not a NIP-20 Command Result? Could it be an oversight? NIP-20 looks like it would fit this use case pretty nicely.

**Comment by fiatjaf** [comment]
Good point. I think NIP-20 didn't exist when NIP-22 was created. 
We must change that. @jeffthibault @Giszmo

**Comment by jeffthibault** [comment]
Yup, NIP-20 did not exist at the time of NIP-22. I will make the change.

**Comment by fiatjaf** [comment]
Done.
