### ISSUE TITLE
addressable to parameterize replaceable?

### ISSUE THREAD

**Issue by kehiy** [nostr-protocol/nips#1491]
see https://github.com/nostr-protocol/nips/blob/8a427ea6d682a11416b2cccdd3e1aec492533cf8/01.md?plain=1#L81.
see https://github.com/nostr-protocol/nips/blob/8a427ea6d682a11416b2cccdd3e1aec492533cf8/01.md?plain=1#L98.

what is its name overall?

**Comment by staab** [comment]
parameterized replaceable but @fiatjaf would disagree

**Comment by kehiy** [comment]
@staab we must choose one at the ebd. Let's make the final decision here.

**Comment by AsaiToshiya** [comment]
See https://github.com/nostr-protocol/nips/pull/1437.

**Comment by kehiy** [comment]
@AsaiToshiya thanks. so, I'll close it and continue there.
