### ISSUE TITLE
NIP needs clerification in the definition of how filters must work

### ISSUE THREAD

**Issue by dukeh3** [nostr-protocol/nips#1520]
Hi.

I was trying to write a filter for an event with tag, ["v", "x", "y"]. Where v is the "key" and "x" and "y" are values. As far as I can read from the standard. Bouth the filter #v:["y"] and #v:["x"] should return the event. I would also expect that the tag ["v", "x", "y"] would be equivilant to the tags, ["v", "x"] and ["v", "y"] on an event. And I would say that its not clear if a tag can be there multiple times.

Now after a conversation with the guys behind strfry I understand that there implementation indexes only the "x" and if you want to have more tags on your event that are indexed that you should have more tags with the letter v, so  ["v", "x"] , ["v", "y"] would trigger bouth the x and the y, while ["v", "x", "y"] would only trigger on the x.

it would be great if it would be clearified.

**Comment by cameri** [comment]
Hey there!

NIP-01 says this about tags: Only the first value in any given tag is indexed.

**Comment by staab** [comment]
Yes, as of #1523 😂

**Comment by cameri** [comment]
Nice, so I wasn't wrong 🤣
