### ISSUE TITLE
NIP-XX: REST2NOSTR Proxy Proposal

### ISSUE THREAD

**Issue by rikmeijer** [nostr-protocol/nips#1549]
Title: REST2NOSTR Proxy for Shared Hosting Environments

Authors: rik@nostriphant.dev 

Status: Draft

Created: 27 oct 2024

Abstract:
This proposal introduces a REST-based proxy for Nostr relay interactions, intended for environments where WebSocket support is limited, such as shared hosting platforms. The REST2NOSTR Proxy enables clients to communicate with Nostr relays via simple HTTP REST endpoints, offering a more accessible method of connectivity while preserving the functionality of Nostr's protocol.

---

Motivation

Shared hosting environments often lack the necessary infrastructure for persistent WebSocket connections, which are essential for traditional Nostr relay communication. Challenges in such environments include:

1. Limited Running Processes: Shared hosting may restrict long-lived processes or may not allow dedicated processes for WebSocket communication.

2. Connection Overheads: Each interaction with WebSocket-based Nostr relays may require reconnection, leading to inefficiency and added overhead.

3. Intermittent Connectivity: Users on shared hosting are often unable to sustain persistent connections, limiting the effectiveness of real-time interactions.

By introducing a REST2NOSTR Proxy, we provide an alternative that allows shared hosting clients to interact with Nostr relays using HTTP REST requests. This bypasses the limitations of WebSocket requirements and allows for more flexible and compatible deployments in constrained environments.

---

Detailed Specification

1. REST Endpoint Structure

The proposed REST API endpoints would cover the fundamental actions in Nostr:

POST /event

Description: Allows clients to send a Nostr event to the relay.

Request Body: JSON object containing the Nostr event.

Response: JSON acknowledgment of the event's acceptance or error.

GET /req/<id>

Description: Retrieves a list of events from the relay, filtered by specified parameters.

Parameters: Optional query parameters for filtering (e.g., event kinds, author, tags).

Response: JSON array of matched events.

POST /req/<id>
PUT /req/<id>

Description: Allows clients to establish a subscription for specific event types.

Request Body: JSON object specifying the subscription filters.

Response: JSON acknowledgment of the subscription setup.

DELETE /req/<id>

Description: Allows clients to unsubscribe from specific subscriptions.

Request Body: JSON object specifying the subscription ID to cancel.

Response: JSON acknowledgment of successful unsubscription.

2. Relay Proxy Architecture

The REST2NOSTR Proxy would act as an intermediary between the client and Nostr WebSocket-based relays:

Client Request Handling: REST-based HTTP requests are received by the proxy, processed, and then converted to the appropriate WebSocket interactions with the Nostr relay.

Relay Communication: The proxy maintains the WebSocket connection with the Nostr relay on behalf of the client, thereby managing persistent connections.

Response Management: Events from the relay are converted into JSON and sent back to the client via HTTP response, allowing for periodic polling if real-time connectivity is limited.

3. Limitations and Considerations

Polling Overheads: In the absence of WebSockets, clients may need to periodically poll the /events endpoint to retrieve real-time updates, potentially introducing latency.

Connection Management: The proxy must handle multiple clients while maintaining efficiency, requiring mechanisms to limit resource consumption and maintain service quality.

Security Considerations: Authentication and rate-limiting must be implemented to prevent abuse of the REST endpoints.

---

Use Cases

1. Shared Hosting Applications
Applications hosted on shared environments can use the REST2NOSTR Proxy to interact with Nostr relays without the need for WebSocket support.

2. Lightweight Clients
Devices with limited connectivity can benefit from simplified, stateless HTTP interactions, reducing overhead.

---

Future Work

This NIP opens the door for additional extensions, such as:

Enhanced Event Filtering: Providing more granular filtering options for REST-based event retrieval.

Subscription Improvements: Options for long-polling or server-sent events (SSE) as a potential alternative to WebSockets for real-time updates.

---

Conclusion

This proposal suggests a REST-based proxy as an efficient alternative to WebSocket connections in constrained hosting environments. By introducing the REST2NOSTR Proxy, we provide developers with an option to maintain Nostr compatibility and functionality on platforms where WebSocket support is impractical. This enables broader adoption and flexibility within the Nostr ecosystem.

**Comment by fiatjaf** [comment]
This has been suggested many times in the past. It's not a good idea. WebSockets are fine. They can be used statelessly too in one-off requests if you need that. It is not a good idea to have two ways of doing the same thing.

**Comment by rikmeijer** [comment]
I must have overlooked these proposals, my apologies then. However the intent for this is not so much an alternative to relays, I agree that having two similar ways is not a good idea. The idea is to connect clients who can not run websockets permanently (shared hosting for example). It is a intermediate solution to allow a lot of websites to interact with the nostr network, without the overhead of starting a websocket client each request (or running a cron job). Do you have any ideas to an better solution connecting these sites to the network? Thanks in advance!

**Comment by rikmeijer** [comment]
I must have overlooked these proposals, my apologies then. However the intent for this is not so much an alternative to relays, I agree that having two similar ways is not a good idea. The idea is to connect clients who can not run websockets permanently (shared hosting for example). According to you websockets can be run stateless, which I concur. My guess was that spinning up a websocket for each request gave too much overhead/delay. Seeing no proposals on this I wanted to open that discussion first, too bad I missed that and wasted your time with it. Thanks!

**Comment by melvincarvalho** [comment]
+1000 it's the ONLY way to scale nostr which is struggling quite badly right now with scale

Typically in a REST API you would have /v1/ type things as the exact details can evolve and/or be refined

**Comment by melvincarvalho** [comment]
> They can be used statelessly too in one-off requests if you need that

While WebSockets can technically support stateless, one-off requests, they are fundamentally constrained by multiple round trips, which can severely impact performance. Additionally, WebSockets require a connection-oriented web server, presenting significant scaling challenges that make it difficult to support large-scale deployments. In contrast, the technique outlined in the original post has demonstrated the ability to handle billions of users efficiently and cost-effectively, with decades of proven data supporting its scalability and reliability

**Comment by franzaps** [comment]
+1 for REST support. Added HTTP to the Zapstore relay months ago.

I have had issues with websockets going stale, but HTTP ALWAYS WORKS.

@fiatjaf _everything_ is done in multiple ways in nostr, except this? I hope you can reconsider as this is limiting usage for no great reason. As much as I like `nak`, many more people have direct access to `curl` and it would be great for developers to interact with the network through it.

**Comment by fiatjaf** [comment]
Maybe everything else is broken, this is the only part that isn't and you want to break it too?

But actually this is not fair at all, we're all constantly trying to get rid of the multiple ways of doing things everywhere, and for most things there aren't: there is only one signature scheme, one way of doing auth, one event format and encoding, one kind for short notes, one syntax, one kind for long form, one way of saying who are your contacts, one way of defining your metadata with no duplicate or redundant fields, one way of attaching your pubkey to a DNS name and on and on.

And the thing you say is "except this" is actually 50% of the protocol, which means all the messages and back-and-forth between clients and relays, so a pretty big deal that also is done in only one way. Having stuff done in two ways is much worse than you are probably imagining.

WebSockets never go stale for me, but maybe some libraries out there are bad, I don't know, are you sending pings and answering pongs? If they go stale after many hours that may be understandable, but if you can keep a websocket open for the course of a handful of minutes that's already so much better than HTTP.

Also how are you going to do live event subscriptions without WebSockets? If HTTP was the we would see massive DDoSing of relays by people doing aggressive polling just because there is no other way and the relay ecosystem would collapse and we would all centralize in a big provider that was able to handle all of that.

Lastly, I dispute that developers are familiar with `curl`. Most aren't, and those who are generally are curious and interested enough to pick up `nak` or other tools to work on a new environment. Oh, by the way, you still need something on top of `curl` to sign events, and, even if you're just querying, to build filters beyond the most simple (the most simple are actually quite annoying without `nak` too).

If none of that convinces you then please just trust me on this.

**Comment by alexgleason** [comment]
@rikmeijer I think Nostr can still be integrated with shared hosting. It just can't be a relay. But it can be a client. That's still powerful. Most relays are public, so you don't even need to host one yourself. Therefore I think it should still be possible to integrate Nostr with WordPress, etc.

ChatGPT generated this for `websocket-php`:

```php
<?php
require 'vendor/autoload.php';

use WebSocket\Client;

try {
    // Connect to the WebSocket server
    $client = new Client("wss://example.com/websocket");

    // Send a message
    $client->send("Hello WebSocket Server!");

    // Receive a response
    $response = $client->receive();

    // Return the response to the downstream HTTP client
    echo "Response: " . $response;

    // Close the WebSocket connection
    $client->close();
} catch (Exception $e) {
    echo "Error: " . $e->getMessage();
}
?>
```

@sebastix is building PHP libraries in Nostr and could probably say more.

**Comment by franzaps** [comment]
@fiatjaf  Yes, using the word everything was not fair - I was thinking everything is optional besides NIP-01 - and I know you're making an effort to reduce the multiple ways of doing something. You're right.

The matter is settled apparently, but I will just leave my thoughts below.

I never meant HTTP _only_, obviously, so there would be no massive DDoS and all that if developers choose the right tools.

Being able to access via HTTP is not the same as using multiple signature schemes or different kinds for short notes, definitely not. The latter create massive interoperability issues, of course, whereas adding another way of interacting with relays does not. If would love to understand more about this nightmare scenario.

Not only I experienced issues with websockets but I heard it multiple times from multiple devs. Sure, we might be using bad libraries that don't handle this well? But again that raises the complexity. With HTTP the bar for participation in an open protocol couldn't be lower. From widgets to embedded systems, HTTP is always faster and easier. I'm positive that a factor in the general slowness we perceive in the average nostr client has to do with this - and that they connect to way too many relays.

You know better than anyone that nostr is not just microblogging feeds, there are a lot of use-cases that do not need subscriptions. So on the flip side of your resources argument, a lot of clients may be clinging to subscriptions and utilizing server resources when it's not necessary. Having both HTTP and sockets allow developers to use the best tool for the job at hand.

(And the REQs on HTTP could be made better by using more expressive URLs, but I don't want to beat a dead horse)

Lastly, on this day where americans celebrate the thanksgiving, I'll take the opportunity to thank you again for this amazing protocol and your continued great work on it.

**Comment by fiatjaf** [comment]
I agree with most of your points (except the one about connecting to multiple relays being bad or that somehow WebSockets are slower than HTTP). I agree WebSockets are more challenging currently but I believe this is changing, even without Nostr, WebSockets are becoming more and more common, and also what is life without some challenges? (a little tongue-in-cheek, but also true).

Anyway, I think trying to add HTTP now would be horribly disruptive and even if successful we would be left in a world that I think would be just worse. I mean: all of the problems with WebSockets you mention (and I don't deny) _can be fixed_, but having two ways of doing things can't be fixed. And the transition to the two-ways world would be so much harder than every developer fixing their WebSockets usage today.

Or maybe not. I don't know. I am too sleepy now to think. In any case, I have nothing more to add, so I will also thank you for understanding my stubbornness and for building Nostr with us.

**Comment by alexgleason** [comment]
I think most of the desire for HTTP is actually a misdirection of a feeling that Nostr is already extremely hard and it's bullshit this WebSocket thing adds another layer of difficulty. So I agree with fiatjaf that adding HTTP would paradoxically make things even _harder_ in the long run because it does not actually fix any of the underlying challenges.

Nearly all of the issues with misbehaving relays, slow relays, attacks on clients by relays, etc are all ALSO problems with HTTP if you think it through. In fact, (and I think this is important to remember), WebSockets _are HTTP_! There is no theoretical limit to using WebSockets.

I have things working really great in Nostrify. It feels almost like using `fetch`: https://nostrify.dev/relay/

**Comment by mikedilger** [comment]
Nobody can stop you @rikmeijer from building a REST front end that talks to relays on the back end.  Relays do not need to know it exists, and the nostr NIPs do not need to document it.  But if many of you all want to do this like @melvincarvalho and friends, then you should write an XNIP standard to share amongst yourselves (I use XNIP to mean some external nip, like blossom BUDs, etc).

But IMHO the belief that REST is better is based on misunderstandings and unfamiliarity, and I haven't heard an argument that seemed to carry any weight with me at least.  Websockets only adds a small amount of overhead, uses less traffic (compared to polling), and provides immediate notification response.   HTTP headers like Etag and If-Then-Match provide a small amount of download-avoidance but this is FAR less than negentropy will provide and could easily be done inside of nostr if we chose to (it is such a silly and simple system).  And HTTP clients cannot be alerted by the relay immediately when a new matching event lands on the relay.  Instead the HTTP clients will have to poll, and poll again, and poll an poll over and over again.  There are hacks to avoid this but they create new problems. You might think HTTP polling is no worse than websocket ping/pong, but ping/pong can be infrequent, where as infrequent HTTP polling just means your user will get the message promptly.

I think a move towards WebTransport would be better move than a going back to bare HTTP REST.  That truly reduces round trips substantially. But most implementations are still flaky.

**Comment by rikmeijer** [comment]
> @rikmeijer I think Nostr can still be integrated with shared hosting. It just can't be a relay. But it can be a client. That's still powerful. Most relays are public, so you don't even need to host one yourself. Therefore I think it should still be possible to integrate Nostr with WordPress, etc.
> 
> ChatGPT generated this for `websocket-php`:
> 
> ```php
> <?php
> require 'vendor/autoload.php';
> 
> use WebSocket\Client;
> 
> try {
>     // Connect to the WebSocket server
>     $client = new Client("wss://example.com/websocket");
> 
>     // Send a message
>     $client->send("Hello WebSocket Server!");
> 
>     // Receive a response
>     $response = $client->receive();
> 
>     // Return the response to the downstream HTTP client
>     echo "Response: " . $response;
> 
>     // Close the WebSocket connection
>     $client->close();
> } catch (Exception $e) {
>     echo "Error: " . $e->getMessage();
> }
> ?>
> ```
> 
> @sebastix is building PHP libraries in Nostr and could probably say more.

Thanks for your reply, I am already connected to him and actually working together on bringing nostr to php (https://github.com/nostriphant is where I am hacking and there are enough challenges there 🤣). 

I let this issue rest as I understand the "duplicating is unnecessarily complicated" argument. I did not have the time to pursue it anyway atm. Through bringing nostr php I am learning nostr. The next thing I would like to make is an openid/oauh service using nostr. I believe nostr has great augmenting capabilties currently for the web, before it assimilates it all together.

**Comment by Sebastix** [comment]
My guess is that many (web)developers (just like me) need to understand how the lifecycle inside a WebSocket connection looks like with NIP-01. This is the case for Nostr clients and relays developers. I can't judge how competent everybody is on this knowlegde, but if I speak for myself I'm still learning a lot. And while learning, it still makes sense to use (only) WebSockets. 
This is something I worked out a while ago and hangs on the wall at my office: 
https://shares.sebastix.dev/4PjvH5bd.jpeg
https://shares.sebastix.dev/cEjyJUre.jpeg

My best learning resources are something I'm adding here https://nostr-php.dev/introduction#learn-more-about-websockets. Last week I also found https://www.researchgate.net/publication/348993267_An_Analysis_of_the_Performance_of_Websockets_in_Various_Programming_Languages_and_Libraries.
Previous week I met Michel de Jong who is working on Solid and is the author of UnHosted. He researched WebSockets already more than 10 years ago for something similar like Nostr: https://unhosted.org/adventures/4/WebSockets.html 

If anyone has more additional resources, please share! :)

**Comment by christroutner** [comment]
I spent about 6 hours vibe coding this REST2NOSTR proposal into existence today. This REST API handles the common use-cases I need for my web app. Code examples for each are in the `examples/` directory.

This is a REST API server written in node.js JavaScript using the express.js library. It's got API Docs, unit and integration tests. Between the README and the examples directory, it's pretty comprehensive on how to use it.

Things looks really good from an initial standpoint. I'm going to integrate it into my own infrastructure. I think this is going to solve a lot of the UX problems I'm seeing on slpdex.com.

Anyone is free to use and contribute to the code base.

https://github.com/christroutner/REST2NOSTR
