### ISSUE TITLE
Prepend @ to root NIP-05 identifiers

### ISSUE THREAD

**Issue by lukechilds** [nostr-protocol/nips#156]
From NIP-05 ([01a3090](https://github.com/nostr-protocol/nips/blob/01a3090c6ab872621e01019c58f8cac38c354c25/05.md)):

> ### Showing just the domain as an identifier
>Clients may treat the identifier _@domain as the "root" identifier, and choose to display it as just the <domain>. For example, if Bob owns bob.com, he may not want an identifier like bob@bob.com as that is redundant. Instead, Bob can use the identifier _@bob.com and expect Nostr clients to show and treat that as just bob.com for all purposes.

Maybe it's too late to change this now, although it doesn't seem like it would break anything too badly if it were to be changed. But I think it would make more sense to refer to root domains as `@domain` instead of `domain`. Referring to the domain alone is ambigious. If a client is trying to inject pubkey mentions in the place of NIP-05 identifiers it's impossible to know if `<domain>` is a NIP-05 identifier or a URL. There isn't enough context. Even if the root domain is a valid NIP-05, maybe in this context it's meant as a link. Even for humans, it may be difficult in many scenarios to know if it's intended to be interpreted as a mention or a link.

As an example if I have the NIP-05 `_@lu.ke` which translates to just `lu.ke` and someone broadcasts this note:

```
Yo check this out lu.ke
```

Is this note saying "Yo check this out" to everyone and then linking to my website `https://lu.ke`.
Or are they saying "Yo check this out" to me via a mention to my NIP-05 identier `lu.ke`.

It's ambiguous and it could be either in different scenarios, there isn't enough context for humans or clients to figure it out.

Alternatively:

```
Yo check this out @lu.ke
```

Is very clear that it's a mention and not a url.

Even combining both is very clear:

```
Yo @lu.ke your domain lu.ke is really badass
```

**Comment by fiatjaf** [comment]
Looks good. This is a pure "display" or "input" thing, so should be ok for clients to try new approaches.

In the case of mentions the client should detect the attempt to mention, then match "lu.ke" against your list of followed people or people relevant to the thread and then replace the mention with a `#[0]` thing then inject the pubkey as a tag.

**Comment by lukechilds** [comment]
To clarify would you like me to open a PR to NIP-05 to clarify that root domains should be shown with the @ prefix? Currently the spec states that they should not.

**Comment by fiatjaf** [comment]
Can we say on the NIP that they can be shown as `domain OR @domain`?

**Comment by lukechilds** [comment]
Sure I'm happy to go with whatever you think makes sense. I'm interested though, what do you think is the benefit of allowing both? The reason I raised the issue is because I think allowing `<domain>` at all is a mistake because it's ambiguous.

e.g if I see text rendered like:

>Yo [@lu.ke]() your domain [lu.ke]() is really badass


it's clear clicking the one prefixed with an `@` takes me to a profile and the other takes me to a website.

If i see:

>Yo [lu.ke]() your domain [lu.ke]() is really badass

even if the client is able to figure out what poster means via the tags, it's not clear to me as a user that clicking those two identical looking links does two different things.

I think changing the spec to say that root NIP-05 IDs can be shown as `@<domain>` instead of `<domain>` will avoid this ambiguity.

**Comment by eskema** [comment]
not sure this makes sense to explicitly state, it is up to the client to render the mention as it sees fit. alphaama has been displaying mentions with an @ before it, no need to nip that IMO. the client needs to pick up #[<int>] and replace it with something, it does not make sense to require that it display an @ if the client prefers another symbol.. even if it also makes sense to me, it may not for someone else and that's ok.

**Comment by fiatjaf** [comment]
Basically I just don't want the current clients that are not using `@` suddently become incompatible with the NIP.

> Yo lu.ke your domain lu.ke is really badass

In this case it's the client's job to format both differently using colors, fonts, backgrounds, spacing, whatever, to differentiate these two.

**Comment by lukechilds** [comment]
Fair enough, I agree it's probably better to allow for more client freedom and see what people gravitate towards, I'll close this issue.
