### ISSUE TITLE
NIP-73: k-Tag examples

### ISSUE THREAD

**Issue by IngwiePhoenix** [nostr-protocol/nips#1573]
Hello!

Haven't taken a look at the recent development in the Nostr spec, so I went to read the recent ones.
While reading NIP-73, I noticed that `i`-tags had examples documented right underneath the table, and `k`-tags did not. Are those even needed, then? If not even their origin spec has them, they appear rather superfluous... o.o

Kind regards,
Ingwie

**Comment by AsaiToshiya** [comment]
`k` tag is a prefix of `i` tag and it is mainly used in [NIP-22](https://github.com/nostr-protocol/nips/blob/master/22.md) for filtering events.
