### ISSUE TITLE
Migrating from NIP-04 to NIP-44 encryption

### ISSUE THREAD

**Issue by arthurfranca** [nostr-protocol/nips#1598]
We should take the opportunity to do `nip44.encrypt('{ "k-i-n-d": event.kind, data: "<plaintext>" }')` (the arg is a stringifed JSON) instead of  `nip44.encrypt("<plaintext>")` when encrypting things inside events.

This way nip07/46 can decrypt and inform it is decrypting something related to a specific event kind so the user can make an informed decision to allow or deny it.

Ack or nack?

note: used "k-i-n-d" key instead of "kind" to avoid collision with a plaintext that happens to be a stringified json with "kind" and "data" keys.

**Comment by vitorpamplona** [comment]
I don't know if it makes sense to keep kind as the reference point. Many encryptions are not based on a specific kind. And some kinds have more than one encryption in such a way that it would be important to differentiate. For instance, health data has 2 encryptions, one that stores a key to view the health data and another one to edit that data. It would be important for a signer to highlight when the permission is not only to see but to edit.

**Comment by vitorpamplona** [comment]
But why stay there? Why not allow the writer an alt that describes what's in the payload? The signer just displays the alt.

**Comment by vitorpamplona** [comment]
The client just adds the alt in the same way we add the alt tag to each event without asking the user about it.

**Comment by vitorpamplona** [comment]
Another way of doing this would be to specify a few codes for different payloads in each nip and then use those codes instead of kinds. In that way the signer doesn't need dynamic  translations of alt content.

**Comment by vitorpamplona** [comment]
Something on those lines. I am not exactly sure if it is the best way. What I know is that kinds alone might not be enough info for signers, depending on the application.

Maybe a "<kind>:<int>" and then we have a table somewhere to describe what each code means? In that way it is scoped to the kind to avoid reusing codes.

**Comment by fiatjaf** [comment]
Not a bad idea but I don't think it's worth the trouble.

Specially because I think our best possible future involve not dealing with nip44 encryption with user keys directly anymore, but only as a way to talk to bunkers, and bunkers would just sign events, while all encryption needs will be provided by per-device keys using MLS or something else.

**Comment by fiatjaf** [comment]
> Like I have to kinda "join" a group with myself (my other device) so that I can decrypt something the other device encrypted?

Yes, exactly.

> I'm skeptical about MLS saving the world.

Me too, and I hate all this crappy IETF I-am-cryptographer-and-I-love-Signal technology vibes but I don't see any other way because I want FROST bunkers and they can't encrypt. Also per-device encryption keys sounds like a sensible idea even if we don't use full-blown MLS.

**Comment by vitorpamplona** [comment]
Even on #1228, the code should describe what kind of event this is first and then what type of information it is trying to assess. Knowing that the app is asking for an `edit key` is irrelevant if I don't know what that key is for: health data, spreadsheets, docs, etc. In fact, It could be said that even kind + code is not enough. As a user, I want to know which file I am giving access to. The signer should say something like: "Amethyst is asking to decrypt edit keys of the spreadsheet 'My Clients'".

So, "<App Requester> is asking to <signer method> <code inside the encrypted file> of the <event kind> <user-facing identification of that kind>".
