### ISSUE TITLE
We need tools to discover bootstrap relays

### ISSUE THREAD

**Issue by arthurfranca** [nostr-protocol/nips#1607]
I'm calling bootstrap relays those that help distribute kind:10002 events.
wss://purplepag.es and wss://user.kindpag.es are the ones I know. Problem is how can clients easily discover new ones?

I think we could add `bootstrap_relays` as a top-level nip05 nostr.json key. This way the bootstrap relays the app already knows can recommend other bootstrap relays (e.g.  at https://purplepag.es/.well-known/nostr.json).

Signers are also in a good position to recommend bootstrap relays to apps. We should add `window.nostr.getBootstrapRelays()` to nip07 and the equivalent `get_bootstrap_relays` for nip46.

**Comment by vitorpamplona** [comment]
Bootstrap is a bad name. Metadata relays are not used to bootstrap anything. They are just the last resort when a pubkey is not found on any of the user's existing relays and when no p-tag with that pubkey has had any relay hint in all events in the database. 
 
We should make a kind 10050-like list for the user's preferred Metadata relays. This should not be the client's choice. The client can have default ones for new users, but people should largely choose their own. 

If the list is available, then NIP-05 jsons only need to have the current relay list, which should be the Outbox relays from NIP-65. 

Making a separate list for those relays alone also allow clients to keep that list up-to-date with the user's kind 10002 but also every other user's kind 10002 that is outdated from those relays.

**Comment by mikedilger** [comment]
Any relay that supports NIP-65 is a bootstrap relay.  A large fraction of relays are.

**Comment by fiatjaf** [comment]
Hardcoding by the app developer is probably enough.
