### ISSUE TITLE
NIP-01 filters with no attributes

### ISSUE THREAD

**Issue by wilsonsilva** [nostr-protocol/nips#161]
I'm implementing Nostr in Ruby. I have a question. Apologies if this is not the right place for it.

NIP-01 declares which attributes a filter _can_ have:

> `<filters>` is a JSON object that determines what events will be sent in that subscription, it can have the following attributes:
>
> ```json
> {
>   "ids": <a list of event ids or prefixes>,
>   "authors": <a list of pubkeys or prefixes, the pubkey of an event must be one of these>,
>   "kinds": <a list of a kind numbers>,
>   "#e": <a list of event ids that are referenced in an "e" tag>,
>   "#p": <a list of pubkeys that are referenced in a "p" tag>,
>   "since": <a timestamp, events must be newer than this to pass>,
>   "until": <a timestamp, events must be older than this to pass>,
>   "limit": <maximum number of events to be returned in the initial query>
> }
> ```

It does not mention which and how many attributes it _should_ have. Is it safe to assume that a JSON object with no attributes, `{}`, is a valid filter?

**Comment by ryzizub** [comment]
As far as I know, `{}` is a valid filter (I just tried it on my relay running nostream). It always depends on a relay what it will do with the filter. A relay should always filter based on the filter, and I would assume it will use its limit when the filter is empty.

**Comment by fiatjaf** [comment]
Some relays interpret an empty filter as "send me everything you have" but you can also just ignore it if you want.

**Comment by Giszmo** [comment]
Relays can ignore everything ever. The literal meaning of `{}` is "send everything ever with no restrictions at all" and that's what all relays did half a year ago. As now that would yield more than the 60MB from back then, relays introduced default limits and some just reply "go home, you're drunk" when the client requests a DB dump but I hope with paid-for relays we will get DB dumps again.

**Comment by Giszmo** [comment]
Also I think OP got the info he wanted. Closing.
