### ISSUE TITLE
NIP 47 using deprecated NIP 04 for encryption

### ISSUE THREAD

**Issue by Gudnessuche** [nostr-protocol/nips#1639]
Is it prudent to move to NIP 17 or NIP 44 for encryption, giving that NIP 04 leaks meta data?

**Comment by vitorpamplona** [comment]
Already happening: https://github.com/nostr-protocol/nips/pull/1531

**Comment by Gudnessuche** [comment]
@vitorpamplona why has this not been merged?

**Comment by vitorpamplona** [comment]
As always, we need 2+ implementations to catch up to it before the merge.

**Comment by Gudnessuche** [comment]
Alby says they implement this, doesn't Amethyst use nip 44 as well?
Boardwalkcash also uses itI suppose.
Nostrudel?

**Comment by vitorpamplona** [comment]
Not as they wrote. We dynamically pick if it is NIP-04 or NIP-44 by the contents and not by the `v` tag.

**Comment by Gudnessuche** [comment]
Given this is a security risk, wouldn't you rather we prioritized security?
Your PR looks fantastic to go imo.

**Comment by vitorpamplona** [comment]
I wouldn't call it a security risk... 

But regardless of what it is, the NIP repo is a reflection of reality as opposed to an imposer of reality. We need lots of people to adopt specifications/changes before things get merged.
