### ISSUE TITLE
Clarity re: "a" tag- coordinates or addressable event?

### ISSUE THREAD

**Issue by avlo** [nostr-protocol/nips#1641]
Hoping to get some clarity regarding intent and usage of **_"a" tag_** throught the documentation.

In [README, under "Standardized Tags" section](https://github.com/nostr-protocol/nips/blob/master/README.md#standardized-tags), **_"a" tag_** is defined as:

> a coordinates to an event

However, in multiple places [throughout remaining documentation](https://github.com/search?q=repo%3Anostr-protocol%2Fnips%20addressable&type=code), the **_"a" tag_** is utilized as:

> an addressable event (_also/formerly known as "parameterized/replaceable event"_)

having either form:

> for an addressable event: ["a", <kind integer>:<32-bytes lowercase hex of a pubkey>:<d tag value\>, <recommended relay URL, optional>]  
> for a normal replaceable event: ["a", <kind integer>:<32-bytes lowercase hex of a pubkey>:, <recommended relay URL, optional>]

which (seems to me) conflict with the [README, "Standardized Tags" defintion](https://github.com/nostr-protocol/nips/blob/master/README.md#standardized-tags), particularly given existense of both:  

**_"location"_** tag:    
> location (optional, repeated) location of the calendar event. e.g. address, GPS coordinates, meeting room name, link to video call

and **_"g"_** (_geohash_) tag:  
> g: (optional) geohash to associate calendar event with a searchable physical location

both fulfilling the _"coordinates to an event"_ function. 

Assuming I haven't a complete misunderstanding, hoping to get other people's **_"a" tag_** interpretation...  and pending consensus, I can/will submit a documentation PR update with comprehensively correct changes. 

----
Appendix:
Some **_"a" tag_** documentation examples as follows:

[NIP-01 "Tags" section:](https://github.com/nostr-protocol/nips/blob/master/01.md#tags)  
>  The a tag, used to refer to an addressable or replaceable event  
>  for an addressable event: ["a", <kind integer>:<32-bytes lowercase hex of a pubkey>:<d tag value\>, <recommended relay URL, optional>]  
>  for a normal replaceable event: ["a", <kind integer>:<32-bytes lowercase hex of a pubkey>:, <recommended relay URL, optional>]

----

[NIP-52, "Time-Based Calendar Event" section](https://github.com/nostr-protocol/nips/blob/master/52.md#time-based-calendar-event):
> Format  
> The format uses an addressable event kind 31923  

[NIP-52, "Date-Based Calendar Event" section](https://github.com/nostr-protocol/nips/blob/master/52.md#date-based-calendar-event)
> Format  
> The format uses an addressable event of kind:31922

[NIP-52, "Calendar" section](https://github.com/nostr-protocol/nips/blob/master/52.md#format-2)	
> Format  
> a (repeated) reference tag to kind 31922 or 31923 calendar event being responded to  
> ["a", "<31922 or 31923>:<calendar event author pubkey>:<d-identifier of calendar event>", "<optional relay url>"],  
> ["a", "<31922 or 31923>:<calendar event author pubkey>:<d-identifier of calendar event>", "<optional relay url>"]

[NIP-52, "Calendar Event RSVP" section](https://github.com/nostr-protocol/nips/blob/master/52.md#format-3)
> Format  
> The format uses an addressable event kind 31925  
> ["a", "<31922 or 31923>:<calendar event author pubkey>:<d-identifier of calendar event>", "<optional recommended relay URL>"],

**Comment by staab** [comment]
It sounds like you're being confused by the word "coordinates". All that means in this context is that an a-tag "points" to an event. g tags are a completely different thing. Does that help?

**Comment by avlo** [comment]
aha, so "coordinates" in an "a" tag context represents the addressable tag format:

> <kind integer\>:<32-bytes lowercase hex of a pubkey\>:<d tag value\>

i do in fact see the same mentioned in [NIP-25 Tags](https://github.com/nostr-protocol/nips/blob/master/25.md#tags)

> The a tag MUST contain the coordinates (kind:pubkey:d-tag) of the replaceable being reacted to.

much thx 👍
