### ISSUE TITLE
NIP-03 is not very efficient for timestamping a large number of events

### ISSUE THREAD

**Issue by nanikamado** [nostr-protocol/nips#1657]
I want to add timestamps to all events newly published to my relay by OTS, but creating one kind:1040 event for every single event is not spatially efficient, so what I'm doing is first creating events that reference 300 other events and then timestamping those instead of timestamping the 300 events individually.

I am using kind:1039 for the events that bundle 300 events, and I am running a bot `npub1c6m9rjhl4s069dkevk8ptgyqvwvytm4hf5sv4cfrwgx0zqldhuyqzgh0k9` on wss://relay.momostr.pink.

Example:
```js
{
  "kind": 1040,
  "tags": [
    [ "e", "fe6421f8603f0a1d965b5cf5ac082a68c44da475a7b59bab8e47ebb1be3371b8"]
  ],
  "content": <OTS data>
}
```
```js
{
  "kind": 1039,
  "id": "fe6421f8603f0a1d965b5cf5ac082a68c44da475a7b59bab8e47ebb1be3371b8",
  "tags": [
    ["e", <event-id>],
    ["e", <event-id>],
    ["e", <event-id>],
    ["e", <event-id>],
    ["e", <event-id>],
    ["e", <event-id>],
    ...
  ]
}
```

Can this method be appended to NIP-03 if I make a PR? Or should it be a different NIP? Or does anyone have any other ideas?

**Comment by vitorpamplona** [comment]
More efficient for who? Yes, tagging 300 events in a single OTS event saves some space at the relay, but now every post in every client needs to download 20KB of data. That if you didn't add 300 relay hints with the e tags. 

I would much rather keep one event per OTS event to avoid consuming so much of the data plan.
