### ISSUE TITLE
NIP-18 may need some improvement

### ISSUE THREAD

**Issue by RooSoft** [nostr-protocol/nips#173]
According to note1wlpjwra6xgeqzvf88l0rk6zkfhgz6en3vm2jmgzsp8nfw06qpaast77ut6, Damus is not implementing NIP-18 as is and doesn't intend do to so.

<img width="511" alt="Screenshot 2023-01-16 at 1 48 32 PM" src="https://user-images.githubusercontent.com/665949/212747986-6ea417bf-05d7-4f75-88fe-2ddf4ff04b44.png">

Its boost feature includes most of the reposted note's data in the contents field and this is apparently needed for many reasons.

Seems like snort is going in the same direction.

As a developer trying to follow the specs in these early days of the network, I already need to differ from what's documented if I want to remain compatible with the most prevalent clients.

**Comment by fiatjaf** [comment]
You're right, I'm going to remove this NIP from here.

But if you're going to implement it like Damus is doing that will be very sad, since it is a hack that is probably not healthy for the network in the long term. I believe that's why William didn't propose it as a NIP himself. We'll see.

**Comment by RooSoft** [comment]
Will do whatever is best for network concensus, you guys tell me what to do...

🫡

**Comment by RooSoft** [comment]
Why is this issue closed? Has it been resolved already?

**Comment by fiatjaf** [comment]
Yes, I've deleted NIP-18.

**Comment by Giszmo** [comment]
Why? Why so impulsive? Where are the arguments? One second to the other we scrapped it just like that? Or is this your way of pushing us to something more decentralized than github?

**Comment by fiatjaf** [comment]
Give me arguments for keeping a NIP that no one implements which I wrote and committed myself trying to describe what Damus was doing only to learn that Damus wasn't doing that.

Meanwhile Astral and probably Hamstr are doing the same thing in what seems to be a cleaner way, which is described in NIP-10.

**Comment by Giszmo** [comment]
It's a very dynamic space right now, with new clients popping up every day. It's ok to nuke stuff but I would appreciate to get a chance to comment before nips are removed.

I agree with your decision to remove this nip but when nips disappear without a chance to ask for a timeout it feels like shaky grounds to implement less popular nips on. It just looks better to have two or three ACK between PR and merge.

On the subject of this nip:

* kind-6 with empty body adds little to kind-1 mentioning events via e-tags. It saves a few bytes over kind-6 with serialized event in content.
* kind-6 with serialized event in content looks goofy at first but as the client can verify the embedded event and store it as first-class event, it's actually quite powerful.

I only wonder how it came to be that both approaches use kind-6.

**Comment by alexgleason** [comment]
Just wanted to document here:

I tried following NIP-10 to do reposts and quote posts, and the ONLY client who understood it was Astral:

```json
{
  "kind": 1,
  "content": "",
  "tags": ["e", "123", "mention"]
}
```

In my mind this is enough. A quote post has a mentioned event. A repost is a quote post without content. However most clients do not understand this, leading to a bad UX.

So finally I figured out this way:

**Repost:**

```json
{
  "kind": 1,
  "content": "#[0]",
  "tags": ["e", "123", "mention"]
}
```

**Quote post:**

```json
{
  "kind": 1,
  "content": "hello world\n\n#[0]",
  "tags": ["e", "123", "mention"]
}
```

Now it works correctly in Iris. Pretty strange. Also NIP-10 and NIP-08 don't mention the fact you can use a tag like `#[0]` to mention an **event** at all, so it should probably be clarified.

**Comment by fiatjaf** [comment]
It is mentioned here: https://github.com/nostr-protocol/nips/blob/b549a9809f94ca703b3b63b73cdacc5407a2edd0/08.md#L15, but could be improved. Please send a PR if you have an idea of how.

**Comment by fiatjaf** [comment]
```json
{
  "kind": 1,
  "content": "",
  "tags": ["e", "123", "mention"]
}
```

Is this method specified anywhere? We should probably remove it from the NIPs. I think it is not a good method. The `#[0]` thing makes more sense even though it is ugly. It's better to have a single way of doing things.

**Comment by alexgleason** [comment]
I'm tempted to make a new nip called "Quote posts and reposts" even though there's two nips already, because I'm not sure the existing nips actually use those words.

**Comment by monlovesmango** [comment]
for the record astral does put the `#[X]` in the content when creating reposts, but will also parse reposts with `""` in the content. would it be preferable that astral stop parsing reposts with `""` in the content?

I don't think that format is specified anywhere, just something I thought would be good to handle.

**Comment by alexgleason** [comment]
:point_up: I pretty much agree at this point. Reposts should be first class citizens in the Nostrsphere. A bunch of clients still use kind 6, so you'll have to implement them anyway. Also kind 1 reposts in clients often have buggy behavior, eg: https://github.com/irislib/iris-messenger/issues/336
