### ISSUE TITLE
An alternative to mining keys

### ISSUE THREAD

**Issue by mikedilger** [nostr-protocol/nips#177]
I would start a NIP (edit: actually it's out of protocol so I wont), but I thought I would start a discussion first.

Scheme goes like this:

- A relay could require keys to be whitelisted in order to write events.
- Anybody who sends in an event with POW beyond a certain threshold is automatically whitelisted, unless or until blacklisted due to abuse. 

In this manner, the keys themselves can remain cryptographically strong without any dubious shrinking of the keyspace, and yet spammers would still have to hit a POW target before they could try again.

This also combines well with other key schemes such as the key rotation scheme proposed elsewhere.

I'm sorry it is so simple, maybe I should add an esoteric cryptographic algorithm to make it flashy.

**Comment by mikedilger** [comment]
Phil Rogaway (actual cryptographer) says:

> A public-key starting with a bunch of zero bits is likely to have some special characteristics that are algebraically significant with respect to what you are doing with it. Said differently, it would be at all surprising if such keys were effectively "weaker" than uniformly random public-keys.  A safer heuristic would be to declare that the public key is "good" (it is properly mined according to your mining algorithm) if its hash begins with a particular length prefix of zeros. You would select a hash function that is ostensibly unrelated to anything that is going on in the trapdoor function, as well as any other protocols to which the PK might be subjected.  It would then far less plausible that you are weakening the generated (PK, SK) pairs by your selection criteria.

So that would remove the key-weakening concern of mined public keys.  But it wouldn't open up the possibility of having a key rotation scheme too.  So I'm still in favor of what I suggest in my post above.

**Comment by fiatjaf** [comment]
Interesting approach. @Cameri will maybe be interested in this.

We can probably just use https://github.com/nostr-protocol/nips/blob/master/13.md and relays could set a giantly high threshold for the first event so keys can be whitelisted, such that they will take an hour or more to mine, then they can go back to not doing any proof-of-work.

But I wonder if this is preferable to a relay just having a signup page where you can paste your pubkey to get whitelisted, and there you must fulfill some requirements such as

- pay an entrance fee
- provide giant proof-of-work (that could be mined for you in your browser as you click a button)
- pass a captcha
- etc

**Comment by Cameri** [comment]
> Interesting approach. @Cameri will maybe be interested in this.
> 
> 
> 
> We can probably just use https://github.com/nostr-protocol/nips/blob/master/13.md and relays could set a giantly high threshold for the first event so keys can be whitelisted, such that they will take an hour or more to mine, then they can go back to not doing any proof-of-work.
> 
> 
> 
> But I wonder if this is preferable to a relay just having a signup page where you can paste your pubkey to get whitelisted, and there you must fulfill some requirements such as
> 
> 
> 
> - pay an entrance fee
> 
> - provide giant proof-of-work (that could be mined for you in your browser as you click a button)
> 
> - pass a captcha
> 
> - etc

I'll be implementing a combination of these measures. There's no one size fits all here and hopefully it's as simple as changing a value on a settings file and you are done.

**Comment by mikedilger** [comment]
I'm closing this issue since it's not really appropriate on this repo, and the people I wanted to see and consider it have (except maybe @scsibug who is now tagged).
