### ISSUE TITLE
Limit fields in filter array

### ISSUE THREAD

**Issue by barkyq** [nostr-protocol/nips#180]
Suppose I send a "REQ" with two (or more) filters with the limit field specified:

`["REQ", [{filter1, limit: N1}, {filter2, limit: N2}]]`

What is the expected behavior? A example SQL query might be something like:

`SELECT * FROM database WHERE filter1 OR filter2 ORDER BY created_at DESC LIMIT N;`

What should `N` be? Or maybe there is a more sophisticated SQL query?

Perhaps something can be said like: "the largest/smallest/first/last limit field appearing in the list of filters will be used when returning events."

**Comment by Giszmo** [comment]
Relays indeed are not consistent with this. Implementing my own relay, I did:

SELECT * FROM database WHERE filter1ORDER BY created_at DESC LIMIT N1;

SELECT * FROM database WHERE filter2 ORDER BY created_at DESC LIMIT N2;

deduplicate.

So the result was between max(N1,N2) and N1 + N2. Others do it differently.

Trying with https://nostr.info/relayr/ I see that nostream works differently based on the default query - buggy as I would say.

**Comment by barkyq** [comment]
Yeah the deduplication way seems like the most faithful interpretation of the query, but requires more SQL calls and maybe a bit more work for the relay?

**Comment by fiatjaf** [comment]
`(... LIMIT 1) UNION (... LIMIT 2)` probably.

But I'd rather leave this open for interpretation because they can't be enforced or relied upon anyway.

**Comment by barkyq** [comment]
OK nice did not know about UNION SQL command.
