### ISSUE TITLE
NIP05 SSL requirement

### ISSUE THREAD

**Issue by opposablebrain** [nostr-protocol/nips#192]
Currently, it appears that NIP05 always defaults to 'https' for fetching nostr.json.
This is good, but is it strictly necessary?
Adding http as a fallback would allow many distributed IPFS (dnslink) sites to work (since SSL is a bit tricky to add while remaining distributed).
What do we think about that?

An alternative would be to fetch the payload directly from a DNS TXT record, circumventing the issue altogether.

(edited for clarity)

**Comment by fiatjaf** [comment]
It is necessary such that we only have one method of fetching the data. If more than one method is used that doubles the work required by implementors and computers doing this kind of verification. The same argument is true for usage of TXT, which was already discussed at length in another issue.

**Comment by opposablebrain** [comment]
Makes sense. Thanks.
