### ISSUE TITLE
NIP-01 type 2 events should be an array or list of recommended servers (not just one)

### ISSUE THREAD

**Issue by jeremyd** [nostr-protocol/nips#193]
NIP-01 currently states that event type 2 is:

2: recommend_server: the content is set to the URL (e.g., wss://somerelay.com) of a relay the event creator wants to recommend to its followers.

After much sleuthing around in the other places where relay information exists, I think this would be far more powerful and widely used if it was an array.  Right now it doesn't seem to get much use..  Thoughts?

**Comment by jeremyd** [comment]
I suppose the alternate is to leave the spec as-is, and clients will have to broadcast multiple type 2 events to their relays for a relay list to be gathered by other clients..  Given that most people are on more than one relay (by design), I still think an array makes more sense.  It also allows people to 'revoke' a relay from their recommended list, much like unfollowing.

**Comment by Giszmo** [comment]
These recommended relays make little sense as the relays used by everybody are already public knowledge. Some clients support kind-2 but I see no need to improve it given the other places relays are already being advertised.

**Comment by jeremyd** [comment]
Relays are only advertised in replies, follow lists, or in type 2 events.  Type 2 events are the only proactive advertisement of a relay, the rest of the types are 'suggestions' from replies to the root event and not from root event itself.

When I first started to use nostr, my clients did not dynamically follow relays.  All I saw were people that I follow replying to messages that didn't exist.  With new client implementations, clients pull these root messages dynamically from the reply relay tag but I still have the situation I may follow someone that is not posting to any of my relays and never see them again, nor will I know that any messages I send to them or tag them with will not be delivered.

The proactive approach that I as a new user tried to do then was to "find out what relays the person is on".  I could see their metadata, I could follow them, but I still had no idea how to be able to send a message that they would see.  Nor could I see a reply from them, since their client is using a set of relays to publish (and another set to read).  The only way I could find their relays I assumed would be a type 2 event, but there were no type 2 events on any of the relays I am using so I assume nobody is using type2.  Therefor, it was a mystery to me, what relays someone really is using.  This seems like a flaw.  Is it a flaw in the clients?  Is gossip the answer vs. a proactive use of type 2?

Regardless, I'll close this issue, I can see that clients if they wished, could make better use of type2 in it's current form and adding to an un-used spec does not seem useful at this time.

**Comment by mikedilger** [comment]
If you want to follow someone and don't know their relays, you won't be able to find their type2 events either... unless they proactively spread them to many more relays than they normally post to.

Nonetheless, type2 is kinda dead.  Type 3 contents are currently being used by Damus, Astral and a few others, even though there is no NIP for it.  Type 10001 is planned and some clients are starting to use it (https://github.com/nostr-protocol/nips/pull/32).

Gossip does not yet look at type2, type3, or type10001 which is one of the reasons I haven't "released" it yet... but surprisingly even to me it still seems to work without them.

**Comment by jeremyd** [comment]
> If you want to follow someone and don't know their relays, you won't be able to find their type2 events either... unless they proactively spread them to many more relays than they normally post to.
> 
> Nonetheless, type2 is kinda dead. Type 3 contents are currently being used by Damus, Astral and a few others, even though there is no NIP for it. Type 10001 is planned and some clients are starting to use it (#32).
> 
> Gossip does not yet look at type2, type3, or type10001 which is one of the reasons I haven't "released" it yet... but surprisingly even to me it still seems to work without them.

I did some further investigation and realized I wasn't actually subscribed to type2, lol!  Now that I am, I do see some.  I think that type 2 could become just as important as metadata in the future if people are trying to signal to their followers the relays that they post on.  This would require a broadcast one or more times to a larger set of relays than you publish on normally as you mentioned.  I also noticed the follow lists that people have, relays are not very accurate.  For example, when I spot check my follower's follow list, they have some relay I've never used as a tag for my follow entry..
