### ISSUE TITLE
Brainstorming: Standard for structured data objects as part of event content

### ISSUE THREAD

**Issue by ingo7** [nostr-protocol/nips#204]
_Hi, thanks a lot for creating such a simple and open protocol and for everyone creating so amazing clients, relays, tools, fun stuff on nostr! Love it._

### Summary

This is to start brainstorming on an optional standard for structured data objects as part of the content tag. Includes example "spec" with set-based ontology as structure.

### Motivations, questions, goals, etc

- Usage of kinds especially for structured data as part of event contents (or tags-tag) is quite un-organized (which isn't bad in itself). It might become a problem if nostr will be used by many more apps. It's already widely unclear which apps use which nostre kind with which data structure. Collisions in "un-official" kinds might become more comon, reviewing and adding more kinds by PR on github takes time. Could this be moved to the clients/apps/users without namespace conflicts and data collissions?
- Keep the relays as dumb (and fast) as possible and enable clients to become smarter by giving them meta data. (less db work and complexity for relays)
- Nostr apps create/use separated data islands. A flexible standard for structured contents could interconnect them.
- Enabling development of generic clients, or clients that can be extended to handle different but similar data structures by using openly defined standard object types. Or enabling something like a extendable nostr app plattform. (dreams)
- privacy: kind4-events leak meta-data. Nesting events might help preventing those leaks.
- if users can connect with more other users easier (via more apps) and more private (nesting), and can select desired contents by types and trusted pubkeys, spam will reach less users and will hopefully tend to be reduced over time.
- explore nostr potentials

### Design (no implementation)

Let's assume we have a client that is able to create, store, receive, send, query and display specified json objects. The client sends those json objects as part of the content tag of something like existing kind1 or kind4 nostre events, e.g. with kinds like this (see NIP16):

kind 1001: kind1 events with plain structured content
kind 4004: kind4 events with encrypted structured content
kind 11001: replaceable events with plain structured content
kind 14004: replaceable events with encrypted structured content
kind 21001: ephemeral events with plain structured content
kind 24004: ephemeral events with encrypted structured content

Each json object in the content of the base event gets an unique id and a sig like it's done in nip1. Someone called those nested structures 'onionized events' somewhere. So we have an envelope (the outer event; kind1/4-like) and the nested event with its own id. Those nested (and/or envelopy) events/json objects could be just created, stored and displayed in your client (if you want to keep the contents and structure private like in a personal cms/wiki) or you could additionally relay them to one or more friends/users (nip4-like; 4004/14004/24004) or to the public (as nip1-like event; 1001/11001/21001). The client could request those events from local storage or from relays in order to e.g. display the latest contents/messages/stuff of your friends/other users you want to receive those from.

But how does a nostr client know how to handle/use and display these nested json objects of different apps with different data structures? Some kind of generic base structure seems to be needed or at least helpful. In the following example specification the structure of the contents is based on some generic ontology-like object types like elements, sets, relations, relationsets, attributes and attributesets. (you could do similar with e.g. rdf/owl-like ontologies, but why not simple sets?)

The **basic object types** used in this example spec of structured content events:
- element
- relation
- attribute
 .
- set: set of elements
- relationset (rset): set of relations
- attributeset (aset): set of attributes
 .
- ontology: namespace for other objects (sets, rsets, asets and indirectly to elements, relations and attributes)
- schema: e.g. JSON schema defining the constraints for objects (validation,ui-generation?) TODO
- template: e.g. usable for ui elements,structures or app layouts TODO

Sets, relationsets and attributesets are part of an ontology. Individual elements, relations and attributes can be based on those ontological definitions (like classes and instances in owl/rdf-ontologies). 

Here some example json for those nested object types (here: more basic tags first):

**Element**
```
{
  "id": "hash of the serialized object data",
  "created_at": "<unix timestamp in seconds>",
  "created_by": "<pubKey, version>",
  "sig": "signature of hash",
  "replace": "id of another object of the same type",
  "objectType": "element",
  "set": "id of a set [optional -> unvalidated]",
  "title": "fun with nostr",
  "content": "notes and other stuff transmitted over relays"
}
```

Examples: John Nostroe, my car, an individual plant, a specific shop item, relayXY, .....

**Relation**
```
{
  "id": "hash of the serialized object data",
  "created_at": "<unix timestamp in seconds>",
  "created_by": "<pubKey, version>",
  "sig": "signature of hash",
  "replace": "id of another object of the same type [optional]",
  "objectType": "relation",
  "relationset": "id of an relationset e.g. the 'part of' relationset [optional? -> unvalidated]; might be just a name if not linked to an rset?",
  "source": "id of an object, e.g. an individual blogpost",
  "target": "id of an object, e.g. the set blogposts"
}
```

Examples: John Nostroe loves freedom, my car part of cars, I sell popcorn, has tag, relayXY part of relays

**Attribute**
```
{
  "id": "hash of the serialized object data",
  "created_at": "<unix timestamp in seconds>",
  "created_by": "<pubKey, version>",
  "sig": "signature of hash",
  "replace": "id of another object of the same type [optional]",
  "objectType": "attribute",
  "attributeset": "id of an attributeset [optional? -> unvalidated]; might be just a name if not linked to a aset?",
  "source": "id of an object",
  "value": "value of the attribute (no object id)"
}
```

Examples: John Nostroe has size: 180cm , my car has status: still running, this banana has color: green, popcorn is available:true, relayXY is: online, ...

**Set**
```
{
  "id": "hash of the serialized object data",
  "created_at": "<unix timestamp in seconds>",
  "created_by": "<pubKey, version>",
  "sig": "signature of hash",
  "replace": "id of another object of the same type [optional]",
  "objectType": "set",
  "ontology": "id of an ontology [optional? -> unvalidated]",
  "schema": "id of a schema describing the elements in this set [optional]",
  "template": "id of a template object [optional]",
  "title": "e.g. blogposts",
  "content": "e.g. set of all blog posts"
}
```

Examples: friends, cars, plants, products, sellers, tags, relays, ... 

**Relationset**
```
{
  "id": "hash of the serialized object data",
  "created_at": "<unix timestamp in seconds>",
  "created_by": "<pubKey, version>",
  "sig": "signature of hash",
  "replace": "id of another object of the same type [optional]",
  "objectType": "relationset",
  "ontology": "id of an ontology [optional? -> unvalidated]",
  "schema": "id of a schema describing the relations in this relationset [optional]",
  "template": "id of a template object [optional]",
  "title": "e.g. part of",
  "content": "e.g. the 'part of' relationset is used to mark one object as part of another object."
}
```

Examples: loves, part of, same as, sells, has tag, related to, ...

**Attributeset**
```
{
  "id": "hash of the serialized object data",
  "created_at": "<unix timestamp in seconds>",
  "created_by": "<pubKey, version>",
  "sig": "signature of hash",
  "replace": "id of another object of the same type [optional]",
  "title": "colors",
  "description": "attributeset e.g. colors",
  "objectType": "attributeset",
  "ontology": "id of an ontology [optional? -> unvalidated]",
  "schema": "id of a schema describing the attributes in this attributeset [optional]",
  "template": "id of a template object [optional]",
  "content": "e.g. the colors attribute(set) assigns a color to an object."
}
```

Examples: has size, has status, has color, is available, is, ...

**Ontology**
```
{
  "id": "hash of the serialized object data",
  "created_at": "<unix timestamp in seconds>",
  "created_by": "<pubKey, version>",
  "sig": "signature of hash",
  "replace": "id of another object of the same type [optional]",
  "objectType": "ontology",
  "schema": "id of a schema describing the sets, relationsets and attributesets [optional]",
  "template": "id of a template object [optional]",
  "title": "e.g. some ontology",
  "content": "e.g. ontology object to define e.g. an app ontology."
}
```

**Schema**
```
{
  "id": "hash of the serialized object data",
  "created_at": "<unix timestamp in seconds>",
  "created_by": "<pubKey, version>",
  "sig": "signature of hash",
  "replace": "id of another object of the same type [optional]",
  "objectType": "schema",
  "ontology": "id of an ontology [optional]",
  "title": "e.g. some ontology schema",
  "content": "e.g. schema to define valid/required tags/tag contents in an ontology object, e.g. using JSON Schema. TODO"
}
```

**Template**
```
{
  "id": "hash of the serialized object data",
  "created_at": "<unix timestamp in seconds>",
  "created_by": "<pubKey, version>",
  "sig": "signature of hash",
  "replace": "id of another object of the same type [optional]",
  "objectType": "template",
  "ontology": "id of an ontology [optional]",
  "title": "e.g. some template",
  "content": "e.g. template to define e.g. an UI representation of objects which can be used by clients. TODO"
}
```

Now objects could be defined on base of above ontology objectTypes without the need for new nostre kinds (or new objectTypes). Client and app devs could create new objects by extending the generic objectTypes with the optional and additional tags (properties). Restrictions on data and data validation could be enabled by using e.g. json schemas. The client could (hopefully) use these generic objectTypes to store (table/objectType), query and receive/send the different derived app objects. 

### Some points on the long list of open questions:
- Does something like above make sense from a client dev perspective (I'm not a dev.) ? Does that work with client dbs e.g. by using json type in postgres/mariadb/sqlite, also regarding querying? Is something like above usable? Does it have too much overhead? How to improve / simplify it?
- Would be nice to have some query-and-format mechanism to get data from stored ontology objects into templates, so even users could create apps. js-api? Macros? (more dreams)
- Regarding the use of templates for apps: How could this be made secure in clients? (regarding custom js and onepage js apps, js/app access to possibly private objects in local storage, access rights for apps/services/users?/.., ..)
- Lots of UI challenges for clients; generation of parts of UI from json schema? Generic visualization with nodes, edges and text fields? (by using json schema types and restrictions) (dreams again)
- How to handle extending/including/organizing ontologies best? meta-/user-ontology?
- How to define json schemas and how to combine multiple schemas?
- How to do versioning of (nested) objects? Where and how to handle replace-tag, in nested object and/or in outer event? How to implement updating references to replaced objects on clients?
- How to handle this best on nostr protocol level? Seperate kinds for structured contents like mentioned above? (Use a less leaky version of kind4?) Better to split this in different NIPs, eg. move spec for replace tag and for templates and schema objects/tags in separate NIPs?
- Are there any devs and spec-experienced people that are interested in playing around with something like that?

Please let's brainstorm/discuss this here on github, I'd appreciate any comments and participation!

Thanks, 
Ingo

**Comment by Giszmo** [comment]
>  (I'm not a dev.)

Wait, what?

I was staring some 5 minutes at this document and was wondering what it was that you wanted to do. We already do structure stuff and kinds and tags help with that and where that gets to its limits, we serialize objects into the content which is ugly but simple, with minimal overhead. And nostr is so attractive for many because it's accessible. We **want** it simple. We will - at least not for a very long time - switch to some binary serialization for the sake of saving 5% or 50% on the wire.

I'd like to close this issue to save other people time. It's not solving a problem we currently or soon have.

**Comment by fiatjaf** [comment]
Great, let's close. Thank you for sacrificing yourself on our behalf, @Giszmo.

Maybe before opening giant NIP proposals that will take several minutes from dozens of people that might try to read people should have to at least not use throwaway GitHub profiles.

@ingo7 next time please just open an issue with a short summary or question and we can proceed from there. Or talk to us on Nostr.
