### ISSUE TITLE
Possible NIP: Event Kind to Translate between nostr and REST/HTTP?

### ISSUE THREAD

**Issue by dfresh613** [nostr-protocol/nips#207]
Hello everyone,

Given the existing, widely used REST pattern and it being the foundation of so many HTTP based applications. It seems like it would be helpful if there was a defined means of bi-directionally translating REST/HTTP requests and nostr events.

I believe this could provide the following benefits:
- Defined pattern/interface to enable clients to query existing REST based web APIs through nostr relays
- Enable relays to capture and persist data from HTTP based servers 
- Enable developers to create web applications which are more easily supported by both standard HTTP, and nostr clients at the same time. This may help increase adoption by providing some form of parity to existing apps faster.

In terms of implementation, perhaps there could be:
- a new event kind which tells nostr relays to make a particular http request, and respond the result back to the client, or other relays
- a published nostr web standard which defines how web applications can structure their json responses to natively be consumed/parsed during nostr event processing

Before going into any lower level implementation details, and making a formal proposal, I am curious if this is something that anyone feels there is an actual need for?

**Comment by fiatjaf** [comment]
I think this opens room for introduction of a lot of bloat in the protocol and would prefer to not have it.

Can I ask you what is the problem with websockets?

**Comment by dfresh613** [comment]
Nothing is wrong with websockets :)

My primary thought was enabling relays to interact with existing web apps on behalf of clients. Maybe to allow a relay to charge a client to make a certain http request on their behalf, or for a chain of relays to do so. 

As you implied though, I suppose this would not have to be natively supported by nostr.

**Comment by Giszmo** [comment]
NACK

Sounds a bit like re-inventing TOR but without encryption.

Closing for now. If it solves any issue we have in nostr or enables censorship-resistance in a novel way that other tools don't solve better already, lets re-open it.
