### ISSUE TITLE
NIP-05 Won't Verify

### ISSUE THREAD

**Issue by shaneholloman** [nostr-protocol/nips#210]
Where may I get support please - specifically my nip-05 will not verify. I feel like I followed this correctly:
https://github.com/nostr-protocol/nips/blob/master/05.md
Converted my pubkey here: https://damus.io/key/
Placed it here: https://pano.nz/.well-known/nostr.json?name=shane
Placed the corresponding data into Damus app `shane@pano.nz`
CORs is set: https://cors-test.codehappy.dev/?url=https%3A%2F%2Fpano.nz&origin=https%3A%2F%2Fcors-test.codehappy.dev%2F&method=get
Damus not verifying me

orig key from Damus app: `npub1zra36366txls8v29vaseq2khq4zh4tq0nf54qf42psjhwtx69ucq7f8g3j`
convert to hex key from Damus: `10fb1d475a59bf03b1456761902ad705457aac0f9a695026aa0c25772cda2f30`

**Comment by fiatjaf** [comment]
It is verified correctly to me.

Also on https://nostr.guru/p/10fb1d475a59bf03b1456761902ad705457aac0f9a695026aa0c25772cda2f30

This is probably a bug on the client you're using.

**Comment by shaneholloman** [comment]
Sorry, I need insist there is an issue here

![issue exists still](https://snipboard.io/OJHpam.jpg)

**Comment by shaneholloman** [comment]
Understood, thought may have been a nips issue. I'm new to the space. sorry to waste you time @fiatjaf
