### ISSUE TITLE
[Draft] Lightning Zaps v2

### ISSUE THREAD

**Issue by ok300** [nostr-protocol/nips#228]
I'd like to propose a different approach to zaps that could solve some of the issues in #224.

Since it's fundamentally a different design, I didn't want to derail the discussion in the main PR, so I opened this separately.

This is an early draft meant for discussion. Please provide feedback and critique below. Thanks!

---

## Rationale

We want a way to send and receive LN payments on nostr in a way that can be tallied publicly.

Since there is no overlap between the LN / LNURL and nostr protocols, we achieve coordination among them by adding a layer of abstraction on top.

## Definitions

- Zapper: Service that combines LNURL and nostr, can be one of two kinds:
  - Sender Zapper: Consists of an LN wallet + basic nostr client. Paired with a specific nostr pubkey that can trigger the sending of a Zap.
  - Receiver Zapper: Consists of a wrapper around a LNURL-pay endpoint + basic nostr client. Paired with a specific nostr pubkey that, upon receiving a LNURL-pay request, it posts to nostr details about the invoice.

- Sender = nostr account that wants to send a zap
- Receiver = nostr account that receives a zap

Nostr messages

- ZapRequest = ephemeral nostr msg sent by Zap Sender to his Zapper, indicating desire to zap Recipient
- ZapInvoice = nostr msg posted by Zap Receiver, containing invoice hash and invoice details (amount, comment)
- ZapProof = nostr msg posted by Zap Sender, containing preimage

Entities involved in a zap

- Sender = nostr client
- Sender Zapper = service
  - paired with sender pubkey and relay list on which to listen for ZapRequests (via nprofile?)
  - has nostr profile linked to original Sender pubkey (metadata field? new or existing? TBD)
  - has access to its own LN wallet
  - can send from LN wallet on behalf of Sender
- Receiver Zapper = service
  - paired with recipient pubkey and relay list
  - has nostr profile linked to Recipient pubkey
  - no need for wallet, can have wrapper around existing LN Address of recipient

## Setup

- Sender pairs pubkey with Sender Zapper (onetime)
- Sender makes sure Sender Zapper LN wallet has enough balance (top-up when needed)
- Receiver pairs pubkey with Receiver Zapper (onetime)
- Receiver configures Receiver Zapper to point to desired LNURL endpoint (onetime)

## Workflow

- Sender
	- [1] nostr: send ZapRequest ("I want to zap this recipient this amount")
- Sender Zapper
	- [2] nostr: listens for incoming ZapRequests (nostr msgs signed by paired pubkey)
	- [3] LN wallet: on receiving ZapRequest, start payment by contacting recipient LNURL-pay endpoint of Zap Receiver
	- [6] LN wallet: pay invoice, as part of the LNURL workflow
	- [7] nostr: post ZapProof (preimage as proof of payment)
- Recipient Zapper
	- [4] LNURL-pay: listens for request. On request, create invoice, return to caller
	- [5] nostr: posts ZapInvoice (invoice hash and payment metadata like amount, comment)

A zap is valid when both ZapInvoice and ZapProof are present and matching. Nostr clients can tally valid zaps.

An invalid zap can mean the invoice was not paid, or was a fake invoice. Nostr clients should ignore these.

## Summary

- LNURL
	- no change to well-known nostr.json
	- compatible with existing LN Addresses
- nostr: 2 messages (+1 ephemeral)
	- challenge, as nostr msg signed by Recipient Zapper
	- response, as nostr msg signed by Sender Zapper
	- zap is considered valid when both messages match
- Zapper
	- Sender can be non-custodial or custodial (wrapper around LN wallet)
	- Receiver can direct payments to existing LN Address or LNURL endpoint

Benefits vs current approach:
- no LNURL changes needed
- minimal nostr client changes needed (send 1 new ephemeral msg kind; validate and tally zaps)
- nostr clients don't need to parse BOLT11 invoices
- nostr clients don't need to parse LUD06 or LUD16 to zap

Zap to normal LN Address is not possible, because a Zap is initiated via an ephemeral nostr message. However a LNURL-pay workflow can be done from a simple LN wallet to a Zapper Receiver, which will post a nostr ZapInvoice. Howver this will not be tallied by clients, because the ZapProof will be missing.

## Future work

Auto matching zaps: I configure my Zapper to match 1:1 every Zap made by account X who I follow; when it detects X is making a new Zap, my Zapper would initiate a separate Zap for the same amount, same recipient, thus automatically doubling the original sender's Zap.

Recipient Zapper can also listen to nostr messages instead of LNURL, which needs a publicly accessible domain. This would allow a non-custodial implementation, like on an Umbrel.

**Comment by fiatjaf** [comment]
I see what you have here, but there are two problems:

 - Step 7 is broken: the Nostr client will probably not be the same as the Lightning wallet, so how will it get the preimage to broadcast?
 - There is no way to attach a specific payment to a specific Nostr note.

The other zap NIP solves these two problems.

**Comment by ok300** [comment]
> Step 7 is broken: the Nostr client will probably not be the same as the Lightning wallet, so how will it get the preimage to broadcast?

Step 7 is made by the Sender Zapper, which is a service with a LN wallet and its own nostr client and pubkey. It's like a bot, listening and reacting only to it's owner's zap request (step 2).

> There is no way to attach a specific payment to a specific Nostr note.

You mean zapping a note? The ZapRequest in step 1 could contain either a pubkey (for zapping profile) or a pubey and note ID (for zapping note).

I'm preparing a demo, will post the link when I have it.

**Comment by sixproph3tsix** [comment]
Sender pairs... pubey?

**Comment by ok300** [comment]
@sixproph3tsix lol thanks, fixed, it's pubkey.

**Comment by fiatjaf** [comment]
> Step 7 is made by the Sender Zapper, which is a service with a LN wallet and its own nostr client and pubkey. It's like a bot, listening and reacting only to it's owner's zap request (step 2).

In this case this is bad since it won't work on normal Lightning wallets -- or it will require these to implement this NIP, which makes everything super hard.

**Comment by ok300** [comment]
The other way around. LN Wallets don't have to implement this to become a Zapper, but a Zapper is something on top that uses a normal LN wallet.

The Zapper could be a custodial service on top of a custodial LN wallet (small nostr client listening to 2-3 event types and issuing / paying invoices to own LN wallet).

Or a non-custodial bot, running on an Umbrel (same as above, but using Umbrel's LN wallet to pay / receive).

**Comment by ok300** [comment]
I've simplified this into #243 . I removed a few steps, removed reliance on preimage and reliance on LNURL.
