### ISSUE TITLE
How exactly does "limit" work?

### ISSUE THREAD

**Issue by hamano** [nostr-protocol/nips#233]
There is an issue between iris.to and the relay server relay.damus.io.

iris.to always send the following request(regardless of open global timeline)

```
{"kinds":[0,1,3,6,7],"limit":200}
```

The relay server responds with 200 events , then responds EOSE, and continues to send the latest events.

Since iris.to does not explicitly CLOSE, browser will always continue to receive a large traffic of global timelines.

Relay servers other than relay.damus.io do not behave in the same way.
After sending 200 events and responding EOSE, no more events will be responded.

Which is more compliant with the specification, client or relay server?

```
"limit": <maximum number of events to be returned in the initial query>
```

How should this specification be interpreted?

Thank you in advance.

**Comment by ok300** [comment]
AFAIK the subscription does two things:

* give you `limit` number of past events (then EOSE), then
* newly published events

with only events that match the filter.

**Comment by hamano** [comment]
Thanks for your advice.

If "until" is specified, no more respond new events.
There may be a misunderstanding that "limit" do same behavior as "until".

I will report a issue to iris.to.
