### ISSUE TITLE
'client' in the new name of tag

### ISSUE THREAD

**Issue by kappaseijin** [nostr-protocol/nips#239]
Examples of NIP-25 Reaction content are '+', '-', 'like', ' dislike' are listed. However, emojis such as '❤️' are also often sent as client implementations, and there are many other emojis when looking at the relay event. I would like to know. I would like to know which client(service) is using those emojis.
So I want 'client' in [Standardized Tags](https://github.com/nostr-protocol/nips#standardized-tags). With it, I can know which clients are using other emojis than the example.
Also, I think Reaction can be an image linked by URI other than emoji or ascii.
Twitter was useful to find that because the client is written in the tweet. This is a realization of that functionality.
best regards.

**Comment by fiatjaf** [comment]
> Also, I think Reaction can be an image linked by URI other than emoji or ascii

Let's not introduce this unnecessary complication, please. You can send image URLs in kind:1 events already.
