### ISSUE TITLE
NIP-01 what is the max length of subscription_id?

### ISSUE THREAD

**Issue by noobdummy** [nostr-protocol/nips#240]
```
<subscription_id> is a random string that should be used to represent a subscription.
```
what is the max length of subscription_id?
is there a limit?

**Comment by fiatjaf** [comment]
Whatever relays want to allow. I was running a relay I wouldn't allow more than 64 characters.

**Comment by barkyq** [comment]
I only allow 20 characters on mine. If it is larger than that the relay responds with a `NOTICE` and doesn't accept the subscription.

**Comment by mikedilger** [comment]
gossip client uses 32 characters, 16 representing the time, 16 being random.  I guess we aren't talking to @barkyq 's relay.

**Comment by barkyq** [comment]
Whoops @mikedilger will update that

**Comment by barkyq** [comment]
I also just revealed that I do not use `gossip` lol sorry mike I hear it is very good though. one day I'll get that set up

**Comment by mikedilger** [comment]
your right @barkyq they don't have to be 32 characters. I could just use 2 characters and count up from zero.

**Comment by barkyq** [comment]
It's your call, I will change the `max_subid_length` to 32 on my relay though

**Comment by mikedilger** [comment]
No, no you're right. No I mean I'm right that you're right. :-) Let's both make the change.

**Comment by barkyq** [comment]
Sounds good. Thanks for letting me know.
