### ISSUE TITLE
NIP05 allow for subdomains?

### ISSUE THREAD

**Issue by aleixisp** [nostr-protocol/nips#241]
Hello, 

I'm trying to implement a service in my API that allow my users to link their username to a Nostr account. I'm trying to also add the NIP05 json file in my backend so it's Reachable by the clients of Nostr (eg. Damus). 

Does NIP05 works with subdomains?
e.g aleixisp@api.universalname.space

It would
Be fairly easy to deploy this on my end, but I'm not sure if current NIP allows for that (it's always references as <domain>) 

Many thanks!

**Comment by barkyq** [comment]
Clients should allow with subdomains. Just tested with astral.ninja web client and it works.
