### ISSUE TITLE
Which is the real kind 8?

### ISSUE THREAD

**Issue by melvincarvalho** [nostr-protocol/nips#266]
We have three kind=8 NIPs

8 - bookmarks ([NIP-29](https://nips.be/29))
8 - poll & vote ([NIP-41](https://nips.be/41))
8 - badges ([NIP-58](https://nips.be/58))

Are we going to reassign numbers or multiplex?

see also: https://github.com/nostrdata/kinds/issues/1 and [kinds list](https://nostrdata.github.io/kinds/)

**Comment by barkyq** [comment]
none of these are "merged", so to speak, so I suppose the correct answer is "none of them are `kind:8`"

**Comment by fiatjaf** [comment]
Multiplex? No, reassign numbers when the first of these is merged.

Polls are just an idea no one seems to be interested in implementing so far (great), bookmarks are being discussed in NIP-51 with a different kind numbers.
