### ISSUE TITLE
NIP-69 - Proposal

### ISSUE THREAD

**Issue by cryptofolyo** [nostr-protocol/nips#275]
NIP-69
======

Nearby Protocol
----------------------------------------------------

`draft` `optional` `author:cryptofolyo`

As of now NOSTR can give me all the feeds from all the people whom i followed. The second type of feed is the `global feed` which is mostly spam and irrelevant. Proposing a third type of filtered feed which is a subset of the global feed from which i can get connected to 

1. Ability to search for a hashtag in my feed
2. Ability to connect with Like minded people nearby me who post content with the same `hashtag` - Posts with higher satoshi tips appear first in the sort order of the filtered feed.
3. Ability to connect with Like minded people far away from me who keep posting contents with the same `hashtag` which is tipped with satoshis by many other people who post content with the same `hashtag`
4. Ability to prompt common hashtags used by the Like minded people 

The ultimate aim or goal of this protocol is to
1. Discovery of the best author or content creator nearby me for each particular topic denoted by a <`hashtag`>
2. Increasing the discovery range of high quality content authors by increasing their kilometre range based on the total satoshis they earned as tip on that `hashtag` or topic
3. Posting high quality content is incentivised as the discovery range of the post is increased proportionately

### Example 
1. Suppose that you need to learn about setting up a NOSTR Relay. Someone from anywhere in the world may be quite an expert internationally in setting up relays. So i need to connect with that person if i search for #nosterrelay in my feeds. This person will be tipped from across the world.
2. Now u also want to connect with some other people nearby in town who already interested in setting up a #nosterrelay - So this person is seen only to all other searchers from nearby him or her

### Challenges
1. People may start to tip themselves to increase their discovery range - This can be mitigated in future by Peer review protocol - Where the discovery range of a content author is determined not only by the tips but also by how many other authors on the same topic have acknowledged this author

### Privacy and Security concerns
Instead of using the exact geolocation of a user - The approximate geolocation randomised within 1 kilometer circle can be used permanently as the user geolocation

**Comment by fiatjaf** [comment]
These things are meant to be tweaked with and experimented by clients, they are not NIP material.

**Comment by cryptofolyo** [comment]
Thank you for the response @fiatjaf 
Any thread to post ideas like these to be taken up by the developers to implement in their clients?

**Comment by cryptofolyo** [comment]
Also can u start a thread in GIT exclusively for NOSTR ideas which can be posted as whitepapers?

**Comment by fiatjaf** [comment]
It's better to talk directly to the developers. Either inside Nostr itself or on their dedicated Telegram groups, there are multiple.

**Comment by cryptofolyo** [comment]
Thank you for the advise
Will try it out.
Regards,

**Comment by akhavr** [comment]
I'm hoping to experiment in this area in few months, as time allows.  Content recommendation and discovery is area, that I'm interested for years.  Finally a really open protocol to build on.

**Comment by cryptofolyo** [comment]
> I'm hoping to experiment in this area in few months, as time allows. Content recommendation and discovery is area, that I'm interested for years. Finally a really open protocol to build on.

connect with me at cryptofolyo@gmail.com if you are interested.
Regards,
