### ISSUE TITLE
NIP-10 relay hint

### ISSUE THREAD

**Issue by barkyq** [nostr-protocol/nips#290]
Some people do not include the relay hint, e.g., a brief search in my feed produces:
https://www.nostr.guru/e/ae057ff319c8c3e5eda82327a7ae0272b5af1d6b98ebe3cac42523912b0ebf6b
https://www.nostr.guru/e/2991a97b1cee197f8efc6e31530e8a100d99401f382bfbb6b2b8eca8a9ac10a0

From NIP-10 on `"e"` tags
> `<relay-url>` is the URL of a recommended relay associated with the reference. It is NOT optional.

I think this line is very prescriptive and feels opinionated, and (as evidenced above) clients are not always following it. But a client developer maybe reads this and expects a relay URL will always be there.

Also sometimes it is not so easy for a client to add a relay hint. For instance, if the client is connected to a private proxy relay which handles event deduplication etc, perhaps listening on `ws://localhost:7447`. Is the client supposed to add `ws://localhost:7447` as the relay hint?

I propose the "it is NOT optional" line be removed and replaced with something like "adding a relay hint is RECOMMENDED."

**Comment by fiatjaf** [comment]
I agree. Please do it.

**Comment by barkyq** [comment]
will do!

**Comment by barkyq** [comment]
closing this, moving discussion to #291
