### ISSUE TITLE
NIP-01 text_note content clarification

### ISSUE THREAD

**Issue by macterra** [nostr-protocol/nips#297]
NIP-01 states:
> 1: text_note: the content is set to the text content of a note (anything the user wants to say). Non-plaintext notes should instead use kind 1000-10000 as described in [NIP-16](https://github.com/nostr-protocol/nips/blob/master/16.md).

Does markdown count as plaintext for text_notes? Clarification needed.

**Comment by Marcelo-Theodoro** [comment]
I don't believe so.
Markdown makes more sense in NIP-23: https://github.com/nostr-protocol/nips/blob/master/23.md

**Comment by Marcelo-Theodoro** [comment]
Don't you think that this part is enough:

```
1: text_note: the content is set to the text content of a note (anything the user wants to say). Non-plaintext notes should instead use kind 1000-10000 as described in [NIP-16](https://github.com/nostr-protocol/nips/blob/master/16.md).
```

I, at least, consider markdown as "non-plaintext"

**Comment by macterra** [comment]
Does everyone consider markdown as "non-plaintext"? If not, we might need some clarification here.

**Comment by staab** [comment]
The consensus from a while back was that markdown is fine insofar as it is also plaintext. So lists/headings are fine, but markdown links (for example) are not.

**Comment by macterra** [comment]
> The consensus from a while back was that markdown is fine insofar as it is also plaintext. 

Do you have a link to that discussion?

**Comment by macterra** [comment]
Markdown appears to be on the [roadmap](https://github.com/irislib/faq#markdown) for https://iris.to/

**Comment by Marcelo-Theodoro** [comment]
Relevant https://github.com/jonathanleger/nostrgram/issues/1

**Comment by staab** [comment]
I don't, somewhere in telegram probably. That was @fiatjaf's opinion iirc, and I agree.

**Comment by macterra** [comment]
> Relevant [jonathanleger/nostrgram#1](https://github.com/jonathanleger/nostrgram/issues/1)

In that case, I think NIP-01 needs clarification because one of the main selling points of markdown is that it is a plaintext format.

**Comment by fiatjaf** [comment]
Please don't do Markdown.

**Comment by fiatjaf** [comment]
379252f992c2528e287bc4ce7faee5631aa3f73c

**Comment by fiatjaf** [comment]
Please ask Martti to not do Markdown -- or, if he really wants to, ask him to disable the link syntax as in the issue linked above.

**Comment by macterra** [comment]
> Please ask Martti to not do Markdown -- or, if he really wants to, ask him to disable the link syntax as in the issue linked above.

Will do
