### ISSUE TITLE
NIP-08 fails to specify how to represent `#[0]` etc. as-is

### ISSUE THREAD

**Issue by shafemtol** [nostr-protocol/nips#319]
### Problem

Let's say I want to discuss NIP-08 through nostr itself. I might try to mention an example of what the actual plaintext looks like behind a mention. So I might try to say inside a kind-1 text note as a reply to someone else:

`Hi, @alice. In the raw json, your mention of @bob inside your note is actually represented as #[0].`

On all clients I have tested, this comes out wrong: The text `#[0]`, which should be represented as-is, collides with whatever the client put at position 0 in `tags`, likely either one of the mentioned users or the id of the note being replied to. It might come out as e.g.:

`Hi, @alice. In the raw json, your mention of @bob inside your note is actually represented as @alice.`

Which ruins the message in this case.

### Suggested Solution

- NIP-08 should specify that whenever the user tries to actually write `#[0]`, `#[1]` etc., the client MUST NOT put a tag other than some specified placeholder tag at the corresponding position in the `tags` list, putting any other tags at other positions in the list.
- NIP-08 should specify/clarify that whenever there is an apparent NIP-08 reference such as `#[0]` but where there is not an `e` or `p` tag (or other tag explicitly specified as having NIP-08 functionality), the client MUST show the text as-is.

These two together, if implemented by clients, fix the issue in a backwards-compatible way.

As for the placeholder tag, this could be something like `ph` (single-letter should be avoided due to NIP-12).

**Comment by shafemtol** [comment]
Demonstration of broken notes here: [note1ztk0np5vpy58k8gytsxpmhshx7vqeyttyvse47p4aghcwhkvvadq3vvfsy](https://astral.ninja/note1ztk0np5vpy58k8gytsxpmhshx7vqeyttyvse47p4aghcwhkvvadq3vvfsy)
In the 4 notes referenced from this one, I try using four different client to write in plain text:
`Testing reply from <client>: #[0] #[1] #[9]`
All clients put the id of the note being replied to and/or the pubkey of the user being replied to at `tags` positions 0 and/or 1, resulting in an erroneous mention. NIP-08 should more clearly specify how clients can avoid this situation by specifying a placeholder tag to put at positions 0 and 1 in this case.

When viewing notes, some clients will show apparent references outside the range of the `tags` list as-is, while others will show some broken text at these locations. I tested 4 clients here: [note19s2ltw0gk4krxu9stsghtlmgkl4fttgr80z7xgs9m959wt40jc7sj9np8j](https://astral.ninja/note19s2ltw0gk4krxu9stsghtlmgkl4fttgr80z7xgs9m959wt40jc7sj9np8j)
Although I consider the broken viewing here to be 100% the fault of the client, having NIP-08 explicitly state the wanted behavior here would help avoid these bugs.

I have yet to test the behavior of clients on viewing notes with placeholder tags.

**Comment by fiatjaf** [comment]
What is the wanted behavior?

**Comment by shafemtol** [comment]
In my example, the desired output is `#[0]`. If my client puts the pubkey of alice in a `p` tag at position 0, it will instead show as `@alice` or something to that effect. But my client might also have put the pubkey of bob there, or an `e` tag referencing alice's post; As a user I generally cannot know what current client implementations will do if I enter the string `#[0]` into a text note.

To "escape" the `#[0]` string, what I'm proposing is that my client should see that I entered `#[0]` and therefore _not_ put a `p` or `e` tag at position 0 in `tags`, but instead some placeholder tag that has no other purpose than to "escape" it. Adding a simple tag like `["ph"]` at position 0 should be a backwards-compatible way to do it (i.e. shouldn't break proper implementations of current NIP-08 spec).

**Comment by arthurfranca** [comment]
> To "escape" the `#[0]` string, what I'm proposing is ... Adding a simple tag like `["ph"]` at position 0....

What about a tag ["noop"] instead, meaning [no operation](https://en.wikipedia.org/wiki/NOP_(code))?

**Comment by staab** [comment]
I've said this before, but the current way of interpolating mentions is Bad, because it confuses code with data. This is the same mistake SQL made that led us down a several-decade-long path of SQL injection problems.

So instead of fixing this with weird "escapes", let's actually fix the problem. The `#[0]` notation was introduced before npubs existed, and was introduced because hex keys aren't distinguishable from other data. While `#[0]` is code, `npub1blah` is data, just like a URL is, and just like a URL, bech32 entities can easily be recognized and modified.

A much better solution than fixing the inherently broken interpolation behavior we have now is to simply embed npubs, notes, nprofiles, nevents, etc in notes. These are human readable (insofar as someone can recognize what it is in a text-only client and copy/paste into a search box), and can easily be parsed by clients to interpolate a link with the username or whatever behavior is desired.

**Comment by shafemtol** [comment]
> What about a tag ["noop"] instead, meaning [no operation](https://en.wikipedia.org/wiki/NOP_(code))?

I thought about "noop", but it feels a little out of place, as tags aren't operations. How about `["ign"]`, for "ignore"?

**Comment by shafemtol** [comment]
> So instead of fixing this with weird "escapes", let's actually fix the problem.

The term "escapes" evokes the abominable idea of inserting even more codes into the text data in order to escape other codes. Let it be clear that the fix I'm proposing does not introduce any other codes or touch the text data at all. It merely shifts tag positions so that NIP-08 replacement does not kick in where it shouldn't.

> The `#[0]` notation [...] was introduced because hex keys aren't distinguishable from other data.

That doesn't sound right. In this case the hex representations of mentioned pubkeys and events would be easily distinguishable from other data. Just take the `e` and `p` tags from the event and match them against the text.

> A much better solution than fixing the inherently broken interpolation behavior we have now is to simply embed npubs, notes, nprofiles, nevents, etc in notes. These are human readable (insofar as someone can recognize what it is in a text-only client and copy/paste into a search box), and can easily be parsed by clients to interpolate a link with the username or whatever behavior is desired.

I do not think it is quite so simple. There is a difference between a mention and spelling out an npub. With a mention, the author might not care how the mention is viewed by a client, whether as a (likely shortened) npub or something like `@alice` or `Alice`.

There are other times when you _do_ want that npub to remain untouched by a client viewing the note. Here's a real-world example I came across: [note1s300mshusxz450dpm3rf6cswys82q43v8am0zcpduxzkrrv2aarq3lszrn](https://astral.ninja/note1s300mshusxz450dpm3rf6cswys82q43v8am0zcpduxzkrrv2aarq3lszrn). Here, the author tried to post a GPG-signed message, but the npub in the message was mangled, resulting in GPG being unable to verify the message. In this instance, it was the _author_'s client that broke the note, but note that nothing in NIP-08 would have prevented a proper client from letting the author present the npub as-is in this case. But if you wanted _viewers_' clients to automatically mangle npub strings however they see fit, you'd have a different variant of the same problem that I'm pointing out in this very issue. Then you'd have the challenge of somehow disambiguating these representations of the text through some auxiliary and, except for trivial cases, probably _not_ very human-readable metadata.

Another issue is that with bech32 strings, you introduce redundancy that is not compressible by the existing compression support in WebSocket (and possibly DB storage), as the corresponding `e` and `p` tags use the hex representation. With hex strings, this extra redundancy would at least be compressible.

I do not agree that NIP-08 is _inheretly_ broken, merely incomplete. Although you may justly consider it ugly, as long as the possible NIP-08 references from the `tags` list are made adaptive so that they do not match any of the existing text, it works just as intended, and it lets the author unambiguously declare whether some representation of a pubkey or event id should be mangled or not.

**Comment by staab** [comment]
You make some very good points. For my part, I plan to linkify bech32 entities in Coracle regardless of mention tags, since I'm aiming at non-technical users. For clients with a more technical audience, a solution to the use case mentioned above would be to expose the raw content if the end user needs it. 

But still, the benefits of using bech32 entities are not as obvious as I thought, plus the main benefit of escapes as proposed is that they're backwards compatible.

The problem with "noop" or "ign" is it forces publishing clients to parse the raw text of a message in order to help receiving clients display things correctly. This seems error prone and not likely to be implemented by authors.

**Comment by shafemtol** [comment]
> The problem with "noop" or "ign" is it forces publishing clients to parse the raw text of a message in order to help receiving clients display things correctly. This seems error prone and not likely to be implemented by authors.

It does complicate implementations a little, as tag positions depend on the text data, while NIP-08 references in the text data depend on tag positions. But such is the nature of "magic" strings like those NIP-08 imposes. How complicated the fix is depends on the existing implementation, but I can't imagine an implementation where you can't find a reasonable way to deal with it.

**Comment by arthurfranca** [comment]
> A much better solution than fixing the inherently broken interpolation behavior we have now is to simply embed npubs, notes, nprofiles, nevents, etc in notes.

This makes sense to me as it is similar to how kind 1 embed images using urls in content instead of inside tags. It would also narrow down the usage of e tags to replies and p tags to notifications.

**Comment by alexgleason** [comment]
Here's an example of why this is a problem.

![Screenshot from 2023-04-27 12-47-42](https://user-images.githubusercontent.com/3639540/234950179-05f92b4f-fd2d-4133-824b-a72d46b12388.png)

![Screenshot from 2023-04-27 12-48-13](https://user-images.githubusercontent.com/3639540/234950130-0c699f0b-8232-46f2-b6d7-2e254379ab5e.png)

**Comment by alexgleason** [comment]
IMO quote posts and media attachments should not be represented in the `content` field of a note **at all**. They should _only_ be tags, and then it's up to the client to decide where to display them, usually underneath the content. Rendering kind 1 content is currently insane and does not work correctly a lot of the time. What if I'm trying to share an image without a file extension? How are we dealing with whitespace issues? It's so much easier to just do away with the entire concept of `#[0]` markers and rely solely on tags. This is what ActivityPub does.

**Comment by staab** [comment]
> IMO quote posts and media attachments should not be represented in the content field of a note at all

Render one of The Nostr Report's posts using that heuristic and tell me how it goes. I guess arguably that should be under NIP-23, but you need media to be represented inline for notes with multiple images/links make sense.

At any rate, this conversation has been decided via [NIP-27](https://github.com/nostr-protocol/nips/blob/master/27.md), so I'll go ahead and close it.

**Comment by staab** [comment]
> This is actually nuts tho

😂

And yeah, I think I agree with you that for instagram-style posts at least, where the media is front-and-center having the media in tags rather than content. Maybe https://github.com/nostr-protocol/nips/pull/478/files can be adapted to support that use case.

**Comment by mikedilger** [comment]
Probably not the right place to say this, but I just thought of a thing that would solve two problems at once.

One problem is the expense of parsing the content of every event eagerly, as @jb55 brought up on another issue. The other is the problem of these #[0] tags in the content, and further the processing of URLs and bech32-TLV type data in the content. So here is the idea:

Tags specify the thing (e.g. url, nevent, whatever) but also the offset into the content where they should be rendered (byte 78). That offset would by convention be an offset into the original content not after the content slides due to the insertion of preceding content specials. Then you get the benefit of tags, the benefit of being specified somewhere in the content, and you avoid duplication.

Anyhow, maybe too late. Or maybe we make a new TextNote type.  Or maybe we change things again.  Or maybe this is a bad idea. I dunno.

**Comment by fiatjaf** [comment]
I like the offset idea. I was going to suggest that for the image metadata NIP but I thought I was being dumb.

We would need the starting offset and the ending? Or not?

**Comment by mikedilger** [comment]
I don't see why we would need an ending offset or a length. In fact I think clients would render something very special at the point of the offset (e.g. links, buttons, highlighted text that isn't the literal thing) so these insertions are logically zero length, and clients have to deal with whatever they actually put there.
