### ISSUE TITLE
smart contract in nostr?

### ISSUE THREAD

**Issue by villenmarx** [nostr-protocol/nips#329]
Hi.

I would like to know if possible to use nostr smart contracts. Would it be possible to use nostr smart contracts?

use case: For example, If any relay has an x quantity of spam, somehow this relay try to distribute the weight of messages to the quantity x of the relay available to prevent a message from being missing. Maybe, the smart contract can do so.

So, I would like to know if there would be a possibility for each relay to have an smart contract, integrated code of conduct. For example, If spam is detected, the spam relay is placed on a public list where it cannot send messages until it gains confidence again.

What do you all think of this idea?
So, Is it possible to program or schedule relay? Is there any technical specification about smart contracts in nostr?

**Comment by fiatjaf** [comment]
Yes, it is possible. Anyone can run their relay in any way they like, with any program they want. Relays are just servers.
