### ISSUE TITLE
NIP-02 (Kind 3) doesn't match what it's currently used for (following/followers lists) and doesn't scale for that purpose

### ISSUE THREAD

**Issue by alexgleason** [nostr-protocol/nips#335]
When I was first reviewing the spec I didn't realize there _was_ any convention to follow people, because NIP-02 seems to be for a different purpose.

However, basically all clients use it for followers/following. This makes it a bit difficult to scale in the following ways:

1. Since Kind 3 is a _replaced_ event, it's susceptible to race conditions when using multiple clients. Unless Client B syncs Kind 3 events before the next follow, it could replace follows from Client A.
2. Getting the people who _follow_ a person requires querying `#p` of Kind 3 events, which means you download **the entire following list** of every person who follows the target user, just to increase the counter by 1. If you visit a popular profile on Iris, you'll see that "followers" count slowly start to fill up... that's because it's slowly downloading every Kind 3 event with the target user. If every one of those events itself has 1000 followers, this system struggles.

**Comment by alexgleason** [comment]
This is potentially related to https://github.com/nostr-protocol/nips/issues/159 in the sense that it has some overlapping problems, and at the very least I would propose a new message type between clients and relays:

Client to relay:

```js
["COUNT", <filter>]
```

Relay to client:

```js
["COUNT", <filter>, <count>]
```

Filter is the same as used in a REQ. Count is a number. That doesn't solve all the problems here, but would partially solve it as well as solve various other problems.

**Comment by alexgleason** [comment]
In terms of the actual problem here, I would consider making "Follow" a specific kind of event with only a single "p" tag. Combined with a COUNT option above it would solve both problems. (sorry for triple post)

**Comment by earonesty** [comment]
also, most clients are using Kind-3 to list the relays that a user uses in the content section of the kind-3 note, even though i don't see that in any of the NIPS.  is that somewhere i'm not looking?

**Comment by staab** [comment]
Using kind 3 for relays was invented a long time ago by a client author. It was never standardized, use NIP 65 instead.

**Comment by staab** [comment]
The conversation around NIP 65's pull request should also answer the other questions being put forward here: https://github.com/nostr-protocol/nips/pull/218

COUNT has also been proposed but has its own problems: https://github.com/nostr-protocol/nips/pull/144

Closing this since most of the topics are already in progress elsewhere.

**Comment by mikedilger** [comment]
I think there is a new idea up there that [person A is following person B] is one event, rather than [person A is following B,C,D,E...]  as one monolithic event.  Then if you follow 100 people you have 100 replaceable/deletable events out there with less chance of clobber and cheaper counting even if we don't implement COUNT.  If that's discussed elsewhere, leave a link, otherwise maybe we reopen and discuss it here.

My concerns would be mostly whether clients will switch, and that there's not much benefit to switching until other people switch.

**Comment by staab** [comment]
There was some discussion about that on the PR (https://github.com/nostr-protocol/nips/pull/218#issuecomment-1416248372 for example), and the consensus seems to have been that that's an antipattern on nostr (https://github.com/nostr-protocol/nips/pull/218#issuecomment-1416824551).

**Comment by earonesty** [comment]
But literally nobody cares about 65. I can't find a single client that posts to it so I have to support the content data in kind three.  can't we just document that and deprecate it instead of ignoring it?

**Comment by mikedilger** [comment]
@earonesty gossip and coracle use NIP-65, nostros either has it or is releasing it soon, and astral is working on it.

Other clients that use the content of kind-3 may keep doing that, and they may ignore NIP-65, but what's the problem?  If you want to support the content of kind3 by reading from it, that's what I had to do too for gossip.  But I don't create it. I don't want to propagate bad ideas.  It's also why I refuse to recognize notes with tags that use bech32 encoded ids or pubkeys. I want to support different ways of doing things, but there has to be a line.

**Comment by fabianfabian** [comment]
> I think there is a new idea up there that [person A is following person B] is one event

I prefer this solution. It's also useful for showing in your notifications [person A is now following you]

**Comment by fiatjaf** [comment]
> It's also why I refuse to recognize notes with tags that use bech32 encoded ids or pubkeys.

Oh, these exist? No way. How can people be doing this? Please stop.
