### ISSUE TITLE
NIP-33 - Doubt about answers and references

### ISSUE THREAD

**Issue by frbitten** [nostr-protocol/nips#346]
I have a doubt about the functioning of the NIP-33. When an event is replaced does the new event have a new ID?

What happens to old event responses and references? Are they edited or do they keep a reference to an event that will no longer exist?

**Comment by arthurfranca** [comment]
> When an event is replaced does the new event have a new ID?

Yes, new id. What doesn't change is kind, pubkey and first d tag.

> What happens to old event responses and references? Are they edited or do they keep a reference to an event that will no longer exist?

References will not be edited. If a reference was made with `e` tag, it will point to a deleted event. If it was made with an `a` tag, it will point to the updated event.
