### ISSUE TITLE
NIP IDEA: private and testing private key space, for testing/local use

### ISSUE THREAD

**Issue by jg1uaa** [nostr-protocol/nips#352]
Currently there is no limit of 256bit (private) key space usage. For ease of software development and private/local relay server, here is an idea of key space.

1. Test key

it consists from same digit, like:
```
0000000000000000000000000000000000000000000000000000000000000000
1111111111111111111111111111111111111111111111111111111111111111
2222222222222222222222222222222222222222222222222222222222222222
3333333333333333333333333333333333333333333333333333333333333333
```
to
```
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
```

(`0000...0000` and `ffff...ffff` can reserved for special purpose)

otherwise, easily assumed from hex speak:

`deaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddead` (dead)
`baddcafebaddcafebaddcafebaddcafebaddcafebaddcafebaddcafebaddcafe` (bad cafe)

2. Local key space

Imagine, private IPv4 address like 192.168.xxx.xxx uses local network at your home, small office and so on.

I think Nostr looks friendly for IoT/M2M application, so there is a case that private relay servers work in closed (not connected to global) network. To reduce the damage when these servers are accidentally connected to global, how about to separate key space?

Simply private keys that have top of 64bits are '1' are treated as 'local', application uses remain 192bits for key.

`ffffffffffffffffxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`

These are just an idea, please grow to any NIP through discussion.

**Comment by fiatjaf** [comment]
I don't understand how can keys be "reserved"? You're saying that clients should match all keys they see against a hardcoded set of reserved keys and ignore them? Or what?

**Comment by jg1uaa** [comment]
Oops, we cannot check private key directly... Indeed private key is fixed, but public key is scrambled by random vector.  This idea should go to trash box.

If we could do, write a document for users that tells not-to-use simple private key with nsec example.

**Comment by jg1uaa** [comment]
please wait...

**Comment by fiatjaf** [comment]
I think this is not a good idea, because it is not enforceable and doesn't really help. People are free to test with these keys on "mainnet".
