### ISSUE TITLE
Open nostr links in app

### ISSUE THREAD

**Issue by milefashell** [nostr-protocol/nips#390]
## Idea
I propose to have an url scheme to share links for nostr elements. 

## Benefit
We can conveniently share links to nostr elements in any application, and it would be easier to view it in any application. So we can have a cross-platform, cross-application referencing solution.

## Scheme
The proposed url scheme would look like this:

`nostr://<filter>:<data>` 

where `<filter>:<data>` can be seen as an url.

The filter would help the identification of the data, meaning if we are sharing a link to a profile, link to a note, etc. Proposed filter ideas are below.

### Proposed filter ideas
- User: `nostr://user:npub`
- Note: `nostr://note:note_id`
- Hashtag: `nostr://hashtag:hashtag_text`
- Channel: `nostr://channel:channel_id`
- Channel message: `nostr://channel_message:channel_id:message_id`
- Suggest relay: `nostr://suggest_relay:relay_url1,relay_url2,relay_url3`
- Search: `nostr://search:search_terms`

The url shall be url encoded.

**Comment by staab** [comment]
This already exists, see https://github.com/nostr-protocol/nips/blob/8362ff8f79d913ac1dfded9668cd31dcc8c73f22/21.md. Feel free to open a pull request to NIP 19 for use cases that aren't yet supported.

**Comment by rusteroobs** [comment]
>  This already exists, see https://github.com/nostr-protocol/nips/blob/8362ff8f79d913ac1dfded9668cd31dcc8c73f22/21.md. Feel free to open a pull request to NIP 19 for use cases that aren't yet supported.

There is a similar request here: [NIP-01: Filters in REQuest messages](https://github.com/nostr-protocol/nips/issues/365)
