### ISSUE TITLE
roadmap in nostr?

### ISSUE THREAD

**Issue by ghost** [nostr-protocol/nips#409]
Hello.

I would like to know if there is any roadmap for proposals in nostr. if there is any roadmap for proposals in nostr?

**Comment by fiatjaf** [comment]
No. There is no roadmap. Nostr is already finished.

**Comment by rusteroobs** [comment]
> No. There is no roadmap. Nostr is already finished.

I disagree, here's the roadmap.
![image](https://user-images.githubusercontent.com/130608073/231607054-4d60047e-7d56-41cd-a156-0bd261f37f7c.png)
