### ISSUE TITLE
New bech32 encoding format `nencrypted`

### ISSUE THREAD

**Issue by mattsats** [nostr-protocol/nips#422]
I propose a new TLV bech32 prefix `nencrypted` where users can share password-protected bech32-encoded entities.

I'm a pleb and new to NIPs so please someone guide me if this is a good idea?

Use cases:
* securely save an `nsec` by emailing it to yourself or copying it into notes app (improved security and UX)
* share a password-protected link to an `npub`, `nevent`, `note` etc.

Implementation
* encrypt string using AES-256 (supported by WebCrypto)
* decrypt string with password

**Comment by fiatjaf** [comment]
For encrypted `nsec` there is a specific NIP proposal already.
