### ISSUE TITLE
what is the best approach of implementing comments for kind: 1 text notes events

### ISSUE THREAD

**Issue by anasfik** [nostr-protocol/nips#423]
I researched the nips, but seems to not find a nip for implementing comments for text notes that are published with Nostr, is there an approach that I should follow in this, or I should just send another text notes events of kind 1 and refer to it with the `e` tag

**Comment by fiatjaf** [comment]
Just send another text notes events of kind 1 and refer to it with the e tag, that's the way.

See NIP-10.
