### ISSUE TITLE
Does a client required to manage some local state for the consistency

### ISSUE THREAD

**Issue by anasfik** [nostr-protocol/nips#426]
Hello.

In my case, i have a client part that sends a request to get all comments of a post event with a filter.

The thing is when all comments is got, the EOSE is retunrned  so, the request is finished.

All comments are rendered and got whatI expect, but in the same page I have a field for adding  comment, when it is exucuted, it adds the comment to th relay, but the previous request is finished and so no updates is happening on my page until I refresh the page or send a new request totally.

The question is, should I manage the state when adding a new comment locally, so when a comment is added, the event will be sent and a local state comment should be added, and so with a page refresh, it will seem normal for the end user ?

Or should I follow another approach so the request don't end at all and keep returning data ?

**Comment by fiatjaf** [comment]
The request doesn't end when you get an `EOSE`. The websocket is kept open and you should keep receiving new events from it until you close it manually. Maybe you are using a library that closes things when it shouldn't, what are you using?

**Comment by anasfik** [comment]
I'am using custom implementation for it, basically, I am listening to a request with the request object:

```json
[
  "REQ",
  "b287685dd69ece41264cba6770a20fa322f8390dd534a3d7cbc89c183c1054a7",
  {
    "kinds": [
      1
    ],
    "#e": [
      "6aca74282aa3e363dc1b0613da83b1b89a8c4e1097e176b0b526fd2f094e1d7c"
    ]
  }
]
```


it gets me all events that I expect and want, then the `EOSE` is returned.

at the same page, when I send another event to the relay WebSocket which has this data:
{
"kind": 1,
"content": ".."
"tags": [
  ["e", "6aca74282aa3e363dc1b0613da83b1b89a8c4e1097e176b0b526fd2f094e1d7c"];   
],
...
}

the event is sent successfully, but the previous listener doesn't get it as a new value like the subscription is closed/finished until I send a new request to get again all the data including the new one I made. so this is why I asked if the `EOSE`
 means that the request with its subscrirpotn_id is finished, I really don't know exactly if I'am thinking about it in the wrong way, or if it is a relay issue (was://relay.damus.io) or if this can happen for many other reasons, please can you help!

**Comment by mikedilger** [comment]
EOSE lets your client know that all the events you asked for which the relay currently has have been delivered.  But relays will keep delivering matching events as they flow in, so you shouldn't close the connection just because an EOSE has come in, unless you don't want those incoming events.

Many clients remember the timestamp of the EOSE (or the time they received the last event) and if they get disconnected, when they reconnect they specify a filter  "since" that timestamp so they don't get everything they got previously over again.

**Comment by fiatjaf** [comment]
https://user-images.githubusercontent.com/1653275/230799772-db766b7f-4c5c-4cd2-8fad-16bbf4112ad5.mp4

**Comment by anasfik** [comment]
Hello, thank you very much for giving me this time, I ran my project again and it works now as expected, I didn't touch anything. so I assume it was a connection issue from my machine or a temporary issue in the relay(s).
