### ISSUE TITLE
NIP-42: why allow either "OK" or "NOTICE"

### ISSUE THREAD

**Issue by npub1zenn0** [nostr-protocol/nips#458]
https://github.com/nostr-protocol/nips/blob/master/42.md#protocol-flow

> For that it can use a NOTICE or OK

There isn't even any distinction between the two mentioned in the doc. I see no reason to make things more difficult for client dev that way.

**Comment by fiatjaf** [comment]
`OK` is returned when the client sends an `EVENT` to the relay. `NOTICE` when a client sends a `REQ`.

**Comment by npub1zenn0** [comment]
I see, the spec is talking about any request getting rejected, not the `AUTH` itself. It doesn't state what the server sends after client sends auth: `server AUTH -> client AUTH -> now what on rejected?`.

**Comment by fiatjaf** [comment]
How could the client possibly produce a bad AUTH event? This would only happen if the client was completely borked and didn't know how to sign events, which shouldn't happen at all in real world usage, only during tests or development.

**Comment by npub1zenn0** [comment]
"bad" being "hasn't paid". So when I add a relay I haven't paid to access, that flow is what I go through

**Comment by fiatjaf** [comment]
Hmm, so you're already getting an `OK` after the `AUTH`, right? Isn't that in the spec? I think that probably should be the spec then.

**Comment by npub1zenn0** [comment]
Indeed yes, both `wss://filter.nostr.wine` + `wss://nostr.kollider.xyz` return with `OK`. wine gives `error: somemsg` and kollider gives `blocked: ...`.
