### ISSUE TITLE
NIP-15: shipping should specify regions, not countries

### ISSUE THREAD

**Issue by ibz** [nostr-protocol/nips#461]
Event 30017

```
...
    "shipping": [
        {
...
            "countries": [<String, countries included in this zone>],
        }
```

I am feeling that using the "countries" terminology here is very limiting.

Not only that there is not even a good definition of a "country" out there, but I might have different shipping costs to different regions around a country (US states for example, or a lower cost for the city I am in and I can meet face to face).

Also, I might want to have some "meta-regions" like "Europe", so I don't need to specify all included countries (although I agree this latter case could be emulated using presets in the UI).

What if we renamed "countries" to "regions" instead, which is a more flexible term?

@motorina0 agree?

**Comment by motorina0** [comment]
Yes, I agree `regions` is better than `countries`. 
Please open a PR.

**Comment by raiseprogrammer** [comment]
Hi @ibz @motorina0, For me it would make sense to say "location" or "locate". For example,

```
...
    "shipping": [
        {
...
            "locate": [<String, countries included in this zone>], // countries, regions etc
        }
```

or:


```
...
    "shipping": [
        {
...
            "location": [<String, countries included in this zone>], // countries, regions etc
        }
```


Location" or "locate" can be state, region, country, etc. What do you all think of this idea of ​​inserting a meta tag called: "locate" or "location"? it makes sense?

**Comment by motorina0** [comment]
@ibz I think your PR was merged. Can this issue be closed?
