### ISSUE TITLE
document which clients support which NIPs

### ISSUE THREAD

**Issue by khimaros** [nostr-protocol/nips#48]
it would be very helpful to understand adoption of NIPs and also useful for end users to select a client.

would this repo be a good place to store that sort of information?

**Comment by Giszmo** [comment]
Probably not. Check out https://github.com/aljazceru/awesome-nostr It would fit much better there.

I suggest to close this issue.

**Comment by vishalxl** [comment]
Made a small gist [here](https://gist.github.com/vishalxl/db8cf8ef2b6be97ae7352c3697fcafb5) about some of the clients. its not perfect, but may prove useful. Such a list could be added in the awesome-nostr list as a link, as mentioned by Giszmo.

**Comment by Giszmo** [comment]
Thanks @vishalxl! Absent objections in one week I'm closing this issue. @vishalxl you might want to turn that into a proper git repo where devs can make PRs towards and have it linked in https://github.com/aljazceru/awesome-nostr

**Comment by vishalxl** [comment]
The git with such a comparison is [here](https://github.com/vishalxl/Nostr-Clients-Features-List)

**Comment by khimaros** [comment]
@vishalxl this is great, thank you for putting it together!

one suggestion is to explicitly include the NIP id for each of those rows (potentially with a link to the NIP)
