### ISSUE TITLE
Reliance on ‘JSON.stringify’ for creation of id and signature is untrustworthy

### ISSUE THREAD

**Issue by Pranoy1c** [nostr-protocol/nips#563]
A slightly different issue was raised here:

https://github.com/nostr-protocol/nips/issues/354

My issue is that ‘JSON.stringify’ does not guarantee the order of keys. I am not referring to the order of the tags array, I am referring to the event itself. Both the ‘id’ and ‘signature’ rely on ‘JSON.stringify’ and have possibilities of mismatch as the order of keys isn’t guaranteed.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

Btw, this also applies to the ‘content’ if that’s a JSON.

The ‘replacer’ parameter to the ‘stringify’ might indicate a possible solution.

I think that either clients are just getting lucky so far with the order or they aren’t verifying signature.

This has the potential of causes issues on relays too if they decide to verify signatures before saving the events as relays may be using non-JavaScript implementations.

**Comment by fiatjaf** [comment]
There are already many non-JavaScript implementations. There is no problem of key ordering because the thing that is hashed is an array, not an object. If `content` is a JSON it will be stringified beforehand and will be passed around as a string.
