### ISSUE TITLE
Typo in NIP-01

### ISSUE THREAD

**Issue by Memory-of-Snow** [nostr-protocol/nips#584]
**Describe the bug**
Typo in NIP-01

**Typo**
Code in Events and signatures.
 "id": <32-bytes lowercase hex-encoded sha256 of the serialized event data>
  "pubkey": <32-bytes lowercase hex-encoded public key of the event creator>,
(Missing comma between the two elements.)

**Correct**
 "id": <32-bytes lowercase hex-encoded sha256 of the serialized event data>,
  "pubkey": <32-bytes lowercase hex-encoded public key of the event creator>,

**Comment by Drugjudy** [comment]
> **Describe the bug** Typo in NIP-01
> 
> **Typo** Code in Events and signatures. "id": <32-bytes lowercase hex-encoded sha256 of the serialized event data> "pubkey": <32-bytes lowercase hex-encoded public key of the event creator>, (Missing comma between the two elements.)
> 
> **Correct** "id": <32-bytes lowercase hex-encoded sha256 of the serialized event data>, "pubkey": <32-bytes lowercase hex-encoded public key of the event creator>,

thanks for pointing out this issue
