### ISSUE TITLE
Nostr's bounty site (bountsr.com) is down

### ISSUE THREAD

**Issue by Pranoy1c** [nostr-protocol/nips#586]
Not sure if this is the right place to report this. If not, please close this.

https://nostr.com/contribute

tells people to contribute to:

https://bountsr.com/

The bounty site is down.

**Comment by BinaryIgor** [comment]
Exactly, who/what is responsible for it being alive?

**Comment by Pranoy1c** [comment]
> Exactly, who/what is responsible for it being alive?

Not sure. But considering Nostr's website tells people to contribute to it, they should know it.

**Comment by dfralan** [comment]
You mean

https://bountsr.org/relay-based-design/

?

**Comment by BinaryIgor** [comment]
Hmm, so basically url should be (on the nostr.com website):
`https://bountsr.org`
But is
`https://bountsr.com`.

@dfralan Do you know where is the repo for https://nostr.com, so we can fix it?

**Comment by dfralan** [comment]
Domain owner is @arcbtc but there is not public repo. I already reached it.
