### ISSUE TITLE
stronger wording for NIP-09

### ISSUE THREAD

**Issue by khimaros** [nostr-protocol/nips#61]
currently the NIP is worded:

> Relays MAY delete or stop publishing any referenced events that have an identical pubkey as the deletion request. Clients may hide or otherwise indicate a deletion status for referenced events.

i think it would be better to upgrade both of these (`MAY` and `may`) to `SHOULD`. setting the standard for default behavior with deletions can set the norm for future clients.

ephemerality is a killer feature for decentralized social network and can have a substantial psychological impact on peoples' willingness to post content to the network.

**Comment by fiatjaf** [comment]
That's fine. Can you send a PR changing that?

**Comment by blakejakopovic** [comment]
Just for clarity, perhaps update NIP-09 further such that a relay SHOULD continue to publish/share the deletion events, as clients may already have the event that's intended to be deleted - so clients still need to receive the deletion events so they can update accordingly.

**Comment by jb55** [comment]
On Thu, Nov 10, 2022 at 06:44:49AM -0800, Blake Jakopovic wrote:
>Just for clarity, perhaps update NIP-09 further such that a relay SHOULD continue to publish/share the deletion events, as clients may already have the event that's intended to be deleted - so clients still need to receive the deletion events so they can update accordingly.

Clients definitely need the deletion event. They probably should also broadcast deletion events to other relays that don't have it.
