### ISSUE TITLE
NIP-33: What should a relay do if it missed the original event and receives a parameterized replaceable event?

### ISSUE THREAD

**Issue by Pranoy1c** [nostr-protocol/nips#614]
NIP-33 says:

> "Upon a parameterized replaceable event with a newer timestamp than the currently known latest replaceable event with the same kind, author and first d tag value being received, the old event SHOULD be discarded, effectively replacing what gets returned when querying for author:kind:d-tag tuples."

https://github.com/nostr-protocol/nips/blob/master/33.md

Since relays are not expected to have all the events, lets say the relay receives this new parameterized replaceable event for which it doesn't have the original event. So it has no way of confirming whether the combo of the kind, author and first d tag are correct.

1. What is the relay supposed to do?
2. Lets say the relay stores this new event. Wouldn't this allow Bob to be able to replace Amy's events on all relays which don't have Amy's original events by Bob simply including Amy's original event's d tag?

**Comment by staab** [comment]
PREs are namespaced by pubkey, so no one can replace someone else's event. IOW, two people can publish different replaceable events with the same `d` without any conflict. If the relay missed the first event, the second is essentially a PUT, so there's not conflict there either.
