### ISSUE TITLE
Extending kind:0 - Mark bots.

### ISSUE THREAD

**Issue by IngwiePhoenix** [nostr-protocol/nips#624]
Hello there!

This is a very, very short proposal/request. In the past week or so, I have gotten replies by accounts that I suspect to be AIs/Bots (possibly self-hosted LLMs or OpenAI API clients) like Cyborg or NakomotoX and potentially one or two more.

Since bots are helpful but still automated, I would like to request an extension to the metadata set with `kind:0` to indicate a bot.

In [this section](https://open.spotify.com/intl-de/track/3PVOtxnl44LA8cIq9nkbxO?si=9045c50691a44c26), I would like to extend the metadata by a very simple bool.

For instance:

```json
{
  name: <username>, 
  about: <string>, 
  picture: <url, string>,
  bot: <bool>
}
```

This could then very easily be used by clients when displaying profiles to tell if an account is a bot - or AI - or not.

It is backwards compatible as the field does nothing but add information, whilst it is also voluntary.

Thoughts on this?

Kind regards,
Ingwie

**Comment by alexgleason** [comment]
Seems fine to me. Mastodon lets users self-indicate whether they are a bot.

**Comment by melvincarvalho** [comment]
@alexgleason how's it done in mastodon these days?  Since forever in linked data it's been `@type : Person` or `@type = Agent`, which comes from FOAF

**Comment by alexgleason** [comment]
I believe a bot has actor type `Service` in ActivityPub, but in the Mastodon API it's just a boolean `bot` field.

**Comment by melvincarvalho** [comment]
@alexgleason good to know!  @type is a bit more fundamental than any field.  So bot = true could work well.  And in the not so distant future we'll have online presences which may be part human, part bot.  So it could be a useful toggle, in any case.  Good to align terms with anything existing...

**Comment by decentropy** [comment]
All events have tags, per NIP-01, including kind 0

I use g-tags on kind 0.
I wonder when kind 0 should use tags vs content.

In this case (a boolean), tag seems more appropriate

**Comment by basantagoswami** [comment]
We probably also need to be able to indicate whether a profile is a brand profile.

**Comment by SilberWitch** [comment]
I have the same issue, but for RSS-feedbots/newsbots.
