### ISSUE TITLE
Why event's "created_at" is not in milliseconds ?

### ISSUE THREAD

**Issue by shanelau** [nostr-protocol/nips#626]
When I send multiple messages within 1 second, it is possible for the recipient's message order to be disrupted.

Why not change it to milliseconds?

NIP01
```
{
  "id": <32-bytes lowercase hex-encoded sha256 of the serialized event data>,
  "pubkey": <32-bytes lowercase hex-encoded public key of the event creator>,
  "created_at": <unix timestamp in seconds>,
```

**Comment by fiatjaf** [comment]
Because that would be a breaking change.

Also no human can write more than one message per second and if you're doing that you're clearly an automated spammer that no one should be following.

**Comment by shanelau** [comment]
It makes sense. However, it is not user-friendly for some automation programs.
