### ISSUE TITLE
Bounds for kind values

### ISSUE THREAD

**Issue by Semisol** [nostr-protocol/nips#636]
We should probably ensure kinds are positive -- but what would be the size of the kind value? 32 bits signed? 53 bits unsigned?

**Comment by jb55** [comment]
is anyone using negative kinds?

**Comment by pqingshuang** [comment]
if not, someone will after semisol bring this up

**Comment by fiatjaf** [comment]
32 bits unsigned.

**Comment by scsibug** [comment]
For reference, nostr-rs-relay uses a 64 bit unsigned integer.

Negative kind values do not seem to solve any problem.

**Comment by mikedilger** [comment]
I used 64-bit unsigned for a while because I didn't know, but then I found something somewhere (maybe the TLV values?) that taught me that it was 32-bit unsigned and I updated all my code.

**Comment by fiatjaf** [comment]
We'll never get anywhere near that. Also many JSON parsers break with anything above a 32-bit signed integer.
