### ISSUE TITLE
Sensitive content

### ISSUE THREAD

**Issue by fernandolguevara** [nostr-protocol/nips#64]
Would be nice to have a tag to mark content as sensitive like mastodon 

<img width="585" alt="image" src="https://user-images.githubusercontent.com/969516/201350421-2159020d-2a57-4031-aa28-6a1295b26e2d.png">

**Comment by jb55** [comment]
Perhaps just a tag: `content-warning` where the second array value is nothing or `nsfw`, `politics` etc.

This would cover the entire post.

**Comment by eskema** [comment]
how about just put "t":"nsfw" and deal with that?

**Comment by jb55** [comment]
that is not the same thing, that is a hashtag. you might not want to post to be searchable on that hashtag.

**Comment by fernandolguevara** [comment]
@jb55 I like the idea to add a new tag to reflect this new feature 


`Example:`

```json
{
    "pubkey": "<pub-key>",
    "created_at": 1000000000,
    "kind": 1,
    "tags": [
      ["t", "hastag"],
      ["cw", "reason"] /* reason is optional, do we need to have a char limit? */
    ],
    "content": "sensitive content with #hastag\n",
    "id": "<event-id>"
  },
```

**Comment by jb55** [comment]
@fernandolguevara we should just stick to something longer in case we want to expand indexing from single-char tags to double-char. This field doesn't need to be indexed.

**Comment by fernandolguevara** [comment]
@jb55 edited 🙌🏼

**Comment by Cameri** [comment]
I like this!
