### ISSUE TITLE
Proof-of-work with NIP-07 is a bit awkward

### ISSUE THREAD

**Issue by alexgleason** [nostr-protocol/nips#651]
Or with any remote signer (eg NIP-46) for that matter. NIP-13 needs the event to be signed before you can tell if it passed the POW check or not. So you either need to configure the signer app/extension to sign automatically, or you need to manually click "I approve" repeatedly to let it keep signing things until it passes the POW requirement.

**Comment by ondra-novak** [comment]
You can compute hash without signing the event. This can be done without signer.

**Comment by alexgleason** [comment]
@ondra-novak Genius. :exploding_head: And obvious now that you mention it! Glad I asked.
