### ISSUE TITLE
PRE sort order problem

### ISSUE THREAD

**Issue by arthurfranca** [nostr-protocol/nips#663]
Nostr sort things by latest `created_at`.
Editing a parameterized replaceable event (PRE) refreshes the `created_at` value.

This is alright for some use cases like "github issues", where may be desirable to place updated issues on top.
For other cases like NIP-51 lists it doesn't matter much.

However, for many use cases like NIP-23 (blog posts) and [classifieds PR](https://github.com/nostr-protocol/nips/pull/662), where the client most likely won't fetch just events from user's friends, this attribute presents a problem: PRE authors are incentivized to edit the PRE to make the event go to the top of the list/feed.

[NIP-34 - Algorithmic Filters](https://github.com/nostr-protocol/nips/pull/579) may one day help with sorting by a specifc score (which many relays may not implement). But it doesn't change the fact that the default sort order is broken for some PRE kinds. Custom sorting client side is impossible for the mentioned use cases because of the number of events, thus we need relays help.

What should we do?

I propose a new kind range 40000 <= n < 50000 that works like PREs but with extra rules **enforced by relays**. Basically these events commit to the first `created_at` value by prefixing the `d` tag with that.  More details [here](https://github.com/arthurfranca/nips/blob/social-notes/99.md#publication-date) which is part of the [Editable Social Note draft PR](https://github.com/nostr-protocol/nips/pull/659) (although there I haven't used a kind in that range, which is bad because would need relays to add custom validation for specific kinds as new NIPs get created instead of for a well-defined range of kinds).

Then maybe we move NIP-23 to that range. Thoughts?

**Comment by alexgleason** [comment]
This is an issue for clients to solve, I think. Clients should keep an index of eventId to naddr. When the new event matches an existing index, update it in your own cache and potentially don't display it in a feed.

It is actually a *benefit* that event updates have a new timestamp and gets returned by filters, as it makes it more likely clients will see the update.

Also, I think you should be able to query past versions of parameterized replaceable events for things like edit history, and to make consolidating them on the client easier.

**Comment by arthurfranca** [comment]
A cache to not show again an already seen event is useful to dedupe a feed and show only things you haven't read yet.

But imagine a list of PRE news articles about things happening in your city that is expected to be sorted by latest publication date. You saw some items like 20 and the client cached them like you said.

Later you refresh the page. Now you see one "new" article that wasn't there and also not on you cache. The author added a `["published_at", <now>]` tag equal to the `created_at` field to look like a fresh item. It seems new so you get interested and click it. The content unfortunatelly is about something old you already knew... then at the end of the content you notice it carries comments and likes from a week ago, revealing it is an stale article.

Better than relying on a local cache is the relay really sorting by publication date before sending to your client. As it is right now, the relay is sorting by the update date, which can be gamed, like the author can update the event as many times as he wants.

> It is actually a benefit that event updates have a new timestamp and gets returned by filters, as it makes it more likely clients will see the update.

Your client would still receive new event versions, but only if searching in the right date range that includes the date the first version of the event was created.

**Comment by alexgleason** [comment]
@arthurfranca If we made relays send all versions of the event for the D tag, it would be easy to recreate the index if we don't already have one.

**Comment by arthurfranca** [comment]
> If we made relays send all versions of the event for the D tag

A relay with no NIP-33 support is exactly that. Or a d tag used on a non PRE (but if replies etc used `a` tag for referencing).

**Comment by alexgleason** [comment]
Good point. Now what? 🤣

**Comment by arthurfranca** [comment]
> No matter what you do, someone can repost the same article as a new event over and over to keep it fresh

@mikedilger Yes but I think you miss an important aspect. Currently if you post a new kind 1 with duplicate content you will lose all you replies, reaction and zap counts linked to the first post (as they arent carried to the new post) and can end up being blocked/muted/unfollowed for spam if you do this too frequently, losing reach and relevance. So such behavior is discouraged. You can use Reposts, but it won't mess with the kind 1 sort order.

With PREs it is the opposite. When you edit a PRE, you keep your replies/reactions/zap counts and may pretend you were doing a valid innocent edit.. that will push you to the top of the feed. So there is an incentive to fake PRE edits.

**Comment by arthurfranca** [comment]
@alexgleason we can't rely on previous versions of PREs because relays most likely wouldn't keep old versions (atleast not all versions) so to save disk space. Also maybe they never had the initial version of an event because it may have been initially posted just to another relay, or the relay was down at the time.

**Comment by fiatjaf** [comment]
People can also publish kind1 notes with dates in the future so they stay at the top of everybody's feeds for a long time.

**Comment by alexgleason** [comment]
This is just making me want parametrized events that aren't replaceable. I wonder how many relays just index the "d" tag no matter what, irrespective of the kind range.

**Comment by arthurfranca** [comment]
@fiatjaf this can be avoided using the until filter `["REQ", '<subid>', { kinds: [1], until: Math.floor(Date.now / 1000) }]`.

But talking about kind 30023, your NIP, I just checked habla.news and the first blog post is from Apr 12 (it isn't lying the "published_at" tag because there are kind 1 comments from the same date) but it was edited today at 14 jul. That's the problem.

The problem is you keep all your article references (comments/likes/zaps), so you lose nothing if faking edits just to go to the top.

**Comment by arthurfranca** [comment]
Closing it and trying to fix the problem (if others acknowledge there is really a probelm xd) by creating [this PR](https://github.com/nostr-protocol/nips/pull/671).
