### ISSUE TITLE
nostr icon

### ISSUE THREAD

**Issue by mikedilger** [nostr-protocol/nips#68]
This is a rather trivial request, and has no effect on the protocol.

But is there a nostr icon?  For client developers who plug into multiple back ends (twitter, facebook, ..., nostr), it would be nice to use an icon next to each post indicating what network it came from.

**Comment by fiatjaf** [comment]
There is none right now, except the emblematic icon you see up there, which was a random screenshot of a part of my screen just to have anything.

I don't think we should have an "official" icon, but anyone is free to create icons and if some of them are very good probably everybody else will start using them too.
