### ISSUE TITLE
NIP-36 (content warning) should require specific tag

### ISSUE THREAD

**Issue by decentropy** [nostr-protocol/nips#687]
Correct me if I'm wrong, but relays don't support wildcard tag search, e.g. ["content-warning": "*"]
NIP-36 says the only requirement is to tag ["content-warning": "reason(optional)"]... which is unsearchable.

To allow a client to search for content-warning, there should be a specific tag required.
I suggest NIP is updated to require  ["l", "content-warning"] or something similar

**Comment by alexgleason** [comment]
>To allow a client to search for content-warning 

Why?

Also, shouldn't NIP-50 search just also search content warning text?

**Comment by decentropy** [comment]
Why... I'm trying to build an advanced search for all kinds, tags.
I just got stuck on that case as an unsearchable one.

Not a huge deal obviously, but I thought it'd be minor change to make those posts searchable.
Can text search (NIP 50) do that? Ok... I thought it was only for content.

**Comment by mikedilger** [comment]
Only single-letter tags are searchable. You'll find many tags that aren't searchable.  "content-warning" is just the beginning of the lot (subject, summary, title, description... all readable tags).  The problem is that if we make every tag searchable, relays will have to index every tag and that can be expensive in both time and space.  So NIP-50 SEARCH seems like the better way to go for tags that contain readable content and aren't single-letter.

**Comment by decentropy** [comment]
I see thanks for the insights @mikedilger 

I'll close

**Comment by staab** [comment]
@decentropy as a side note, I looked at fixing this as part of #532 but didn't update it for backwards-compatibility. If you'd like to classify things for content warning in a more disciplined manner, you might look at NIP 32.

**Comment by decentropy** [comment]
@staab ... I was only thinking search/query flexibility.

if only 1-letter tags are indexed (per mike), good to use where possible. tags like "subject", 'millisats" and variable so can't be searchable... but tags that flag yes/no, or even predictable sets like a status, protocol could be indexed for potential search. or like you said, maybe L tag is best approach in general
