### ISSUE TITLE
proposal for "edit" notes (from jb55)

### ISSUE THREAD

**Issue by khimaros** [nostr-protocol/nips#69]
the following was posted at by @jb55 at [here](https://nostr.com/e/baabedf905ab83cb7b8325e7c6d1a591ee9fabf8dc67b2b1e87e6db7b6af424d). creating this issues so that it can be discussed and potentially incorporated as a NIP. mutability is important and frequently overlooked in the world of alternative social networks. quoted content follows:

> It would be cool if there was a way to edit notes. Basic idea: a note is created with the following tags:
>
```json
{"tags": [["e","thread_id"],["e","note_id","","edit"]]}
```
>
> Where `note_id` is the note you are editing. Clients can replace the note with the most recent one it sees. It is able to fetch all edit notes because of the thread_id reference.
>
> For clients that don't support this, it will look like a regular reply.

**Comment by fiatjaf** [comment]
Yes, this looks good. Also since you know what you're editing you can prevent overwriting stuff that you didn't happen to be seeing at any given time. Reminds me of CouchDB.

**Comment by mikedilger** [comment]
NIP should require relays must reject edits to events with different public keys.

Clients can allow drilling through to the original, especially as replies to the original might not make sense as replies to the edit.

**Comment by jb55** [comment]
This is a really old post, I prefer having a new note kind for handling edits, and I'm not sure if having duplicate replies is a good thing.

**Comment by fiatjaf** [comment]
A new note kind is indeed better.
