### ISSUE TITLE
NIP-05: gnupg standards compliance

### ISSUE THREAD

**Issue by RandyMcMillan** [nostr-protocol/nips#7]
There is a poorly documented gnupg dns standard that will work great as a guide for a nostr standard. I am working on some documentation that I will add to NIP-05. By complying with the gnupg dns standard - nostr will not have to reinvent this wheel and refactoring a python/other dns lib should be trivial.

PR to follow.

**Comment by RandyMcMillan** [comment]
pgp_dns guide:

https://github.com/RandyMcMillan/pgp.guide/blob/master/source/pgp_dns.md

nostr implementation: tbd

**Comment by fiatjaf** [comment]
But what do we gain by not reinventing the wheel?
