### ISSUE TITLE
User discovery

### ISSUE THREAD

**Issue by mikedilger** [nostr-protocol/nips#70]
NIP-05 is about user verification but it is also halfway useful for user discovery.

With many relays, only some of them carrying a user's events, full user discovery would suggest putting user relays in the nostr.json file along with a public key.

In such a case, a user could subscribe to "bob@bob.com" with a client that knows none of the current relays, find his public key and relays and have at it.

I'm less opinionated about how to structure nostr.json to do this, but it ought to be backwards compatible. Something like this might work

````javascript
{
  "names": {
    "bob": "b0635d6a9851d3aed0cd6c495b282167acf761729078d975fc341b22650b07b9"
  },
  "relays' {
    "b0635d6a9851d3aed0cd6c495b282167acf761729078d975fc341b22650b07b9": [ "wss://relay.damus.io", "wss://nostr-pub.wellorder.net" ]
  },
}
````

**Comment by fiatjaf** [comment]
I support this idea. User discovery is a multifaceted beast and we can use multiple means to attack it. This can be one of them.

Are you planning on implementing this somewhere @mikedilger?

**Comment by mikedilger** [comment]
I'm planning to write a desktop client using https://tauri.app/.  But this is very early days and I have a day job doing something else so it could be a while (or maybe I'll knock it out over the weekend, who knows).

**Comment by mikedilger** [comment]
In the future, clients following many people on many relays may find the fan-out to be a scaling bottleneck.  In such a case, the practical solution is that people may want to list several authoritative relays (maybe that they control, so as to not be censored) and several popular aggregation relays (so clients don't have to connect to everybody's authoritative relay).

In such a case, and perhaps in other cases I'm not thinking about as well, the nostr.json file might want to associate additional information with the relays. So perhaps the structure should allow for that somehow... although I'm not quite sure which way would be best.

**Comment by fiatjaf** [comment]
[NIP-35 addresses this issue.
](https://github.com/nostr-protocol/nips/pull/73)

Future concerns related to extra information associated with the relays can be solved by dirty hacks in the future when the need arises.
