### ISSUE TITLE
NIP-XX Account kill switch 

### ISSUE THREAD

**Issue by dipunm** [nostr-protocol/nips#710]
See thread: nostr:nevent1qqsw857ytntsxtvth6h6gmxp9ywk8f3wfn4wgkdkvagjmhslk40yq8cpz3mhxue69uhhyetvv9ujumn0wd68ytnzvupzq0clvy0tl9gk9ksguumeth0m6w3whljm8mwqf9f4vqe2707j2x4zqvzqqqqqqyudq5zy

The idea here is to prevent abuse of a compromised nostr account that already has followers.

Of course a user could send out warnings and notes to people telling their followers that their account has been compromised and to follow another account, however notes like this can be deleted and worse still, a similar note can be created that suggests a malicious account is the new official account.

Using NIP-05 can help to alert followers that an account may have been compromised, however once you follow someone, you tend to trust your follow list more than NIP-05 identifiers. At least for some time.

I propose a new event type that marks a given npub as compromised. The event must be signed by the accounts own private key, indicating that either the owner has created this message, or the account has indeed been compromised and someone else has signed this message on their behalf with the compromised key.

This event type should not be deletable. Similarly to NIP-09, where deletions can't be deleted, nor can an event that declares an account compromised.

The event MUST NOT suggest which account supersedes this one. This would be subject to confusion and/or malicious signalling to the accounts followers.

A timestamp may be included, relays can choose to reject the event if the timestamps is very old when it comes their way. A timestamp can give an indication of what events were honest, but it is only an indication. Relays should not support replacing this event if a duplicate with a newer timestamp is later broadcast.

Clients MAY add a compromised label or icon to a compromised account and its posts.

Relays MAY choose to ignore or reject anything from an account that has this event.

Relays MAY use an internal blocklist database to improve performance if they choose to ignore or reject future posts by blocked accounts.

This was my best attempt at a NIP, but I would appreciate people's eyes, ideas, comments and some help writing it in a format that can be turned into a real NIP.

**Comment by fiatjaf** [comment]
See https://github.com/nostr-protocol/nips/pull/637

**Comment by dipunm** [comment]
Closed as duplicate.
