### ISSUE TITLE
NIP57, Doubt on passing the invoice to an app that can pay it.

### ISSUE THREAD

**Issue by AaruBama** [nostr-protocol/nips#729]
https://github.com/nostr-protocol/nips/blob/2f84cd97e38c0a824cc27ea2ac976545e9e3f09e/57.md?plain=1#L21C4-L22C1

Great documentation on entire nostr-protocol. A newbie like me was able to create a pr invoice to allow my users to send sats.
I'm however unsure about this.

I've a `lnbc` invoice that can be paid. I am able to pay it by copying from the variable and pasting it in my wallet. However I'd want to achieve something like damus or any other app on nostr where the invoice is automatically sent to an app that can pay it.

How can this be achieved?

**Comment by jb55** [comment]
On Sat, Aug 19, 2023 at 02:06:01AM -0700, AaruBama wrote:
>https://github.com/nostr-protocol/nips/blob/2f84cd97e38c0a824cc27ea2ac976545e9e3f09e/57.md?plain=1#L21C4-L22C1
>
>Great documentation on entire nostr-protocol. A newbie like me was able to create a pr invoice to allow my users to send sats.
>I'm however unsure about this.
>
>I've a `lnbc` invoice that can be paid. I am able to pay it by copying from the variable and pasting it in my wallet. However I'd want to achieve something like damus or any other app on nostr where the invoice is automatically sent to an app that can pay it.
>
>How can this be achieved?

make it a clickable uri: lightning:lnbc..

or if you want to do it programatically see https://github.com/nostr-protocol/nips/blob/master/47.md

**Comment by AaruBama** [comment]
I did it programatically. making it a URI solved it. Thanks. :)
