### ISSUE TITLE
there are only 10,000 3xxxx kinds

### ISSUE THREAD

**Issue by melvincarvalho** [nostr-protocol/nips#789]
There are only 10,000 3xxxx kinds

If nostr becomes very popular, we could run out of 3xxxx kinds

Perhaps it is an idea to reserve one obscure number : 37152

Then the d tag could be sub divided

1_<tag>
2_<tag>
...

for different apps that register with the tag.

**Comment by vitorpamplona** [comment]
We can use also another range: 100,000 to 1,000,000. :)

**Comment by melvincarvalho** [comment]
ok that works, i guess 3xxxxx would be best, but then relays need to change processing

**Comment by vitorpamplona** [comment]
Maybe by then we are going to instruct them to keep previous versions so we have a full history of changes :)

**Comment by alexgleason** [comment]
Isn't that just NIP-78? https://github.com/nostr-protocol/nips/blob/master/78.md

**Comment by melvincarvalho** [comment]
> Isn't that just NIP-78? https://github.com/nostr-protocol/nips/blob/master/78.md

Hmm in a way.  But then you've used up the `d` tag and it's more like a 1xxxx event?

I guess d could be sub divided in 30078.  There seems many solutions here, and maybe im worrying over nothing.

**Comment by fiatjaf** [comment]
Kinds are only useful when we can agree on a standard use for them, like how it's being done currently in the NIPs repo, and that requires human work and conversations. It's hard for me to imagine so many kinds being used without that process breaking down such that kinds are not meaningful anymore.
