### ISSUE TITLE
NIP-65 Temporarily omit a relay

### ISSUE THREAD

**Issue by SnowCait** [nostr-protocol/nips#805]
## Cases

- Mobile network while moving from Wi-Fi network
- Checking relays which may not work well

## Suggestion

Allow `none` to 3rd element in [NIP-65](https://github.com/nostr-protocol/nips/blob/master/65.md).

Example (example-c.com)
```
kind: 10002,
tags: [
  ["r", "wss://example-a.com/"],
  ["r", "wss://example-b.com/", "read"],
  ["r", "wss://example-c.com/", "none"]
]
```

It might be okay to use empty string instead of `none` but it may be confused with undefined in some language.

**Comment by fiatjaf** [comment]
Shouldn't the app handle these internally? There is probably no need to broadcast such temporary changes.

**Comment by SnowCait** [comment]
Outbox-model writes to the other read relays.
Therefore client must remove the ommited relay tag from kind 10002 in these cases.
However, client must implement another logic to keep the ommited relay. That is not simple.

**Comment by vitorpamplona** [comment]
NIP65 is designed to let OTHERS know which relays to use when looking for your posts or writing to you. 

This NIP is not that effective as a way to store your own relay configurations. You will need a lot more freedom to manage all the state a client must manage. Maybe we need another NIP or just keep it local like everyone else does (most of these settings are client-based and thus they are not super useful to other clients).

**Comment by mattn** [comment]
So how about extra attributes like `"mobile"` ?

```
kind: 10002,
tags: [
  ["r", "wss://example-a.com/"],
  ["r", "wss://example-b.com/", "read", "mobile"],
  ["r", "wss://example-c.com/", "write", "mobile"]
]
```

**Comment by SnowCait** [comment]
@vitorpamplona 
I agree with you. Another NIP (or redesigning NIP-65) is needed to be more flexible.

To digress a little.
Outbox-model (kind 10002) has some issues in my understanding.
- Cannot support mutiple environment. (like this issue)
- Subscribing all followees's write relays consumes gigantic traffic.

**Comment by SnowCait** [comment]
@mattn 
Looks good for me but we must also think about 3rd element doesn't exist like example-a.com.

**Comment by vitorpamplona** [comment]
> - Subscribing all followees's write relays consumes gigantic traffic.

Gotta be smart about it. Blindly subscribing to every write relay won't work well.

**Comment by AsaiToshiya** [comment]
> @vitorpamplona I agree with you. Another NIP (or redesigning NIP-65) is needed to be more flexible.

Would not be possible to use the [relay set](https://github.com/nostr-protocol/nips/pull/786)?

**Comment by vitorpamplona** [comment]
Yep, you can have multiple relay sets split in any way you want: per location, per client, per working group, etc.

**Comment by SnowCait** [comment]
Looks good for me but it will not work well to share between clients without d-tag rules.

**Comment by vitorpamplona** [comment]
Frankly, clients are so different that I am not sure if the expectation of making it work for other clients make any sense. 

We can start using it and then if a common set of d tags emerge, we can add them to the nip.

**Comment by fabianfabian** [comment]
As far as I understand NIP-65 it seems great in case censorship becomes a problem, you will always be able to find someones posts because they control where they are available in 10002 and can easily update it if a relay starts censoring.

I don't understand how adding "wifi" or "mobile" helps any of this, maybe I'm getting NIP-65 wrong.

**Comment by mikedilger** [comment]
I don't understand these example cases.  If I switch from wifi to mobile, why would I change which relays I post to?  This doesn't make any sense to me.  And if one of my write relays isn't working well at the moment, oh well, that's why I use more than one, for redundancy.  And even if I did switch relays, all my old messages are on the other relays... would I want those messages to no longer be accessible?

I see switching relays to be a rare thing, a longterm thing, not a dynamic quick-fire thing.  I can imagine clients dynamically changing relays often and copying all their events to their new relays as they change... but I don't see much benefit to it.

Gossip client presumes people don't update their nip-65 very often. It checks every 8 hours, by default, for relay list changes.

**Comment by AsaiToshiya** [comment]
> If I switch from wifi to mobile, why would I change which relays I post to?

I think, for example, that saving data usage by switching to relays such as relayable.org.

**Comment by fabianfabian** [comment]
> > If I switch from wifi to mobile, why would I change which relays I post to?
> 
> I think, for example, that saving data usage by switching to relays such as relayable.org.

`kind:10002` is supposed to be spread to many relays, I don't think its useful to pollute it with local settings.

**Comment by SnowCait** [comment]
Do you mean outbox-model should write to all read relays and subscribe all read relays?
Clients which write to a part of read relays may write to only temporarily ommited relay if it is not reflect latest relay information.
It might be outbox-model issue but I think some way is needed to avoid that. (I don't mind if the way is not my suggestion.)

**Comment by mikedilger** [comment]
I recognize that there is a problem:  relays may be down.  I don't think changing kind-10002 solves that problem.  What if I post to 6 relays, they are all working fine, then 2 go down, and I didn't know about it so I can't change my kind-10002?  And what if someone following me looks only at the 2 that are down?

I don't know what the right answer is, but considering that websites and RSS have only ONE server, and don't have any failover solution to a different DNS address, then it seems we shoudn't have to solve this problem this way.  Relays should just be more stable.

**Comment by fiatjaf** [comment]
What I don't get from this PR is that it seems to be assuming that temporary choices made in the context of a client and valid only for the next 5 minutes should be immediately reflected in a kind:10002 event being broadcasted to the entire world.

That's not how it should be. In fact, a client should be able to make decisions locally to not read from some relay that is in the list or to write to another relay that isn't in the list and so on -- and that doesn't mean at all that these decisions must be published for everybody else immediately.

**Comment by SnowCait** [comment]
Nostr relies on relays. Which relay I should read from/write to is important to especially SNS client, I think.
The hint is only kind 10002. (at least now)

>fact, a client should be able to make decisions locally to not read from some relay that is in the list or to write to another relay that isn't in the list and so on

This is right and this decisions will not be published. I agree with it.
But the decisions will be decided by some hints, not random.
One of hints is kind 10002.

When someone mentions to me, they will write kind 1 to one/some/all of my read relays in kind 10002.
I'd like to omit a relay from kind 10002 while I can't receive from it by some reason. (even if it is 5 minutes)
That reduces risk of missing.

**Comment by SnowCait** [comment]
However, my suggestion might not be good for reading old events as @mikedilger said. (Clients can read from also `none` relay but I don't want to change existing rule.)
Closing this issue and I consider more better way.
