### ISSUE TITLE
A section for nostr clients and their supported NIPs

### ISSUE THREAD

**Issue by heanzyzabala** [nostr-protocol/nips#807]
Do we have a list of nostr clients where we can see which NIPs they're supporting? 

Something similar with LUDs where lightning wallets are collated with their respective implemented LUDs: https://github.com/lnurl/luds#lnurl-documents

**Comment by AsaiToshiya** [comment]
Please see the awesome-nostr: https://github.com/aljazceru/awesome-nostr#client-reviews-andor-comparisons

**Comment by badonyx** [comment]
https://nostorg.github.io/clients/

**Comment by heanzyzabala** [comment]
Thanks!

**Comment by heanzyzabala** [comment]
Thanks!
