### ISSUE TITLE
NIP-19 using bech32 limited to 90 chars

### ISSUE THREAD

**Issue by FreeTrade** [nostr-protocol/nips#816]
I was parsing an nprofile and got an 'Exceeds length limit' error.

I dug into bech32 - seems like it has a limit of 90 chars. ref
https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki

A Bech32[[2](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#cite_note-2)] string is at most 90 characters long and consists of:

Is that long enough to hold all the info required by NIP-19?

**Comment by fiatjaf** [comment]
Some bech32 libraries have this limit hardcoded in them, but you can opt to remove it.

**Comment by FreeTrade** [comment]
Guess I need to use a different lib. Thanks!

**Comment by fiatjaf** [comment]
What library are you using? `@scure/base` has this option and it's very good.
