### ISSUE TITLE
NIP5: Add some field for specifying the kind of direct message 

### ISSUE THREAD

**Issue by arejula27** [nostr-protocol/nips#83]
The direct message is a way to intereact with other person, however it could be in many ways: direct chat, mail or whatever u want. I think it would be appropiated to add a field for specifying the kind o encrypted message it is, so if you are building a chat app u can filter this kind of message or if you are doing a mail app (my case) you can filter them.

**Comment by arejula27** [comment]
Another option could be separate them on different event kinds, i dont think it is the best option because both are the same event (encrypted for 2 people), the only difference is the type of communication it is, one more instantaneous and other more polite.

**Comment by arejula27** [comment]
In my opinion with a tag will be enough, however i wrote this issue for discuss a standardized tag, so every app could use it, not only mine.

**Comment by eskema** [comment]
I don't underestand what you're trying to do, is this to know what is the user preferred way to get contacted? like kind-1 vs kind-4?

**Comment by arejula27** [comment]
The idea is to specify the structure of the content, it could be a simple sentence or a JSON {title:string, text:string} or whatever the client prefer. So with this tag the clients would decode correctly.

**Comment by arejula27** [comment]
Maybe my explanation was terrible at the begining :\

**Comment by eskema** [comment]
encodings and structures are better suited for specific kinds, otherwise you pollute clients with unreadable data where it shouldn't. If you want a specific format, you write a new kind for it and use that instead of forcing clients to use your own.

**Comment by arejula27** [comment]
Okay, how i select a new number? I will write a pr then

**Comment by eskema** [comment]
write the nip without a number, the number will reveal itself after
