### ISSUE TITLE
Question about parameterized replaceable events (NIP-33 merged with NIP-01?)

### ISSUE THREAD

**Issue by mattsats** [nostr-protocol/nips#834]
In the old NIP-33, it specifies that events 30000 <= kind < 40000 that have 
`tags=[["d", "my_identifier"]]`
be parameterized  replaceable events. 

In the new NIP-01 (subheading Tags), it specifies that these events have
`tags=[["a", "kind:pubkey:my_identifier"]]`

But in same NIP-01 (subheading Kinds), it also specifies that also the "d" tag's first value.

Are parameterized replaceable events expected to have both "d" and "a" tags?

**Comment by vitorpamplona** [comment]
The event has a `d` tag. Any reference to that event uses an `a` tag.

**Comment by mattsats** [comment]
Oh, thanks!
