### ISSUE TITLE
nostr censorship

### ISSUE THREAD

**Issue by melvincarvalho** [nostr-protocol/nips#887]
Hi all

2nd contributor to nostr github here.  Some of you might know me.  I also run the Nostr reddit, admin nostr matrix, and chair the w3c nostr community group, along with many other things I run for the project, and folks I help generally. 

I've co-authored NIPs, run many web sites, created many projects on nostr, countless apps, run sites, run relays etc..  I helped get nostr integrated into alby, I have on-boarded dozens of developers, and I shitpost every day (Im not a vegan).  I've also supported it almost 24/7 for the last 3 years, all paid for by myself.  Indeed, I have donated to the project rather than getting anything back.

I'm concerned about heavy handed running of the protocol and github repo.  I went in to fix a typo in one of my comments, and I'm no longer able to do this:

![image](https://github.com/nostr-protocol/nips/assets/65864/c0ac37f4-5fe1-4818-83b9-39cba880d451)

Additionally I am no longer able to reply to issues:

![image](https://github.com/nostr-protocol/nips/assets/65864/055c4364-95de-4ed5-9e95-04e958e4890a)

Additionally views from zebedee are invisible to me, and I am unable to read them, or consider the response.

It's slightly concerning that a protocol that calls itself "censorship resistant" should impose such sanctions on a legit issue, where the there is a differing of opinion.  This is not only annoying, and gets in the way of, but creates a chilling effect across the project.

Instead of making a big thing about this, why dont we all agree to put the project first.  Let's a agree That we should have a shared area where we can listen to each other's views, without fear of censorship

And one person, one company, one VC, no matter how well meaning can represent the whole project.  Let's use this as an opportunity to do better.  Instead of solving the problem with censorship, let's embrace censorship resistance.  Instead of making problems worse with centralization, let's embrace decentralization and trust the community.  

Nostr has become more open in the last week, as many on the [project page](https://github.com/orgs/nostr-protocol/people) have opened their identities.  Much respect for that.  The project thanks all of you.  But it's time the project has a 2nd owner, and that centralized heavy handed techniques become forgotten as a thing of the past.  The world needs an alternative to all the centralized, censored, privacy invasive projects out there.  Let's fight to make nostr that project.

**Comment by jb55** [comment]
pretty concerning

**Comment by fiatjaf** [comment]
Oops, I didn't know that if I blocked you personally that would block you from the repository that doesn't even belong to my personal account. That's a GitHub bug. Fixed it now though.
