### ISSUE TITLE
NIP-XX: Addendums

### ISSUE THREAD

**Issue by AndrewDRX** [nostr-protocol/nips#903]
## Abstract

This NIP proposes a new event `kind` for tracking addendums to already signed events.

## Specification

An addendum event would be in the below format.

```json
{
  "content": <data relative to the type of this addendum, may be `null` if all data is contained w/in tags>,
  "id": <32-bytes lowercase hex-encoded sha256 of the serialized event data>,
  "kind": <integer for kind TBD>,
  "pubkey": <32-bytes lowercase hex-encoded public key of the event creator>,
  "sig": <64-bytes lowercase hex of the signature of the sha256 hash of the serialized event data, which is the same as the "id" field>,
  "tags": [
    ["e", <32-bytes lowercase hex of the id of event associated to this addendum>],
    ["type", <string for the type of this addendum>],
    ...
  ]
}
```

As noted, the `type` tag would be used for identifying the type of addendum being made. This could be such things as "content" or "context" or "timestamp".

Relays may store only addendum events that have a `type` tag relevant to the content that they provide.

Alternatively, instead of the `type` tag, the `alt` tag could be used if that is the preferred standard for designating "sub-kinds", similar to how it is used for `OpenTimestamp Attestations (NIP-03)`.

As noted, the `e` tag would be used to associate the addendum to an existing event. The associated event may be a prior addendum, or an event of any `kind`.

Addendums can be associated to events signed by any user, not just events that were signed by the user creating the addendum. So, users can add context to the posts of other users via an addendum.

## Possible Use Cases

Below are some examples of how an addendum event `kind:TBD` could be used.

1) A user could submit a change or addition to one of their signed events, in particular this may be useful for any non-replaceable event `kind`. For example, if a user wishes to make an edit to one of their existing notes of `kind:1`, then they could post an addendum pointing back to the parent event w/ a `type` tag of "content". Relays could optionally not display any edits made this way, or optionally display the event showing the content from the most recent addendum, or optionally display a link to view all addendums under a different context while primarily showing the original content.

2) Timestamp attestations other than those defined as `kind:1040` for `OpenTimestamp Attestation (NIP-03)` could be done by posting a timestamp as an addendum w/ the `type` tag of "timestamp". Multiple timestamp attesters could post timestamps in this way w/out being restricted to using OTS. This would allow for any IETF RFC-3161 compliant timestamp authority to act as an oracle for providing timestamp attestations for events of any `kind`.

3) A payment system could allow for addendums to provide tax-related context to a transaction, such as associating a transaction to a specific tax code. This could be done by the user who posted the transaction, or by an accountant reviewing the transactions of another user.

4) A met mast tower could post an initial event for a sensor upon setup, and then post an addendum with a sensor reading at each polling interval, or an addendum whenever the sensor is replaced or reconfigured. Similarly, an event could be posted to represent a shear calculation based on multiple sensors, and then addendums could be posted to calculate a shear whenever any of those sensors are polled, or post an addendum whenever any of those sensors are replaced or reconfigured.

5) Published research or journals could post an initial event for the published work. Then citations, sources or contributors could be posted as addendums. Peer-reviews or responses to peer-reviews could also be posted as addendums.

6) Whatever else since the use cases are intentionally broad. Some may find them useful for posting and tracking updates and additional context for existing events. Others may find them useful as a method to allow oracles or automated services to provide data for events.

**Comment by vitorpamplona** [comment]
Every event that e-tags another event is an Addendum :) 

There is no need to reduce them all to a single event kind.

**Comment by staab** [comment]
I second splitting use cases out into separate kinds. But addenda that clients can display in a privileged way are a good idea.

**Comment by AndrewDRX** [comment]
> Every event that e-tags another event is an Addendum :)
> 
> There is no need to reduce them all to a single event kind.

Those are event references, not necessarily addendums.

A relay would have no way to know which events to display or store or use if it was all of the same kind just using an e-tag, so it would clutter the datasource of a relay when querying any given event kind.

A designated addendum kind would all a relay to keep that data separated and not use it or store it if they don't want it.

**Comment by AndrewDRX** [comment]
> I second splitting use cases out into separate kinds. But addenda that clients can display in a privileged way are a good idea.

OK. I am working on a project to build a UTXO and smart contract model via the nostr protocol. This idea was a shortcut to trying to consolidate multiple `kind` values into a single generic event type.

I will nix this addendum idea and can instead get away with just two defined `kind` values for now; one for UTXO transactions and a second for oracle provider data. A new issue will be opened for that at some later date as an RFC. Stay tuned!

As for this issue, I will probably just leave it open until at least the end of the year in case anyone else stumbles upon this and wants to weigh in w/ their own arguments for such a generic event `kind` for sharing post-signature data, but will close it after a bit if there is no notable activity.
