### ISSUE TITLE
NIP 50 search term encoding

### ISSUE THREAD

**Issue by mleku** [nostr-protocol/nips#920]
Relating to this NIP:

https://github.com/nostr-protocol/nips/blob/master/50.md

From an implementation perspective, it lacks any specification of the allowable text within the string of the search key of the filter object.

I'm of the opinion that for this case, HTML (`%xXXXX`) or JSON Unicode entities (`\uXXXX`) should be used, I lean towards the latter, but for the complete set of symbols in order to allow less complex and faster marshal/unmarshal implementations. Essentially, to be able to guarantee that within a search term you won't find a `}` or `]` character, specifically, so that a parser can find the boundaries of these objects without having a second level of parsing to handle strings that may contain this.

**Comment by mikedilger** [comment]
JSON already has these escape sequences if you need a } or ] or " or indeed even a BEL or NUL inside of your string. Common ones like \t and uncommon ones like \u0000.  Nostr messages are JSON and so these escape sequences are already allowed.

**Comment by mleku** [comment]
Ok, so "any allowable JSON text". Implicit really. Thanks.

**Comment by mleku** [comment]
ok, implicit. many other types of fields have rules, like IDs, pubkeys, but others don't. I'm just thinking in terms of trying to dodge having to do quote state when scanning for close bracket/braces. Can't :D
