### ISSUE TITLE
The order of tags in follows/blocks/mutes/bookmarks/etc

### ISSUE THREAD

**Issue by alexgleason** [nostr-protocol/nips#958]
Should new tags be added to the end or the beginning?

```js
// Adding the new tag at the end:
const tags = [...event.tags, ["p", "123"]];

// Adding the new tag at the beginning:
const tags = [["p", "123"], ...event.tags];
```

I want to display newest items at the top in the UI. So it raises the question about the order of tags.

I don't care whether it's top or bottom, but we should standardize one or the other to avoid inconsistent behavior in clients. What is the most common way?

**Comment by vitorpamplona** [comment]
Bottom is probably people's first way of coding this without even thinking about the order, so I would go with that option.
