### ISSUE TITLE
Infinite stream of notes

### ISSUE THREAD

**Issue by ionextdebug** [nostr-protocol/nips#961]
`
ws.send(JSON.stringify([ 'REQ', "my random subscription", {
        "kind": 3,
        "tags": [
          ["p", "hex of pubkey", "wss relay server", "petname"]
        ],
        "content": ""
      }]))
`

The above code results into an infite stream of notes not related with sent request. Why?
- Bad practice on relay side
- Error in my request/code

I would like to understand, and if it is a bad practice on relay side, can you suggest a relay with best practices according to NIPs? I need a relay server to correctly test and understand the protocol patterns.

Thanks

**Comment by benthecarman** [comment]
your filter is wrong see: https://github.com/nostr-protocol/nips/blob/master/01.md#from-client-to-relay-sending-events-and-creating-subscriptions

looks like it should be something like
```json
{
 "kinds": [3],
 "#p": ["hex of pubkey"],
}
```

**Comment by nextdebug** [comment]
> your filter is wrong, the fields you put are not valid so the relay is parsing it as an empty `{}`, see: https://github.com/nostr-protocol/nips/blob/master/01.md#from-client-to-relay-sending-events-and-creating-subscriptions
> 
> looks like it should be something like
> 
> ```json
> {
>  "kinds": [3],
>  "#p": ["hex of pubkey"],
> }
> ```

According to (NIP-03)[https://github.com/nostr-protocol/nips/blob/master/03.md] I can use the syntax below:
```
{
  "kind": 1040
  "tags": [
    ["e", <event-id>, <relay-url>],
    ["alt", "opentimestamps attestation"]
  ],
  "content": <base64-encoded OTS file data>
}
```

Moreover the relay is streaming, then in anycase the relay implementation is wrong or creating a new dialect.

**Comment by benthecarman** [comment]
That is the event structure, not the filter.

**Comment by Giszmo** [comment]
As far as the nips are concerned, this behavior is not defined to be like OP described. This issue belongs to the relay that treated a non-standard query too broadly instead of returning an error.
