### ISSUE TITLE
What is the algorithm of id and how to calculate it using c or other languages

### ISSUE THREAD

**Issue by cjz0728** [nostr-protocol/nips#964]
What is the algorithm of id and how to calculate it using c or other languages

**Comment by Egge21M** [comment]
As described in NIP-01, `id` is the SHA256 hash of the serialized event.

**Comment by cjz0728** [comment]
I have used the sha256 algorithm for encryption elsewhere, but the results are inconsistent.
Original text:[0,"c902d195c2231573c591d18da17676f804145e14187211913c0e40fec4d374ca",1704362537,1,[["p","9be107b0d7218c67b4954ee3e6bd9e4dba06 ef937a93f684e42f730a0c3d053c"],["e","51ed7939a984edee863bfbb2e66fdc80436b000a8ddca442d83e6a2bf1636a95","wss://relay.noscription.org/","root"] ,["e","000004627b7eb9b3a0986d27ed5abaac049c6f5ede794d5f74181902a7d770e8","wss://relay.noscription.org/","reply"],["seq_witness","166967032","0x7fd8412d4 3b1608f819a4f521511bf6a1cf376d3e391f517773ecfc6764c171f"],["nonce","sx4xhfjiozh" ,"21"]],"{"p":"nrc-20","op":"mint","tick":"noss","amt":"10"}"]
, web page results: 2b55bd43a09241b0713a94af6cac638d51ce467ca68b9d46afa8df4dede1e3fe, sha256 results: 225F785C7FFBA56B8DB4AD44088C67782D8A7AD22D9098126F8B100688E9111B

**Comment by Egge21M** [comment]
That does not look like a valid event. Please read NIP-01 carefully and see what an event consists of.

The text you added looks like a tag array of some sorts and additionally it does not look like it complies with the spec.

**Comment by fiatjaf** [comment]
Try pasting the event you have in https://nak.nostr.com/ and compare the serialized string with what you're doing.

**Comment by vitorpamplona** [comment]
@cjz0728 the example you posted is missing escapes in the content part of the array (`"` become `\"`). Are you building this string by hand? I recommend building this array in native objects and then request a JSON library to create the string.

**Comment by jb55** [comment]
On Wed, Jan 03, 2024 at 11:10:24PM -0800, cjz0728 wrote:
>What is the algorithm of id and how to calculate it using c or other languages

if you want a C example I have one in nostril(1)

https://github.com/jb55/nostril/blob/8726ad3b15f10e5a09864bbef61f7a35d1d2f3d7/nostril.c#L175

https://github.com/jb55/nostril/blob/8726ad3b15f10e5a09864bbef61f7a35d1d2f3d7/nostril.c#L315

**Comment by AveragePythonEnjoyer29** [comment]
Here's how I calculate it in my python lib:
```py
    def compute_id(self) -> None:

        raw_serialized = json.dumps(
            obj=[
                0, 
                self.pubkey, 
                self.created_at, 
                self.kind, 
                self.tags, 
                self.content
            ],
            indent=None,
            separators=(",", ":")
        )

        self._id = sha256(
            raw_serialized.encode()
        ).hexdigest()
   ```
