### ISSUE TITLE
NIP-01: Tag Order Not Specified

### ISSUE THREAD

**Issue by AndrewDRX** [nostr-protocol/nips#999]
NIP-01 defines a section under the text "To prevent implementation differences from creating a different event ID for the same event, the following rules MUST be followed while serializing".

There should be documentation found there in regard to how tags should be ordered, which is crucial for validating an event ID to verify that an event has not been altered.

For generating a hash ID of a new event, if there is a standard for how to order those tags, then that should be documented (e.g., alphabetical order, subjective order of importance). If there is no standard for this, then that should still be noted for clarification.

For generating a hash ID to validate an existing event, I assume that the tag order should be respective of how it was ordered when the event was received. This should be documented as well for clarification.

**Comment by staab** [comment]
Tags are represented by JSON arrays, which are ordered collections, so that's the order that should be used. Feel free to open a PR for any particular language that needs clarification.

**Comment by AndrewDRX** [comment]
> JSON arrays, which are ordered collections

Duh moment on my part. This is fair. I was asking under the mindset that relays may store event tags under a separate schema in a relational data structure, and recreate the event from there. But I suppose those are just implementation details, and if an event is relayed w/ the tags in a different order, then that is an issue w/ the implementation, not the protocol.

> For generating a hash ID of a new event, if there is a standard for how to order those tags, then that should be documented (e.g., alphabetical order, subjective order of importance).

This was never answered. Is there a SHOULD standard for how these should be ordered?

**Comment by staab** [comment]
>  Is there a SHOULD standard for how these should be ordered?

In some cases yes, as with legacy positional `e` tags (see NIP 10), but in most cases no.

**Comment by alexgleason** [comment]
> I was asking under the mindset that relays may store event tags under a separate schema in a relational data structure, and recreate the event from there.

Check out my genius solution of storing the original tags array as a string, and then storing a separate tags table of only the tags I want to index.

![image](https://github.com/nostr-protocol/nips/assets/3639540/08739dde-a552-48a3-b6a6-0ceec60d485e)

![image](https://github.com/nostr-protocol/nips/assets/3639540/d46a104f-05ad-45ca-8d26-3c4b02445d89)

![image](https://github.com/nostr-protocol/nips/assets/3639540/cbb2f7fc-577a-4ff9-9378-a755ce46f8e5)

![image](https://github.com/nostr-protocol/nips/assets/3639540/94fb5203-a7b0-49f3-a653-7c34c16e0f8d)

https://gitlab.com/soapbox-pub/ditto/-/blob/main/src/storages/events-db.ts

**Comment by AndrewDRX** [comment]
> > I assume that the tag order should be respective of how it was ordered when the event was received
> 
> maybe there is some confusion. tag order, event ids and signatures are not generated when the event is received, it is set in stone when the event is created.

No confusion on my part. Due diligence would be to regenerate the event's hash ID upon receiving an event to verify that the event was not modified. Simply checking the signature against the hash ID does not validate the integrity of the event, but just that the event's hash ID was signed. And to regenerate the hash ID, the tags must be in the same order of which generated the original hash ID.

But as @staab pointed out, JSON arrays are already ordered collections, so my concern there is resolved.

**Comment by AndrewDRX** [comment]
> > I was asking under the mindset that relays may store event tags under a separate schema in a relational data structure, and recreate the event from there.
> 
> Check out my genius solution of storing the original tags array as a string, and then storing a separate tags table of only the tags I want to index.
> 
> ![image](https://private-user-images.githubusercontent.com/3639540/298694819-08739dde-a552-48a3-b6a6-0ceec60d485e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NTExMjksIm5iZiI6MTcwNTk1MDgyOSwicGF0aCI6Ii8zNjM5NTQwLzI5ODY5NDgxOS0wODczOWRkZS1hNTUyLTQ4YTMtYjZhNi0wY2VlYzYwZDQ4NWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjJUMTkxMzQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODQzOGI0ZGRhZGE1ZTZkYmMyYTAxY2ViMGI0OTI5ODU2NzRjZjRkNjc0M2FkZjQ1ZWJjNzUyNmIzY2M3M2IzYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BR-KWn_J6Sz0V_cE4dtoodUB_02ADGIL52cpjkJ4Niw)
> 
> ![image](https://private-user-images.githubusercontent.com/3639540/298694874-d46a104f-05ad-45ca-8d26-3c4b02445d89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NTExMjksIm5iZiI6MTcwNTk1MDgyOSwicGF0aCI6Ii8zNjM5NTQwLzI5ODY5NDg3NC1kNDZhMTA0Zi0wNWFkLTQ1Y2EtOGQyNi0zYzRiMDI0NDVkODkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjJUMTkxMzQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmMzZDNmNjMzM2MyZDUwNmU1ZmQ0NjVjOWNmY2Q2Yzc4YmRlM2VlMDFhMDEyYmRmMzlhNTgyOTJlYjM4OGY2MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.f_kN5WNATt9__O7dcjPMovlIRsV-j7NiIU-Tg6T3_bQ)
> 
> ![image](https://private-user-images.githubusercontent.com/3639540/298695167-cbb2f7fc-577a-4ff9-9378-a755ce46f8e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NTExMjksIm5iZiI6MTcwNTk1MDgyOSwicGF0aCI6Ii8zNjM5NTQwLzI5ODY5NTE2Ny1jYmIyZjdmYy01NzdhLTRmZjktOTM3OC1hNzU1Y2U0NmY4ZTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjJUMTkxMzQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2YwYTczNzgzOTg3ZjY4ODk0NGUxOGU3YWVhNzBmMDkyYTAzMmEwNjcyNzk3YzdiMWM4MDZjOTQxODg1YzlmYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ntsDtxXpt4yRehQb2fQJKJRLCdDoeZCF_FdgV7mfIHA)
> 
> ![image](https://private-user-images.githubusercontent.com/3639540/298695293-94fb5203-a7b0-49f3-a653-7c34c16e0f8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NTExMjksIm5iZiI6MTcwNTk1MDgyOSwicGF0aCI6Ii8zNjM5NTQwLzI5ODY5NTI5My05NGZiNTIwMy1hN2IwLTQ5ZjMtYTY1My03YzM0YzE2ZTBmOGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjJUMTkxMzQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjBlNWJkZTg1M2NiZjdlNTAyMGFhOTJkMzQxN2JmNjE0NDg1N2Y3ZTg3ODQzZTY0ZjBiZjU2Y2U0NzZlZWM2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cvoCJMksnPRql7RpXeW-uWPCvl7daSFUanNQoI6MeqQ)
> 
> https://gitlab.com/soapbox-pub/ditto/-/blob/main/src/storages/events-db.ts

I was thinking of this as well. A little bit of data redundancy isn't always a bad idea. And low risk for a data that won't be updated, so you don't have to worry about it falling out of sync (unless it is a replaceable event).
